! Generated by tools/generate_gaussian_kde_reference.py with SciPy 1.17.0.
module gaussian_kde_reference
    use scifort_kinds, only : dp
    implicit none
    real(dp), parameter :: ref_1d_factor = 7.24779663677695529e-01_dp
    real(dp), parameter :: ref_1d_cov = 1.91079897770374063e+00_dp
    real(dp), parameter :: ref_1d_silverman_factor = 7.67703899274755019e-01_dp
    real(dp), parameter :: ref_1d_silverman_cov = 2.14383074494804982e+00_dp
    real(dp), parameter :: ref_1d_pdf(3) = [ &
        1.48972257680968723e-01_dp, &
        1.68629157004025032e-01_dp, &
        1.36522362811672432e-01_dp]
    real(dp), parameter :: ref_1d_logpdf(3) = [ &
        -1.90399518043281168e+00_dp, &
        -1.78005331239914888e+00_dp, &
        -1.99126684765366946e+00_dp]
    real(dp), parameter :: ref_1d_box = 3.29803201679106206e-01_dp
    real(dp), parameter :: ref_1d_gaussian = 1.60535574292074074e-01_dp
    real(dp), parameter :: ref_1d_kde = 1.41166255303142030e-01_dp
    real(dp), parameter :: ref_2d_neff = 5.40540540540540793e+00_dp
    real(dp), parameter :: ref_2d_factor = 7.54852251457532875e-01_dp
    real(dp), parameter :: ref_2d_cov(2,2) = reshape([ &
        6.89967204061863404e-01_dp, &
        2.01615495854429227e-01_dp, &
        2.01615495854429227e-01_dp, &
        5.37833586730528057e-01_dp], &
        [2,2])
    real(dp), parameter :: ref_2d_inv_cov(2,2) = reshape([ &
        1.62763484207379339e+00_dp, &
        -6.10144873527711296e-01_dp, &
        -6.10144873527711296e-01_dp, &
        2.08803371326453435e+00_dp], &
        [2,2])
    real(dp), parameter :: ref_2d_pdf(3) = [ &
        7.33322832908857997e-02_dp, &
        9.62264122664972105e-02_dp, &
        6.74422634683694705e-02_dp]
    real(dp), parameter :: ref_2d_logpdf(3) = [ &
        -2.61275434016104757e+00_dp, &
        -2.34105140320922400e+00_dp, &
        -2.69648340315350943e+00_dp]
    real(dp), parameter :: ref_2d_gaussian = 6.70814720125327418e-02_dp
    real(dp), parameter :: ref_2d_box = 3.13453294529328685e-01_dp
    real(dp), parameter :: ref_constant_factor = 4.19999999999999984e-01_dp
    real(dp), parameter :: ref_constant_cov(2,2) = reshape([ &
        2.13600920245398784e-01_dp, &
        6.24163803680981635e-02_dp, &
        6.24163803680981635e-02_dp, &
        1.66503202453987698e-01_dp], &
        [2,2])
    real(dp), parameter :: ref_marginal_factor = 7.54852251457532875e-01_dp
    real(dp), parameter :: ref_marginal_pdf(3) = [ &
        2.21136872263291206e-01_dp, &
        3.25676555154521929e-01_dp, &
        2.65790496398457310e-01_dp]
end module gaussian_kde_reference
