! Generated by tools/generate_goodness_of_fit_reference.py with SciPy 1.17.0.
module goodness_of_fit_reference
    use scifort_kinds, only : dp
    implicit none
    public

    real(dp), parameter :: skew_ref(2) = [ &
        1.0108048609177787_dp, 0.31210983614218968_dp &
    ]
    real(dp), parameter :: kurt_ref(2) = [ &
        -1.2276759591008841_dp, 0.21956863467775334_dp &
    ]
    real(dp), parameter :: normal_ref(2) = [ &
        1.5937375263283635_dp, 0.45073812457727613_dp &
    ]
    real(dp), parameter :: jb_ref(2) = [ &
        0.8313439891545038_dp, 0.65989668468096263_dp &
    ]
    real(dp), parameter :: ks1_ref(4) = [ &
        0.15803634777692699_dp, 0.99747168258027374_dp, 0.69999999999999996_dp, &
        -1.0_dp &
    ]
    real(dp), parameter :: ks1_methods_ref(2) = [ &
        0.99963664903936023_dp, 1.0_dp &
    ]
    real(dp), parameter :: ks2_ref(4) = [ &
        0.40000000000000002_dp, 0.74603174603174593_dp, 1.2_dp, &
        1.0_dp &
    ]
    real(dp), parameter :: ks2_one_sided_ref(4) = [ &
        0.14999999999999999_dp, 0.81746031746031744_dp, 0.40000000000000002_dp, &
        0.3968253968253968_dp &
    ]
    real(dp), parameter :: cvm_ref(5) = [ &
        0.025107524937195414_dp, 0.99608718002358199_dp, 0.071428571428571619_dp, &
        0.83391608391608396_dp, 0.85552869801177123_dp &
    ]
    real(dp), parameter :: shapiro_ref(2) = [ &
        0.93249901475758934_dp, 0.47291801143797862_dp &
    ]
    real(dp), parameter :: and_norm_stat = 0.20595986043426251_dp
    real(dp), parameter :: and_norm_critical(5) = [ &
        0.51100000000000001_dp, 0.57499999999999996_dp, 0.68500000000000005_dp, &
        0.79500000000000004_dp, 0.94299999999999995_dp &
    ]
    real(dp), parameter :: and_norm_sig(5) = [ &
        15.0_dp, 10.0_dp, 5.0_dp, &
        2.5_dp, 1.0_dp &
    ]
    real(dp), parameter :: and_norm_fit(2) = [ &
        1.3900000000000001_dp, 0.94569198650159525_dp &
    ]
    real(dp), parameter :: and_expon_stat = 0.622010506121633_dp
    real(dp), parameter :: and_expon_critical(5) = [ &
        0.86399999999999999_dp, 1.002_dp, 1.246_dp, &
        1.5009999999999999_dp, 1.8480000000000001_dp &
    ]
    real(dp), parameter :: and_expon_sig(5) = [ &
        15.0_dp, 10.0_dp, 5.0_dp, &
        2.5_dp, 1.0_dp &
    ]
    real(dp), parameter :: and_expon_fit(2) = [ &
        0.0_dp, 1.4900000000000002_dp &
    ]
    real(dp), parameter :: and_logistic_stat = 0.218299715864962_dp
    real(dp), parameter :: and_logistic_critical(6) = [ &
        0.41599999999999998_dp, 0.54900000000000004_dp, 0.64400000000000002_dp, &
        0.75_dp, 0.88400000000000001_dp, 0.98499999999999999_dp &
    ]
    real(dp), parameter :: and_logistic_sig(6) = [ &
        25.0_dp, 10.0_dp, 5.0_dp, &
        2.5_dp, 1.0_dp, 0.5_dp &
    ]
    real(dp), parameter :: and_logistic_fit(2) = [ &
        1.3292428015366005_dp, 0.53362473615982275_dp &
    ]
    real(dp), parameter :: and_gumbel_r_stat = 0.16533985660643502_dp
    real(dp), parameter :: and_gumbel_r_critical(5) = [ &
        0.44600000000000001_dp, 0.59899999999999998_dp, 0.71199999999999997_dp, &
        0.82499999999999996_dp, 0.97599999999999998_dp &
    ]
    real(dp), parameter :: and_gumbel_r_sig(5) = [ &
        25.0_dp, 10.0_dp, 5.0_dp, &
        2.5_dp, 1.0_dp &
    ]
    real(dp), parameter :: and_gumbel_r_fit(2) = [ &
        0.9650701085943395_dp, 0.7233540061762499_dp &
    ]
    real(dp), parameter :: and_gumbel_l_stat = 0.37274417513671487_dp
    real(dp), parameter :: and_gumbel_l_critical(5) = [ &
        0.44600000000000001_dp, 0.59899999999999998_dp, 0.71199999999999997_dp, &
        0.82499999999999996_dp, 0.97599999999999998_dp &
    ]
    real(dp), parameter :: and_gumbel_l_sig(5) = [ &
        25.0_dp, 10.0_dp, 5.0_dp, &
        2.5_dp, 1.0_dp &
    ]
    real(dp), parameter :: and_gumbel_l_fit(2) = [ &
        1.8563397565283943_dp, 0.91089013916595474_dp &
    ]
end module goodness_of_fit_reference
