! SPDX-License-Identifier: MIT
! Generated by tools/generate_multivariate_reference.py
! SciPy version: 1.17.0
module test_multivariate_reference
    use, intrinsic :: iso_fortran_env, only : int64
    use scifort_kinds, only : dp
    implicit none
    real(dp), parameter :: mvn1_x_ref(2) = [ &
        2.00000000000000011e-01_dp, &
        -4.00000000000000022e-01_dp ]
    real(dp), parameter :: mvn1_mean_ref(2) = [ &
        5.00000000000000000e-01_dp, &
        -1.00000000000000000e+00_dp ]
    real(dp), parameter :: mvn1_cov_ref(2,2) = reshape([ &
        2.00000000000000000e+00_dp, &
        4.00000000000000022e-01_dp, &
        4.00000000000000022e-01_dp, &
        1.50000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: mvn1_pdf_ref = 7.92094733598004419e-02_dp
    real(dp), parameter :: mvn1_logpdf_ref = -2.53565937418604337e+00_dp
    real(dp), parameter :: mvn1_entropy_ref = 3.35977909249590256e+00_dp
    real(dp), parameter :: mvn2_x_ref(3) = [ &
        1.19999999999999996e+00_dp, &
        1.00000000000000006e-01_dp, &
        -6.99999999999999956e-01_dp ]
    real(dp), parameter :: mvn2_mean_ref(3) = [ &
        0.00000000000000000e+00_dp, &
        2.99999999999999989e-01_dp, &
        -1.00000000000000000e+00_dp ]
    real(dp), parameter :: mvn2_cov_ref(3,3) = reshape([ &
        1.00000000000000000e+00_dp, &
        2.00000000000000011e-01_dp, &
        -1.00000000000000006e-01_dp, &
        2.00000000000000011e-01_dp, &
        2.00000000000000000e+00_dp, &
        5.00000000000000000e-01_dp, &
        -1.00000000000000006e-01_dp, &
        5.00000000000000000e-01_dp, &
        1.19999999999999996e+00_dp ], &
        [3,3])
    real(dp), parameter :: mvn2_pdf_ref = 1.78641681609113499e-02_dp
    real(dp), parameter :: mvn2_logpdf_ref = -4.02495835109229461e+00_dp
    real(dp), parameter :: mvn2_entropy_ref = 4.61865379241140150e+00_dp
    real(dp), parameter :: mvn_lower_cov_ref(2,2) = reshape([ &
        2.00000000000000000e+00_dp, &
        4.00000000000000022e-01_dp, &
        9.90000000000000000e+01_dp, &
        1.50000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: mvn_lower_pdf_ref = 7.92094733598004419e-02_dp
    real(dp), parameter :: mvn_singular_cov_ref(2,2) = reshape([ &
        1.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: mvn_singular_on_ref(2) = [ &
        5.00000000000000000e-01_dp, &
        5.00000000000000000e-01_dp ]
    real(dp), parameter :: mvn_singular_off_ref(2) = [ &
        5.00000000000000000e-01_dp, &
        4.00000000000000022e-01_dp ]
    real(dp), parameter :: mvn_singular_on_pdf_ref = 2.48947779975693867e-01_dp
    real(dp), parameter :: mvn_singular_on_logpdf_ref = -1.39051212348464537e+00_dp
    real(dp), parameter :: mvn_singular_off_pdf_ref = 0.00000000000000000e+00_dp
    real(dp), parameter :: mvn_fit_data_ref(2,5) = reshape([ &
        2.00000000000000011e-01_dp, &
        -1.10000000000000009e+00_dp, &
        1.39999999999999991e+00_dp, &
        2.99999999999999989e-01_dp, &
        -6.99999999999999956e-01_dp, &
        8.00000000000000044e-01_dp, &
        2.00000000000000000e+00_dp, &
        -2.00000000000000011e-01_dp, &
        1.00000000000000006e-01_dp, &
        1.69999999999999996e+00_dp ], &
        [2,5])
    real(dp), parameter :: mvn_fit_mean_ref(2) = [ &
        5.99999999999999978e-01_dp, &
        2.99999999999999989e-01_dp ]
    real(dp), parameter :: mvn_fit_cov_ref(2,2) = reshape([ &
        9.39999999999999836e-01_dp, &
        -2.97999999999999932e-01_dp, &
        -2.97999999999999932e-01_dp, &
        8.84000000000000008e-01_dp ], &
        [2,2])
    real(dp), parameter :: mvn_fixed_mean_ref(2) = [ &
        2.50000000000000000e-01_dp, &
        -5.00000000000000000e-01_dp ]
    real(dp), parameter :: mvn_fit_cov_fixed_mean_ref(2,2) = reshape([ &
        1.06249999999999978e+00_dp, &
        -1.80000000000000160e-02_dp, &
        -1.80000000000000160e-02_dp, &
        1.52400000000000024e+00_dp ], &
        [2,2])
    real(dp), parameter :: mvn1_cdf_ref = 3.17852325544398129e-01_dp
    real(dp), parameter :: mvn1_logcdf_ref = -1.14616838914261443e+00_dp
    real(dp), parameter :: mvn_box_lower_ref(2) = [ &
        -1.00000000000000000e+00_dp, &
        -2.00000000000000000e+00_dp ]
    real(dp), parameter :: mvn1_box_cdf_ref = 1.35019951367947949e-01_dp
    real(dp), parameter :: mvn2_cdf_ref = 2.87186442233060168e-01_dp
    real(dp), parameter :: mvn_singular_on_cdf_ref = 6.91462461274013118e-01_dp
    real(dp), parameter :: mvn_singular_off_cdf_ref = 6.55421741610324182e-01_dp
    real(dp), parameter :: mvn_marg_mean_ref(2) = [ &
        -1.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp ]
    real(dp), parameter :: mvn_marg_cov_ref(2,2) = reshape([ &
        1.19999999999999996e+00_dp, &
        -1.00000000000000006e-01_dp, &
        -1.00000000000000006e-01_dp, &
        1.00000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: mvt_x_ref(2) = [ &
        4.00000000000000022e-01_dp, &
        5.00000000000000000e+00_dp ]
    real(dp), parameter :: mvt_loc_ref(2) = [ &
        0.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp ]
    real(dp), parameter :: mvt_shape_ref(2,2) = reshape([ &
        1.00000000000000000e+00_dp, &
        1.00000000000000006e-01_dp, &
        1.00000000000000006e-01_dp, &
        1.00000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: mvt_df_ref = 7.00000000000000000e+00_dp
    real(dp), parameter :: mvt_pdf_ref = 7.57126509139627053e-04_dp
    real(dp), parameter :: mvt_logpdf_ref = -7.18598019941485777e+00_dp
    real(dp), parameter :: mvt_entropy_ref = 3.11856618419688081e+00_dp
    real(dp), parameter :: mvt_cdf_ref = 6.48201453569012487e-01_dp
    real(dp), parameter :: mvt_lower_ref(2) = [ &
        -1.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp ]
    real(dp), parameter :: mvt_box_cdf_ref = 3.94655295479988955e-01_dp
    real(dp), parameter :: mvt_singular_shape_ref(2,2) = reshape([ &
        1.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: mvt_singular_x_ref(2) = [ &
        5.00000000000000000e-01_dp, &
        4.00000000000000022e-01_dp ]
    real(dp), parameter :: mvt_singular_pdf_ref = 9.70424922244224053e-02_dp
    real(dp), parameter :: mvt_singular_logpdf_ref = -2.33260633223154690e+00_dp
    real(dp), parameter :: mvt_marg_loc_ref(2) = [ &
        1.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp ]
    real(dp), parameter :: mvt_marg_shape_ref(2,2) = reshape([ &
        1.00000000000000000e+00_dp, &
        1.00000000000000006e-01_dp, &
        1.00000000000000006e-01_dp, &
        1.00000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: mv4_x_ref(4) = [ &
        2.00000000000000011e-01_dp, &
        -2.99999999999999989e-01_dp, &
        6.99999999999999956e-01_dp, &
        1.00000000000000006e-01_dp ]
    real(dp), parameter :: mv4_loc_ref(4) = [ &
        1.00000000000000006e-01_dp, &
        -2.00000000000000011e-01_dp, &
        0.00000000000000000e+00_dp, &
        2.99999999999999989e-01_dp ]
    real(dp), parameter :: mv4_cov_ref(4,4) = reshape([ &
        1.00000000000000000e+00_dp, &
        5.00000000000000000e-01_dp, &
        -2.00000000000000011e-01_dp, &
        1.00000000000000006e-01_dp, &
        5.00000000000000000e-01_dp, &
        2.00000000000000000e+00_dp, &
        2.99999999999999989e-01_dp, &
        -4.00000000000000022e-01_dp, &
        -2.00000000000000011e-01_dp, &
        2.99999999999999989e-01_dp, &
        1.50000000000000000e+00_dp, &
        2.50000000000000000e-01_dp, &
        1.00000000000000006e-01_dp, &
        -4.00000000000000022e-01_dp, &
        2.50000000000000000e-01_dp, &
        8.00000000000000044e-01_dp ], &
        [4,4])
    real(dp), parameter :: mv4_lower_ref(4) = [ &
        -1.19999999999999996e+00_dp, &
        -1.00000000000000000e+00_dp, &
        -8.00000000000000044e-01_dp, &
        -1.50000000000000000e+00_dp ]
    real(dp), parameter :: mv4_cdf_ref = 8.98368212040629582e-02_dp
    real(dp), parameter :: mv4_box_cdf_ref = 1.72261683491050990e-02_dp
    real(dp), parameter :: mvt4_cdf_ref = 8.92624618042265061e-02_dp
    real(dp), parameter :: mvt4_box_cdf_ref = 1.64023128369739611e-02_dp
    real(dp), parameter :: dir_alpha_ref(3) = [ &
        4.00000000000000022e-01_dp, &
        5.00000000000000000e+00_dp, &
        1.50000000000000000e+01_dp ]
    real(dp), parameter :: dir_x_ref(3) = [ &
        2.00000000000000011e-01_dp, &
        2.00000000000000011e-01_dp, &
        5.99999999999999978e-01_dp ]
    real(dp), parameter :: dir_x_short_ref(2) = [ &
        2.00000000000000011e-01_dp, &
        2.00000000000000011e-01_dp ]
    real(dp), parameter :: dir_pdf_ref = 2.84383168493725524e-01_dp
    real(dp), parameter :: dir_logpdf_ref = -1.25743276531591874e+00_dp
    real(dp), parameter :: dir_mean_ref(3) = [ &
        1.96078431372549052e-02_dp, &
        2.45098039215686292e-01_dp, &
        7.35294117647058876e-01_dp ]
    real(dp), parameter :: dir_var_ref(3) = [ &
        8.98288580596248178e-04_dp, &
        8.64602758823888873e-03_dp, &
        9.09517187853700962e-03_dp ]
    real(dp), parameter :: dir_cov_ref(3,3) = reshape([ &
        8.98288580596248178e-04_dp, &
        -2.24572145149062099e-04_dp, &
        -6.73716435447186215e-04_dp, &
        -2.24572145149062099e-04_dp, &
        8.64602758823888873e-03_dp, &
        -8.42145544308982655e-03_dp, &
        -6.73716435447186215e-04_dp, &
        -8.42145544308982655e-03_dp, &
        9.09517187853700788e-03_dp ], &
        [3,3])
    real(dp), parameter :: dir_entropy_ref = -4.32801624740827151e+00_dp
    real(dp), parameter :: mn_p_ref(3) = [ &
        2.99999999999999989e-01_dp, &
        2.00000000000000011e-01_dp, &
        5.00000000000000000e-01_dp ]
    real(dp), parameter :: mn_x_ref(3) = [ &
        1.00000000000000000e+00_dp, &
        3.00000000000000000e+00_dp, &
        4.00000000000000000e+00_dp ]
    real(dp), parameter :: mn_pmf_ref = 4.20000000000000720e-02_dp
    real(dp), parameter :: mn_logpmf_ref = -3.17008566069876707e+00_dp
    real(dp), parameter :: mn_mean_ref(3) = [ &
        2.39999999999999991e+00_dp, &
        1.60000000000000009e+00_dp, &
        4.00000000000000000e+00_dp ]
    real(dp), parameter :: mn_cov_ref(3,3) = reshape([ &
        1.67999999999999994e+00_dp, &
        -4.79999999999999982e-01_dp, &
        -1.19999999999999996e+00_dp, &
        -4.79999999999999982e-01_dp, &
        1.28000000000000003e+00_dp, &
        -8.00000000000000044e-01_dp, &
        -1.19999999999999996e+00_dp, &
        -8.00000000000000044e-01_dp, &
        2.00000000000000000e+00_dp ], &
        [3,3])
    real(dp), parameter :: mn_entropy_ref = 3.10249234907558158e+00_dp
    real(dp), parameter :: mn_adjust_p_ref(3) = [ &
        2.00000000000000011e-01_dp, &
        2.00000000000000011e-01_dp, &
        2.00000000000000011e-01_dp ]
    real(dp), parameter :: mn_adjust_x_ref(3) = [ &
        1.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp, &
        4.00000000000000000e+00_dp ]
    real(dp), parameter :: mn_adjust_pmf_ref = 1.55519999999999881e-01_dp
    real(dp), parameter :: mn_adjust_logpmf_ref = -1.86098093827000888e+00_dp
    real(dp), parameter :: mn_adjust_mean_ref(3) = [ &
        1.20000000000000018e+00_dp, &
        1.20000000000000018e+00_dp, &
        3.59999999999999964e+00_dp ]
    real(dp), parameter :: dm_alpha_ref(3) = [ &
        3.00000000000000000e+00_dp, &
        4.00000000000000000e+00_dp, &
        5.00000000000000000e+00_dp ]
    real(dp), parameter :: dm_x_ref(3) = [ &
        1.00000000000000000e+00_dp, &
        2.00000000000000000e+00_dp, &
        3.00000000000000000e+00_dp ]
    real(dp), parameter :: dm_pmf_ref = 8.48416289592757861e-02_dp
    real(dp), parameter :: dm_logpmf_ref = -2.46696894910133580e+00_dp
    real(dp), parameter :: dm_mean_ref(3) = [ &
        1.50000000000000000e+00_dp, &
        2.00000000000000000e+00_dp, &
        2.50000000000000000e+00_dp ]
    real(dp), parameter :: dm_var_ref(3) = [ &
        1.55769230769230771e+00_dp, &
        1.84615384615384648e+00_dp, &
        2.01923076923076872e+00_dp ]
    real(dp), parameter :: dm_cov_ref(3,3) = reshape([ &
        1.55769230769230771e+00_dp, &
        -6.92307692307692291e-01_dp, &
        -8.65384615384615419e-01_dp, &
        -6.92307692307692291e-01_dp, &
        1.84615384615384648e+00_dp, &
        -1.15384615384615374e+00_dp, &
        -8.65384615384615419e-01_dp, &
        -1.15384615384615374e+00_dp, &
        2.01923076923076872e+00_dp ], &
        [3,3])
end module test_multivariate_reference
