! Generated by tools/generate_nonparametric_extended_reference.py with SciPy 1.17.0.
module nonparametric_extended_reference
    use scifort_kinds, only : dp
    implicit none
    private
    real(dp), parameter, public :: ansari_ref(12) = [1.70000000000000000e+01_dp, 9.61038961038961026e-01_dp, &
        1.70000000000000000e+01_dp, 4.80519480519480513e-01_dp, &
        1.70000000000000000e+01_dp, 6.53679653679653638e-01_dp, &
        1.80000000000000000e+01_dp, 5.36374406835716577e-01_dp, &
        1.80000000000000000e+01_dp, 2.68187203417858289e-01_dp, &
        1.80000000000000000e+01_dp, 7.31812796582141711e-01_dp]
    real(dp), parameter, public :: mood_ref(12) = [-3.26860225230306722e-01_dp, 7.43773605768231816e-01_dp, &
        -3.26860225230306722e-01_dp, 3.71886802884115908e-01_dp, &
        -3.26860225230306722e-01_dp, 6.28113197115884092e-01_dp, &
        -1.00248623237000545e+00_dp, 3.16108812671663797e-01_dp, &
        -1.00248623237000545e+00_dp, 1.58054406335831898e-01_dp, &
        -1.00248623237000545e+00_dp, 8.41945593664168102e-01_dp]
    real(dp), parameter, public :: epps_ref(4) = [7.97845063750149297e-01_dp, 9.38736730159526078e-01_dp, &
        2.30929876498244280e+00_dp, 8.89169979237281027e-01_dp]
    real(dp), parameter, public :: anderson_ref(6) = [2.84154626642709118e+00_dp, 2.24659537017584884e-02_dp, &
        2.69723332044491881e+00_dp, 2.56092876078370286e-02_dp, &
        2.72617089720147021e+00_dp, 2.49440536077385477e-02_dp]
    real(dp), parameter, public :: anderson_tie_ref(4) = [-1.71422507545859193e-01_dp, 2.50000000000000000e-01_dp, &
        -1.94404619736090717e-01_dp, 2.50000000000000000e-01_dp]
    real(dp), parameter, public :: anderson_critical_ref(7) = [3.25000000000000067e-01_dp, 1.22599999999999998e+00_dp, &
        1.96099999999999985e+00_dp, 2.71799999999999997e+00_dp, &
        3.75199999999999978e+00_dp, 4.59199999999999964e+00_dp, &
        6.54600000000000026e+00_dp]
    real(dp), parameter, public :: median_ref(11) = [4.14150555327025938e+00_dp, 1.26090827740932443e-01_dp, &
        3.40000000000000000e+01_dp, 5.50170843989769853e+00_dp, &
        6.38732760695532725e-02_dp, 3.40000000000000000e+01_dp, &
        4.86827710333145180e+00_dp, 8.76732404935212095e-02_dp, &
        3.40000000000000000e+01_dp, 4.20341033640629114e+00_dp, &
        1.22247797371178288e-01_dp]
    integer, parameter, public :: median_table_1(2, 3) = reshape([5, 11, 10, 5, 7, 10], [2, 3])
    integer, parameter, public :: median_table_2(2, 3) = reshape([5, 11, 11, 4, 9, 8], [2, 3])
    integer, parameter, public :: median_table_3(2, 3) = reshape([5, 11, 10, 4, 7, 8], [2, 3])
end module nonparametric_extended_reference
