! Generated by tools/generate_resampling_inference_reference.py with SciPy 1.17.0.
module resampling_inference_reference
    use scifort_stats, only : dp
    implicit none
    private
    public :: ref_independent_pvalue, ref_samples_pvalue, ref_pairings_pvalue
    public :: ref_monte_greater, ref_power_one, ref_power_two

    real(dp), parameter :: ref_independent_pvalue = 3.33333333333333315e-01_dp
    real(dp), parameter :: ref_samples_pvalue = 5.00000000000000000e-01_dp
    real(dp), parameter :: ref_pairings_pvalue = 1.00000000000000000e+00_dp
    real(dp), parameter :: ref_monte_greater = 1.00000000000000006e-01_dp
    real(dp), parameter :: ref_power_one = 1.00000000000000000e+00_dp
    real(dp), parameter :: ref_power_two = 1.00000000000000000e+00_dp
end module resampling_inference_reference
