! SPDX-License-Identifier: MIT
! Copyright (c) 2026 SciFort contributors

! Tests for the incomplete beta function and the beta, Student t, and F
! distributions. Reference values are generated by
! tools/generate_beta_reference.py.

program test_beta
    use, intrinsic :: ieee_arithmetic, only : ieee_is_finite, ieee_is_nan, &
        ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value
    use scifort_constants, only : scifort_pi
    use scifort_special, only : betainc, betaincc, betainccinv, betaincinv
    use scifort_stats
    use test_beta_reference
    use test_checks, only : check_close, check_true
    implicit none

    real(dp), parameter :: eps = epsilon(1.0_dp)
    integer :: failures
    real(dp) :: nan_value
    real(dp) :: negative_inf
    real(dp) :: positive_inf

    nan_value = ieee_value(0.0_dp, ieee_quiet_nan)
    negative_inf = ieee_value(0.0_dp, ieee_negative_inf)
    positive_inf = ieee_value(0.0_dp, ieee_positive_inf)

    failures = 0
    call test_betainc_reference(failures)
    call test_betainc_special_values(failures)
    call test_betainc_identities(failures)
    call test_inverse_reference(failures)
    call test_t_reference(failures)
    call test_f_reference(failures)
    call test_beta_distribution_reference(failures)
    call test_endpoints(failures)
    call test_invalid_and_ieee(failures)
    call test_extreme_tails(failures)
    call test_monotonicity(failures)
    call test_round_trips(failures)
    call test_distribution_identities(failures)
    call test_elemental(failures)

    if (failures == 0) then
        print '(a)', 'test_beta: PASS'
    else
        print '(a,1x,i0)', 'test_beta: FAIL', failures
        error stop 1
    end if

contains

    subroutine test_betainc_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(ib_a)
            write(label, '(a,i0)') 'betainc reference ', i
            call check_close(trim(label), betainc(ib_a(i), ib_b(i), ib_x(i)), ib_p(i), &
                ib_tol_p(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'betaincc reference ', i
            call check_close(trim(label), betaincc(ib_a(i), ib_b(i), ib_x(i)), ib_q(i), &
                ib_tol_q(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'beta logcdf reference ', i
            call check_close(trim(label), beta_logcdf(ib_x(i), ib_a(i), ib_b(i)), &
                ib_logp(i), ib_tol_logp(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'beta logsf reference ', i
            call check_close(trim(label), beta_logsf(ib_x(i), ib_a(i), ib_b(i)), &
                ib_logq(i), ib_tol_logq(i), 0.0_dp, failures)
        end do
    end subroutine test_betainc_reference

    ! Conventions follow scipy.special.betainc: a and b must be finite and
    ! positive and 0 <= x <= 1.
    subroutine test_betainc_special_values(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_close('betainc(1, 1, 0)', betainc(1.0_dp, 1.0_dp, 0.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('betainc(1, 1, 1)', betainc(1.0_dp, 1.0_dp, 1.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('betaincc(2, 3, 0)', betaincc(2.0_dp, 3.0_dp, 0.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('betaincc(2, 3, 1)', betaincc(2.0_dp, 3.0_dp, 1.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('betainc(0, 1, 0.5)', ieee_is_nan(betainc(0.0_dp, 1.0_dp, 0.5_dp)), &
            failures)
        call check_true('betainc(1, -1, 0.5)', &
            ieee_is_nan(betainc(1.0_dp, -1.0_dp, 0.5_dp)), failures)
        call check_true('betainc(inf, 1, 0.5)', &
            ieee_is_nan(betainc(positive_inf, 1.0_dp, 0.5_dp)), failures)
        call check_true('betainc(1, 1, 1.5)', ieee_is_nan(betainc(1.0_dp, 1.0_dp, 1.5_dp)), &
            failures)
        call check_true('betaincc NaN x', ieee_is_nan(betaincc(1.0_dp, 1.0_dp, nan_value)), &
            failures)
        call check_close('betaincinv(1, 1, 0)', betaincinv(1.0_dp, 1.0_dp, 0.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('betaincinv(1, 1, 1)', betaincinv(1.0_dp, 1.0_dp, 1.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('betainccinv(1, 1, 0)', betainccinv(1.0_dp, 1.0_dp, 0.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('betainccinv(1, 1, 1)', betainccinv(1.0_dp, 1.0_dp, 1.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('betaincinv(0, 1, 0.5)', &
            ieee_is_nan(betaincinv(0.0_dp, 1.0_dp, 0.5_dp)), failures)
        call check_true('betainccinv p > 1', &
            ieee_is_nan(betainccinv(2.0_dp, 3.0_dp, 1.5_dp)), failures)
    end subroutine test_betainc_special_values

    subroutine test_betainc_identities(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: j
        integer :: m
        integer :: n
        real(dp) :: binomial
        real(dp) :: coefficient
        real(dp) :: x

        ! x and 1 - x are both exact in binary64.
        x = 0.25_dp
        call check_close('I_x(1, 1) = x', betainc(1.0_dp, 1.0_dp, x), x, 0.0_dp, &
            2.0_dp * eps, failures)
        call check_close('I_x(a, 1) = x**a', betainc(3.7_dp, 1.0_dp, x), x**3.7_dp, &
            0.0_dp, 8.0_dp * eps, failures)
        call check_close('1 - I_x(1, b) = (1 - x)**b', betaincc(1.0_dp, 2.5_dp, x), &
            (1.0_dp - x)**2.5_dp, 0.0_dp, 8.0_dp * eps, failures)
        call check_close('symmetry DLMF 8.17.4', betainc(2.5_dp, 7.0_dp, x), &
            betaincc(7.0_dp, 2.5_dp, 1.0_dp - x), 0.0_dp, 4.0_dp * eps, failures)

        ! DLMF 8.17.5: I_x(m, n - m + 1) = sum over j = m..n of C(n, j) x**j (1 - x)**(n - j).
        n = 12
        do m = 1, n
            binomial = 0.0_dp
            coefficient = 1.0_dp
            do j = 0, n
                if (j > 0) coefficient = coefficient * real(n - j + 1, dp) / real(j, dp)
                if (j >= m) binomial = binomial + coefficient * x**j * (1.0_dp - x)**(n - j)
            end do
            call check_close('binomial sum DLMF 8.17.5', &
                betainc(real(m, dp), real(n - m + 1, dp), x), binomial, 0.0_dp, &
                1.0e-14_dp, failures)
        end do
    end subroutine test_betainc_identities

    subroutine test_inverse_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(ibinv_a)
            write(label, '(a,i0)') 'betaincinv reference ', i
            call check_close(trim(label), betaincinv(ibinv_a(i), ibinv_b(i), ibinv_p(i)), &
                ibinv_x(i), ibinv_tol(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'betainccinv reference ', i
            call check_close(trim(label), betainccinv(ibinv_a(i), ibinv_b(i), ibinv_p(i)), &
                ibcinv_x(i), ibcinv_tol(i), 0.0_dp, failures)
        end do
    end subroutine test_inverse_reference

    subroutine test_t_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(st_x)
            write(label, '(a,i0)') 't logpdf reference ', i
            call check_close(trim(label), t_logpdf(st_x(i), st_df(i)), st_logpdf(i), &
                st_tol_logpdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 't cdf reference ', i
            call check_close(trim(label), t_cdf(st_x(i), st_df(i)), st_cdf(i), &
                st_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 't sf reference ', i
            call check_close(trim(label), t_sf(st_x(i), st_df(i)), st_sf(i), &
                st_tol_sf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 't logcdf reference ', i
            call check_close(trim(label), t_logcdf(st_x(i), st_df(i)), log(st_cdf(i)), &
                st_tol_cdf(i) / st_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 't logsf reference ', i
            call check_close(trim(label), t_logsf(st_x(i), st_df(i)), log(st_sf(i)), &
                st_tol_sf(i) / st_sf(i), 0.0_dp, failures)
        end do
    end subroutine test_t_reference

    subroutine test_f_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(fd_x)
            write(label, '(a,i0)') 'F logpdf reference ', i
            call check_close(trim(label), f_logpdf(fd_x(i), fd_dfn(i), fd_dfd(i)), &
                fd_logpdf(i), fd_tol_logpdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'F cdf reference ', i
            call check_close(trim(label), f_cdf(fd_x(i), fd_dfn(i), fd_dfd(i)), fd_cdf(i), &
                fd_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'F sf reference ', i
            call check_close(trim(label), f_sf(fd_x(i), fd_dfn(i), fd_dfd(i)), fd_sf(i), &
                fd_tol_sf(i), 0.0_dp, failures)
        end do
    end subroutine test_f_reference

    subroutine test_beta_distribution_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(bd_x)
            write(label, '(a,i0)') 'beta logpdf reference ', i
            call check_close(trim(label), &
                beta_logpdf(bd_x(i), bd_a(i), bd_b(i), bd_loc(i), bd_scale(i)), &
                bd_logpdf(i), bd_tol_logpdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'beta pdf reference ', i
            call check_close(trim(label), &
                beta_pdf(bd_x(i), bd_a(i), bd_b(i), bd_loc(i), bd_scale(i)), &
                exp(bd_logpdf(i)), 0.0_dp, bd_tol_logpdf(i) + 2.0_dp * eps, failures)
            write(label, '(a,i0)') 'beta cdf reference ', i
            call check_close(trim(label), &
                beta_cdf(bd_x(i), bd_a(i), bd_b(i), bd_loc(i), bd_scale(i)), &
                bd_cdf(i), bd_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'beta sf reference ', i
            call check_close(trim(label), &
                beta_sf(bd_x(i), bd_a(i), bd_b(i), bd_loc(i), bd_scale(i)), &
                bd_sf(i), bd_tol_sf(i), 0.0_dp, failures)
        end do
    end subroutine test_beta_distribution_reference

    subroutine test_endpoints(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_true('beta pdf 0, a < 1', beta_pdf(0.0_dp, 0.5_dp, 2.0_dp) > huge(1.0_dp), &
            failures)
        call check_close('beta pdf 0, a = 1', beta_pdf(0.0_dp, 1.0_dp, 3.0_dp), 3.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('beta pdf 0, a > 1', beta_pdf(0.0_dp, 2.0_dp, 3.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('beta pdf 1, b < 1', beta_pdf(1.0_dp, 1.0_dp, 0.5_dp) > huge(1.0_dp), &
            failures)
        call check_close('beta pdf 1, b = 1, scaled', &
            beta_pdf(5.0_dp, 2.0_dp, 1.0_dp, 1.0_dp, 4.0_dp), 0.5_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('beta pdf outside', beta_pdf(1.5_dp, 2.0_dp, 3.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('beta cdf at 1', beta_cdf(1.0_dp, 2.0_dp, 3.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('beta logsf at 1', beta_logsf(1.0_dp, 2.0_dp, 3.0_dp) < -huge(1.0_dp), &
            failures)
        call check_close('beta ppf 0', beta_ppf(0.0_dp, 2.0_dp, 3.0_dp, 1.0_dp, 4.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('beta ppf 1', beta_ppf(1.0_dp, 2.0_dp, 3.0_dp, 1.0_dp, 4.0_dp), &
            5.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('beta isf 0', beta_isf(0.0_dp, 2.0_dp, 3.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)

        call check_close('t cdf 0', t_cdf(3.0_dp, 4.0_dp, 3.0_dp), 0.5_dp, 0.0_dp, 0.0_dp, &
            failures)
        call check_close('t cdf -inf', t_cdf(negative_inf, 4.0_dp), 0.0_dp, 0.0_dp, &
            0.0_dp, failures)
        call check_close('t sf -inf', t_sf(negative_inf, 4.0_dp), 1.0_dp, 0.0_dp, &
            0.0_dp, failures)
        call check_close('t pdf inf', t_pdf(positive_inf, 4.0_dp), 0.0_dp, 0.0_dp, &
            0.0_dp, failures)
        call check_true('t ppf 0', t_ppf(0.0_dp, 4.0_dp) < -huge(1.0_dp), failures)
        call check_true('t isf 0', t_isf(0.0_dp, 4.0_dp) > huge(1.0_dp), failures)
        call check_close('t ppf 1/2', t_ppf(0.5_dp, 4.0_dp, 2.0_dp), 2.0_dp, 0.0_dp, &
            0.0_dp, failures)

        call check_true('F pdf 0, dfn < 2', f_pdf(0.0_dp, 1.0_dp, 5.0_dp) > huge(1.0_dp), &
            failures)
        call check_close('F pdf 0, dfn = 2', f_pdf(0.0_dp, 2.0_dp, 5.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('F pdf 0, dfn > 2', f_pdf(0.0_dp, 3.0_dp, 5.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('F cdf inf', f_cdf(positive_inf, 3.0_dp, 5.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('F ppf 0', f_ppf(0.0_dp, 3.0_dp, 5.0_dp, 2.0_dp), 2.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('F isf 0', f_isf(0.0_dp, 3.0_dp, 5.0_dp) > huge(1.0_dp), failures)
    end subroutine test_endpoints

    subroutine test_invalid_and_ieee(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_true('beta zero shape', ieee_is_nan(beta_cdf(0.5_dp, 0.0_dp, 1.0_dp)), &
            failures)
        call check_true('beta infinite shape', &
            ieee_is_nan(beta_pdf(0.5_dp, 1.0_dp, positive_inf)), failures)
        call check_true('beta NaN x', ieee_is_nan(beta_sf(nan_value, 2.0_dp, 2.0_dp)), &
            failures)
        call check_true('beta ppf p < 0', ieee_is_nan(beta_ppf(-0.1_dp, 2.0_dp, 2.0_dp)), &
            failures)
        call check_true('t zero df', ieee_is_nan(t_cdf(1.0_dp, 0.0_dp)), failures)
        call check_true('t NaN df', ieee_is_nan(t_pdf(1.0_dp, nan_value)), failures)
        call check_true('t NaN x', ieee_is_nan(t_logsf(nan_value, 3.0_dp)), failures)
        call check_true('t zero scale', ieee_is_nan(t_cdf(1.0_dp, 3.0_dp, scale=0.0_dp)), &
            failures)
        call check_true('t ppf p > 1', ieee_is_nan(t_ppf(1.5_dp, 3.0_dp)), failures)
        call check_true('F infinite dfd', ieee_is_nan(f_cdf(1.0_dp, 2.0_dp, positive_inf)), &
            failures)
        call check_true('F negative dfn', ieee_is_nan(f_pdf(1.0_dp, -2.0_dp, 3.0_dp)), &
            failures)
        call check_true('F NaN x', ieee_is_nan(f_logcdf(nan_value, 2.0_dp, 3.0_dp)), &
            failures)
    end subroutine test_invalid_and_ieee

    ! Exact limits of the Cauchy case df = 1: sf(t) = atan(1/t) / pi and
    ! ppf(p) = -1 / tan(pi p), both of which reduce to 1 / (pi t) far out.
    subroutine test_extreme_tails(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_close('t sf 1e200, df 1', t_sf(1.0e200_dp, 1.0_dp), &
            1.0_dp / (scifort_pi * 1.0e200_dp), 0.0_dp, 1.0e-14_dp, failures)
        call check_close('t logcdf -1e200, df 1', t_logcdf(-1.0e200_dp, 1.0_dp), &
            -log(scifort_pi) - 200.0_dp * log(10.0_dp), 0.0_dp, 1.0e-14_dp, failures)
        call check_close('t ppf 1e-300, df 1', t_ppf(1.0e-300_dp, 1.0_dp), &
            -1.0_dp / (scifort_pi * 1.0e-300_dp), 0.0_dp, 1.0e-13_dp, failures)
        call check_close('t isf 1e-300, df 3', t_sf(t_isf(1.0e-300_dp, 3.0_dp), 3.0_dp), &
            1.0e-300_dp, 0.0_dp, 1.0e-12_dp, failures)
    end subroutine test_extreme_tails

    subroutine test_monotonicity(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        logical :: ok
        real(dp) :: previous
        real(dp) :: value
        real(dp) :: x

        ok = .true.
        previous = 0.0_dp
        do i = -400, 400
            x = sign(10.0_dp ** (abs(real(i, dp)) / 100.0_dp), real(i, dp))
            value = t_cdf(x, 2.5_dp)
            ok = ok .and. value >= previous .and. value <= 1.0_dp
            previous = value
        end do
        call check_true('t cdf monotone', ok, failures)

        ok = .true.
        previous = 0.0_dp
        do i = -600, 600
            x = 10.0_dp ** (real(i, dp) / 100.0_dp)
            value = f_cdf(x, 3.0_dp, 7.0_dp)
            ok = ok .and. value >= previous .and. value <= 1.0_dp
            previous = value
        end do
        call check_true('F cdf monotone', ok, failures)

        ok = .true.
        previous = 0.0_dp
        do i = 1, 999
            x = real(i, dp) / 1000.0_dp
            value = beta_cdf(x, 0.7_dp, 300.0_dp)
            ok = ok .and. value >= previous .and. value <= 1.0_dp .and. &
                beta_pdf(x, 0.7_dp, 300.0_dp) >= 0.0_dp
            previous = value
        end do
        call check_true('beta cdf monotone', ok, failures)
    end subroutine test_monotonicity

    ! A quantile carries a relative error of order eps, which moves a tail V
    ! by about eps x f(x) / V; the forward function adds eps (1 + |log V|).
    ! A quantile that underflows to zero, overflows, or rounds to the upper
    ! support endpoint cannot reproduce p; the test then checks that this is
    ! justified.
    subroutine test_round_trips(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        real(dp), parameter :: probabilities(6) = [1.0e-100_dp, 1.0e-8_dp, 0.025_dp, &
            0.3_dp, 0.5_dp, 0.99_dp]
        real(dp), parameter :: dfs(5) = [0.5_dp, 1.0_dp, 3.0_dp, 40.0_dp, 1.0e5_dp]
        integer :: i
        integer :: j
        real(dp) :: p
        real(dp) :: rtol
        real(dp) :: x

        do i = 1, size(dfs)
            do j = 1, size(probabilities)
                p = probabilities(j)
                x = t_ppf(p, dfs(i))
                rtol = 20.0_dp * eps * (1.0_dp + abs(log(p)) + abs(x) * t_pdf(x, dfs(i)) / p)
                call check_close('t cdf(ppf(p))', t_cdf(x, dfs(i)), p, 0.0_dp, rtol, failures)
                x = f_ppf(p, dfs(i), 7.0_dp)
                if (x == 0.0_dp) then
                    call check_true('F ppf underflow is justified', &
                        f_cdf(tiny(1.0_dp), dfs(i), 7.0_dp) >= p, failures)
                else
                    rtol = 20.0_dp * eps * (1.0_dp + abs(log(p)) + &
                        x * f_pdf(x, dfs(i), 7.0_dp) / p)
                    call check_close('F cdf(ppf(p))', f_cdf(x, dfs(i), 7.0_dp), p, 0.0_dp, &
                        rtol, failures)
                end if
                x = f_isf(p, 7.0_dp, dfs(i))
                if (.not. ieee_is_finite(x)) then
                    call check_true('F isf overflow is justified', &
                        f_sf(huge(1.0_dp), 7.0_dp, dfs(i)) >= p, failures)
                else
                    rtol = 20.0_dp * eps * (1.0_dp + abs(log(p)) + &
                        x * f_pdf(x, 7.0_dp, dfs(i)) / p)
                    call check_close('F sf(isf(p))', f_sf(x, 7.0_dp, dfs(i)), p, 0.0_dp, &
                        rtol, failures)
                end if
                x = beta_isf(p, dfs(i), 2.0_dp)
                if (x == 1.0_dp) then
                    ! The exact root lies above the largest double below one.
                    call check_true('beta isf rounding to 1 is justified', &
                        beta_sf(1.0_dp - epsilon(1.0_dp) / 2.0_dp, dfs(i), 2.0_dp) >= p, &
                        failures)
                else
                    rtol = 20.0_dp * eps * (1.0_dp + abs(log(p)) + &
                        x * beta_pdf(x, dfs(i), 2.0_dp) / p)
                    call check_close('beta sf(isf(p))', beta_sf(x, dfs(i), 2.0_dp), p, &
                        0.0_dp, rtol, failures)
                end if
            end do
        end do
    end subroutine test_round_trips

    subroutine test_distribution_identities(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        real(dp) :: t(6)

        t = [-50.0_dp, -2.0_dp, -0.1_dp, 0.3_dp, 4.0_dp, 1.0e6_dp]
        do i = 1, size(t)
            call check_close('t(1) cdf = Cauchy', t_cdf(t(i), 1.0_dp), cauchy_cdf(t(i)), &
                0.0_dp, 4.0_dp * eps, failures)
            call check_close('t(1) logsf = Cauchy', t_logsf(t(i), 1.0_dp), &
                cauchy_logsf(t(i)), 0.0_dp, 4.0_dp * eps, failures)
            ! Closed form for df = 2: cdf = 1/2 + t / (2 sqrt(2 + t**2)).
            call check_close('t(2) closed form', t_cdf(t(i), 2.0_dp), &
                0.5_dp + t(i) / (2.0_dp * sqrt(2.0_dp + t(i)**2)), 1.0e-16_dp, 1.0e-14_dp, &
                failures)
            call check_close('t(inf) = normal', t_cdf(t(i), positive_inf, 1.0_dp, 2.0_dp), &
                normal_cdf(t(i), 1.0_dp, 2.0_dp), 0.0_dp, 0.0_dp, failures)
            ! F(1, df) is the distribution of the square of t(df).
            call check_close('F(1, df) = t squared', f_sf(t(i)**2, 1.0_dp, 6.0_dp), &
                2.0_dp * t_sf(abs(t(i)), 6.0_dp), 0.0_dp, 1.0e-14_dp, failures)
            call check_close('t pdf symmetry', t_pdf(t(i), 3.5_dp), t_pdf(-t(i), 3.5_dp), &
                0.0_dp, 0.0_dp, failures)
            call check_close('t cdf + sf', t_cdf(t(i), 3.5_dp) + t_sf(t(i), 3.5_dp), 1.0_dp, &
                2.0_dp * eps, 0.0_dp, failures)
        end do

        call check_close('beta(1, 1) = uniform', beta_cdf(2.6_dp, 1.0_dp, 1.0_dp, 2.0_dp, &
            3.0_dp), uniform_cdf(2.6_dp, 2.0_dp, 3.0_dp), 0.0_dp, 4.0_dp * eps, failures)
        call check_close('beta ppf symmetry', beta_ppf(0.2_dp, 3.0_dp, 5.0_dp), &
            1.0_dp - beta_ppf(0.8_dp, 5.0_dp, 3.0_dp), 1.0e-15_dp, 0.0_dp, failures)
        call check_close('t ppf symmetry', t_ppf(0.01_dp, 7.0_dp), -t_isf(0.01_dp, 7.0_dp), &
            0.0_dp, 0.0_dp, failures)
    end subroutine test_distribution_identities

    subroutine test_elemental(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        real(dp) :: actual(4)
        real(dp) :: x(4)

        x = [0.1_dp, 0.4_dp, 0.7_dp, 0.95_dp]
        actual = betainc(2.0_dp, 5.0_dp, x)
        do i = 1, size(x)
            call check_close('betainc elemental', actual(i), betainc(2.0_dp, 5.0_dp, x(i)), &
                0.0_dp, 0.0_dp, failures)
        end do
        actual = t_cdf(x, [1.0_dp, 2.0_dp, 5.0_dp, 30.0_dp])
        call check_close('t cdf elemental', actual(3), t_cdf(x(3), 5.0_dp), 0.0_dp, &
            0.0_dp, failures)
        actual = f_ppf(x, 3.0_dp, 9.0_dp)
        call check_close('F ppf elemental', actual(4), f_ppf(x(4), 3.0_dp, 9.0_dp), &
            0.0_dp, 0.0_dp, failures)
    end subroutine test_elemental

end program test_beta
