! SPDX-License-Identifier: MIT
! Copyright (c) 2026 SciFort contributors

! Tests for the lognormal, weibull, pareto, and rayleigh distributions.
! Reference values are generated by tools/generate_continuous_reference.py.

program test_continuous
    use, intrinsic :: ieee_arithmetic, only : ieee_is_finite, ieee_is_nan, &
        ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value
    use scifort_constants, only : scifort_sqrt_two
    use scifort_kinds, only : dp
    use scifort_stats
    use test_checks, only : check_close, check_true
    use test_continuous_reference
    implicit none

    real(dp), parameter :: eps = epsilon(1.0_dp)
    integer :: failures
    real(dp) :: nan_value
    real(dp) :: negative_inf
    real(dp) :: positive_inf

    nan_value = ieee_value(0.0_dp, ieee_quiet_nan)
    negative_inf = ieee_value(0.0_dp, ieee_negative_inf)
    positive_inf = ieee_value(0.0_dp, ieee_positive_inf)

    failures = 0
    call test_lognormal_reference(failures)
    call test_weibull_reference(failures)
    call test_pareto_reference(failures)
    call test_rayleigh_reference(failures)
    call test_endpoints(failures)
    call test_round_trips(failures)
    call test_identities(failures)
    call test_invalid_and_ieee(failures)
    call test_elemental(failures)

    if (failures == 0) then
        print '(a)', 'test_continuous: PASS'
    else
        print '(a,1x,i0)', 'test_continuous: FAIL', failures
        error stop 1
    end if

contains

    subroutine test_lognormal_reference(failures)
        ! Compares lognormal functions against high-precision reference values.
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(ln_x)
            write(label, '(a,i0)') 'lognormal pdf ref ', i
            call check_close(trim(label), lognormal_pdf(ln_x(i), ln_s(i)), ln_pdf(i), &
                ln_tol(i) * ln_pdf(i), ln_tol(i), failures)

            write(label, '(a,i0)') 'lognormal cdf ref ', i
            call check_close(trim(label), lognormal_cdf(ln_x(i), ln_s(i)), ln_cdf(i), &
                ln_tol(i) * ln_cdf(i), ln_tol(i), failures)

            write(label, '(a,i0)') 'lognormal sf ref ', i
            call check_close(trim(label), lognormal_sf(ln_x(i), ln_s(i)), ln_sf(i), &
                ln_tol(i) * ln_sf(i), ln_tol(i), failures)

            write(label, '(a,i0)') 'lognormal logcdf ref ', i
            call check_close(trim(label), lognormal_logcdf(ln_x(i), ln_s(i)), ln_logcdf(i), &
                ln_tol(i), ln_tol(i), failures)

            write(label, '(a,i0)') 'lognormal logsf ref ', i
            call check_close(trim(label), lognormal_logsf(ln_x(i), ln_s(i)), ln_logsf(i), &
                ln_tol(i), ln_tol(i), failures)
        end do
    end subroutine test_lognormal_reference

    subroutine test_weibull_reference(failures)
        ! Compares weibull functions against high-precision reference values.
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(wb_x)
            write(label, '(a,i0)') 'weibull pdf ref ', i
            call check_close(trim(label), weibull_pdf(wb_x(i), wb_c(i)), wb_pdf(i), &
                wb_tol(i) * wb_pdf(i), wb_tol(i), failures)

            write(label, '(a,i0)') 'weibull cdf ref ', i
            call check_close(trim(label), weibull_cdf(wb_x(i), wb_c(i)), wb_cdf(i), &
                wb_tol(i) * wb_cdf(i), wb_tol(i), failures)

            write(label, '(a,i0)') 'weibull sf ref ', i
            call check_close(trim(label), weibull_sf(wb_x(i), wb_c(i)), wb_sf(i), &
                wb_tol(i) * wb_sf(i), wb_tol(i), failures)

            write(label, '(a,i0)') 'weibull logcdf ref ', i
            call check_close(trim(label), weibull_logcdf(wb_x(i), wb_c(i)), wb_logcdf(i), &
                wb_tol(i), wb_tol(i), failures)

            write(label, '(a,i0)') 'weibull logsf ref ', i
            call check_close(trim(label), weibull_logsf(wb_x(i), wb_c(i)), wb_logsf(i), &
                wb_tol(i), wb_tol(i), failures)
        end do
    end subroutine test_weibull_reference

    subroutine test_pareto_reference(failures)
        ! Compares pareto functions against high-precision reference values.
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(pa_x)
            write(label, '(a,i0)') 'pareto pdf ref ', i
            call check_close(trim(label), pareto_pdf(pa_x(i), pa_b(i)), pa_pdf(i), &
                pa_tol(i) * pa_pdf(i), pa_tol(i), failures)

            write(label, '(a,i0)') 'pareto cdf ref ', i
            call check_close(trim(label), pareto_cdf(pa_x(i), pa_b(i)), pa_cdf(i), &
                pa_tol(i) * pa_cdf(i), pa_tol(i), failures)

            write(label, '(a,i0)') 'pareto sf ref ', i
            call check_close(trim(label), pareto_sf(pa_x(i), pa_b(i)), pa_sf(i), &
                pa_tol(i) * pa_sf(i), pa_tol(i), failures)

            write(label, '(a,i0)') 'pareto logcdf ref ', i
            call check_close(trim(label), pareto_logcdf(pa_x(i), pa_b(i)), pa_logcdf(i), &
                pa_tol(i), pa_tol(i), failures)

            write(label, '(a,i0)') 'pareto logsf ref ', i
            call check_close(trim(label), pareto_logsf(pa_x(i), pa_b(i)), pa_logsf(i), &
                pa_tol(i), pa_tol(i), failures)
        end do
    end subroutine test_pareto_reference

    subroutine test_rayleigh_reference(failures)
        ! Compares rayleigh functions against high-precision reference values.
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(ry_x)
            write(label, '(a,i0)') 'rayleigh pdf ref ', i
            call check_close(trim(label), rayleigh_pdf(ry_x(i)), ry_pdf(i), &
                ry_tol(i) * ry_pdf(i), ry_tol(i), failures)

            write(label, '(a,i0)') 'rayleigh cdf ref ', i
            call check_close(trim(label), rayleigh_cdf(ry_x(i)), ry_cdf(i), &
                ry_tol(i) * ry_cdf(i), ry_tol(i), failures)

            write(label, '(a,i0)') 'rayleigh sf ref ', i
            call check_close(trim(label), rayleigh_sf(ry_x(i)), ry_sf(i), &
                ry_tol(i) * ry_sf(i), ry_tol(i), failures)

            write(label, '(a,i0)') 'rayleigh logcdf ref ', i
            call check_close(trim(label), rayleigh_logcdf(ry_x(i)), ry_logcdf(i), &
                ry_tol(i), ry_tol(i), failures)

            write(label, '(a,i0)') 'rayleigh logsf ref ', i
            call check_close(trim(label), rayleigh_logsf(ry_x(i)), ry_logsf(i), &
                ry_tol(i), ry_tol(i), failures)
        end do
    end subroutine test_rayleigh_reference

    subroutine test_endpoints(failures)
        ! Checks boundary, support endpoint, and quantile endpoint behaviors.
        integer, intent(inout) :: failures !! running count of failed checks

        ! Lognormal endpoints
        call check_close('lognormal pdf 0', lognormal_pdf(0.0_dp, 1.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('lognormal cdf 0', lognormal_cdf(0.0_dp, 1.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('lognormal sf 0', lognormal_sf(0.0_dp, 1.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('lognormal ppf 0', lognormal_ppf(0.0_dp, 1.0_dp, loc=2.0_dp), &
            2.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('lognormal ppf 1 is inf', &
            .not. ieee_is_finite(lognormal_ppf(1.0_dp, 1.0_dp)) .and. &
            lognormal_ppf(1.0_dp, 1.0_dp) > 0.0_dp, failures)
        call check_close('lognormal isf 1', lognormal_isf(1.0_dp, 1.0_dp, loc=2.0_dp), &
            2.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('lognormal isf 0 is inf', &
            .not. ieee_is_finite(lognormal_isf(0.0_dp, 1.0_dp)) .and. &
            lognormal_isf(0.0_dp, 1.0_dp) > 0.0_dp, failures)

        ! Weibull endpoints
        call check_close('weibull cdf 0', weibull_cdf(0.0_dp, 1.5_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('weibull sf 0', weibull_sf(0.0_dp, 1.5_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('weibull pdf 0 c<1 is inf', &
            .not. ieee_is_finite(weibull_pdf(0.0_dp, 0.5_dp)) .and. &
            weibull_pdf(0.0_dp, 0.5_dp) > 0.0_dp, failures)
        call check_close('weibull pdf 0 c=1', weibull_pdf(0.0_dp, 1.0_dp, scale=2.0_dp), &
            0.5_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('weibull pdf 0 c>1', weibull_pdf(0.0_dp, 2.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('weibull ppf 0', weibull_ppf(0.0_dp, 1.5_dp, loc=3.0_dp), &
            3.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('weibull ppf 1 is inf', &
            .not. ieee_is_finite(weibull_ppf(1.0_dp, 1.5_dp)) .and. &
            weibull_ppf(1.0_dp, 1.5_dp) > 0.0_dp, failures)
        call check_close('weibull isf 1', weibull_isf(1.0_dp, 1.5_dp, loc=3.0_dp), &
            3.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('weibull isf 0 is inf', &
            .not. ieee_is_finite(weibull_isf(0.0_dp, 1.5_dp)) .and. &
            weibull_isf(0.0_dp, 1.5_dp) > 0.0_dp, failures)

        ! Pareto endpoints
        call check_close('pareto cdf 1', pareto_cdf(1.0_dp, 2.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('pareto sf 1', pareto_sf(1.0_dp, 2.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('pareto pdf 1', pareto_pdf(1.0_dp, 2.0_dp, scale=2.0_dp, loc=0.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('pareto pdf loc+scale', pareto_pdf(3.0_dp, 2.0_dp, loc=1.0_dp, scale=2.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('pareto ppf 0', pareto_ppf(0.0_dp, 2.0_dp, loc=1.0_dp, scale=2.0_dp), &
            3.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('pareto ppf 1 is inf', &
            .not. ieee_is_finite(pareto_ppf(1.0_dp, 2.0_dp)) .and. &
            pareto_ppf(1.0_dp, 2.0_dp) > 0.0_dp, failures)
        call check_close('pareto isf 1', pareto_isf(1.0_dp, 2.0_dp, loc=1.0_dp, scale=2.0_dp), &
            3.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('pareto isf 0 is inf', &
            .not. ieee_is_finite(pareto_isf(0.0_dp, 2.0_dp)) .and. &
            pareto_isf(0.0_dp, 2.0_dp) > 0.0_dp, failures)

        ! Rayleigh endpoints
        call check_close('rayleigh pdf 0', rayleigh_pdf(0.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('rayleigh cdf 0', rayleigh_cdf(0.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('rayleigh sf 0', rayleigh_sf(0.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('rayleigh ppf 0', rayleigh_ppf(0.0_dp, loc=1.5_dp), &
            1.5_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('rayleigh ppf 1 is inf', &
            .not. ieee_is_finite(rayleigh_ppf(1.0_dp)) .and. &
            rayleigh_ppf(1.0_dp) > 0.0_dp, failures)
        call check_close('rayleigh isf 1', rayleigh_isf(1.0_dp, loc=1.5_dp), &
            1.5_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('rayleigh isf 0 is inf', &
            .not. ieee_is_finite(rayleigh_isf(0.0_dp)) .and. &
            rayleigh_isf(0.0_dp) > 0.0_dp, failures)
    end subroutine test_endpoints

    subroutine test_round_trips(failures)
        ! Checks that cdf(ppf(p)) == p and sf(isf(p)) == p.
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        real(dp) :: p(7)
        real(dp) :: q
        character(len=64) :: label

        p = [1.0e-6_dp, 0.01_dp, 0.1_dp, 0.5_dp, 0.9_dp, 0.99_dp, 1.0_dp - 1.0e-6_dp]

        do i = 1, size(p)
            q = p(i)
            write(label, '(a,i0)') 'lognormal cdf ppf round trip ', i
            call check_close(trim(label), lognormal_cdf(lognormal_ppf(q, 0.75_dp), 0.75_dp), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)
            write(label, '(a,i0)') 'lognormal sf isf round trip ', i
            call check_close(trim(label), lognormal_sf(lognormal_isf(q, 0.75_dp), 0.75_dp), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)

            write(label, '(a,i0)') 'weibull cdf ppf round trip ', i
            call check_close(trim(label), weibull_cdf(weibull_ppf(q, 1.5_dp), 1.5_dp), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)
            write(label, '(a,i0)') 'weibull sf isf round trip ', i
            call check_close(trim(label), weibull_sf(weibull_isf(q, 1.5_dp), 1.5_dp), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)

            write(label, '(a,i0)') 'pareto cdf ppf round trip ', i
            call check_close(trim(label), pareto_cdf(pareto_ppf(q, 2.5_dp), 2.5_dp), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)
            write(label, '(a,i0)') 'pareto sf isf round trip ', i
            call check_close(trim(label), pareto_sf(pareto_isf(q, 2.5_dp), 2.5_dp), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)

            write(label, '(a,i0)') 'rayleigh cdf ppf round trip ', i
            call check_close(trim(label), rayleigh_cdf(rayleigh_ppf(q)), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)
            write(label, '(a,i0)') 'rayleigh sf isf round trip ', i
            call check_close(trim(label), rayleigh_sf(rayleigh_isf(q)), &
                q, 1.0e-15_dp, 1.0e-14_dp, failures)
        end do
    end subroutine test_round_trips

    subroutine test_identities(failures)
        ! Checks analytical relationships between distributions.
        integer, intent(inout) :: failures !! running count of failed checks

        real(dp) :: x

        ! Weibull(c=1, loc, scale) == Exponential(loc, scale)
        x = 1.5_dp
        call check_close('weibull c=1 is expon pdf', &
            weibull_pdf(x, 1.0_dp, loc=0.5_dp, scale=2.0_dp), &
            exponential_pdf(x, loc=0.5_dp, scale=2.0_dp), &
            0.0_dp, 2.0_dp * eps, failures)
        call check_close('weibull c=1 is expon cdf', &
            weibull_cdf(x, 1.0_dp, loc=0.5_dp, scale=2.0_dp), &
            exponential_cdf(x, loc=0.5_dp, scale=2.0_dp), &
            0.0_dp, 2.0_dp * eps, failures)
        call check_close('weibull c=1 is expon sf', &
            weibull_sf(x, 1.0_dp, loc=0.5_dp, scale=2.0_dp), &
            exponential_sf(x, loc=0.5_dp, scale=2.0_dp), &
            0.0_dp, 2.0_dp * eps, failures)

        ! Weibull(c=2, loc, scale = sqrt(2)*sigma) == Rayleigh(loc, sigma)
        call check_close('weibull c=2 is rayleigh pdf', &
            weibull_pdf(x, 2.0_dp, loc=0.2_dp, scale=scifort_sqrt_two * 1.5_dp), &
            rayleigh_pdf(x, loc=0.2_dp, scale=1.5_dp), &
            0.0_dp, 2.0_dp * eps, failures)
        call check_close('weibull c=2 is rayleigh cdf', &
            weibull_cdf(x, 2.0_dp, loc=0.2_dp, scale=scifort_sqrt_two * 1.5_dp), &
            rayleigh_cdf(x, loc=0.2_dp, scale=1.5_dp), &
            0.0_dp, 2.0_dp * eps, failures)
        call check_close('weibull c=2 is rayleigh sf', &
            weibull_sf(x, 2.0_dp, loc=0.2_dp, scale=scifort_sqrt_two * 1.5_dp), &
            rayleigh_sf(x, loc=0.2_dp, scale=1.5_dp), &
            0.0_dp, 2.0_dp * eps, failures)

        ! Lognormal(s, loc=0, scale=1) at exp(z) CDF matches Normal(0, s) at z
        call check_close('lognormal normal cdf identity', &
            lognormal_cdf(exp(1.2_dp), 0.8_dp), &
            normal_cdf(1.2_dp, 0.0_dp, 0.8_dp), &
            0.0_dp, 2.0_dp * eps, failures)
        call check_close('lognormal normal sf identity', &
            lognormal_sf(exp(1.2_dp), 0.8_dp), &
            normal_sf(1.2_dp, 0.0_dp, 0.8_dp), &
            0.0_dp, 2.0_dp * eps, failures)
    end subroutine test_identities

    subroutine test_invalid_and_ieee(failures)
        ! Checks invalid parameters and IEEE values return quiet NaN.
        integer, intent(inout) :: failures !! running count of failed checks

        ! Invalid shape
        call check_true('lognormal invalid s <= 0', ieee_is_nan(lognormal_pdf(1.0_dp, 0.0_dp)), failures)
        call check_true('lognormal invalid s negative', ieee_is_nan(lognormal_pdf(1.0_dp, -1.0_dp)), failures)
        call check_true('weibull invalid c <= 0', ieee_is_nan(weibull_pdf(1.0_dp, 0.0_dp)), failures)
        call check_true('pareto invalid b <= 0', ieee_is_nan(pareto_pdf(2.0_dp, 0.0_dp)), failures)

        ! Invalid scale
        call check_true('lognormal invalid scale <= 0', ieee_is_nan(lognormal_pdf(1.0_dp, 1.0_dp, scale=0.0_dp)), failures)
        call check_true('weibull invalid scale <= 0', ieee_is_nan(weibull_pdf(1.0_dp, 1.0_dp, scale=-1.0_dp)), failures)
        call check_true('pareto invalid scale <= 0', ieee_is_nan(pareto_pdf(2.0_dp, 1.0_dp, scale=0.0_dp)), failures)
        call check_true('rayleigh invalid scale <= 0', ieee_is_nan(rayleigh_pdf(1.0_dp, scale=0.0_dp)), failures)

        ! Invalid probability
        call check_true('lognormal ppf < 0', ieee_is_nan(lognormal_ppf(-0.1_dp, 1.0_dp)), failures)
        call check_true('lognormal ppf > 1', ieee_is_nan(lognormal_ppf(1.1_dp, 1.0_dp)), failures)
        call check_true('weibull ppf < 0', ieee_is_nan(weibull_ppf(-0.1_dp, 1.0_dp)), failures)
        call check_true('weibull ppf > 1', ieee_is_nan(weibull_ppf(1.1_dp, 1.0_dp)), failures)
        call check_true('pareto ppf < 0', ieee_is_nan(pareto_ppf(-0.1_dp, 1.0_dp)), failures)
        call check_true('pareto ppf > 1', ieee_is_nan(pareto_ppf(1.1_dp, 1.0_dp)), failures)
        call check_true('rayleigh ppf < 0', ieee_is_nan(rayleigh_ppf(-0.1_dp)), failures)
        call check_true('rayleigh ppf > 1', ieee_is_nan(rayleigh_ppf(1.1_dp)), failures)

        ! NaN input
        call check_true('lognormal nan x', ieee_is_nan(lognormal_pdf(nan_value, 1.0_dp)), failures)
        call check_true('weibull nan x', ieee_is_nan(weibull_pdf(nan_value, 1.0_dp)), failures)
        call check_true('pareto nan x', ieee_is_nan(pareto_pdf(nan_value, 1.0_dp)), failures)
        call check_true('rayleigh nan x', ieee_is_nan(rayleigh_pdf(nan_value)), failures)
    end subroutine test_invalid_and_ieee

    subroutine test_elemental(failures)
        ! Checks that array and scalar evaluations agree.
        integer, intent(inout) :: failures !! running count of failed checks

        real(dp) :: x(3)
        real(dp) :: y(3)
        integer :: i

        x = [0.5_dp, 1.0_dp, 2.0_dp]

        ! Lognormal elemental
        y = lognormal_pdf(x, 1.0_dp)
        do i = 1, 3
            call check_close('lognormal elemental', y(i), lognormal_pdf(x(i), 1.0_dp), &
                0.0_dp, 0.0_dp, failures)
        end do

        ! Weibull elemental
        y = weibull_cdf(x, 1.5_dp)
        do i = 1, 3
            call check_close('weibull elemental', y(i), weibull_cdf(x(i), 1.5_dp), &
                0.0_dp, 0.0_dp, failures)
        end do

        ! Pareto elemental
        y = pareto_sf(x + 1.0_dp, 2.0_dp)
        do i = 1, 3
            call check_close('pareto elemental', y(i), pareto_sf(x(i) + 1.0_dp, 2.0_dp), &
                0.0_dp, 0.0_dp, failures)
        end do

        ! Rayleigh elemental
        y = rayleigh_cdf(x)
        do i = 1, 3
            call check_close('rayleigh elemental', y(i), rayleigh_cdf(x(i)), &
                0.0_dp, 0.0_dp, failures)
        end do
    end subroutine test_elemental

end program test_continuous
