! SPDX-License-Identifier: MIT
! Generated by tools/generate_matrix_distributions_reference.py
! SciPy version: 1.17.0
module test_matrix_distributions_reference
    use scifort_kinds, only : dp
    implicit none
    integer, parameter :: mhg_m_ref(3) = [5, 7, 8]
    integer, parameter :: mhg_x_ref(3) = [1, 2, 3]
    integer, parameter :: mhg_n_ref = 6
    real(dp), parameter :: mhg_logpmf_ref = -1.88583202511202863e+00_dp
    real(dp), parameter :: mhg_pmf_ref = 1.51702786377709176e-01_dp
    real(dp), parameter :: mhg_mean_ref(3) = [ &
        1.50000000000000000e+00_dp, &
        2.09999999999999964e+00_dp, &
        2.40000000000000036e+00_dp ]
    real(dp), parameter :: mhg_var_ref(3) = [ &
        8.28947368421052655e-01_dp, &
        1.00578947368421057e+00_dp, &
        1.06105263157894747e+00_dp ]
    real(dp), parameter :: mhg_cov_ref(3,3) = reshape([ &
        8.28947368421052655e-01_dp, &
        -3.86842105263157932e-01_dp, &
        -4.42105263157894779e-01_dp, &
        -3.86842105263157932e-01_dp, &
        1.00578947368421057e+00_dp, &
        -6.18947368421052690e-01_dp, &
        -4.42105263157894779e-01_dp, &
        -6.18947368421052690e-01_dp, &
        1.06105263157894747e+00_dp ], &
        [3,3])
    real(dp), parameter :: nig_mu_ref = 4.00000000000000022e-01_dp
    real(dp), parameter :: nig_lmbda_ref = 2.50000000000000000e+00_dp
    real(dp), parameter :: nig_a_ref = 3.50000000000000000e+00_dp
    real(dp), parameter :: nig_b_ref = 1.69999999999999996e+00_dp
    real(dp), parameter :: nig_x_ref = 2.00000000000000011e-01_dp
    real(dp), parameter :: nig_s2_ref = 1.30000000000000004e+00_dp
    real(dp), parameter :: nig_logpdf_ref = -2.46254305938837437e+00_dp
    real(dp), parameter :: nig_pdf_ref = 8.52179608395016164e-02_dp
    real(dp), parameter :: nig_mean_ref(2) = [ &
        4.00000000000000022e-01_dp, &
        6.79999999999999938e-01_dp ]
    real(dp), parameter :: nig_var_ref(2) = [ &
        2.72000000000000020e-01_dp, &
        3.08266666666666633e-01_dp ]
    real(dp), parameter :: matrix_mean_ref(2,2) = reshape([ &
        2.00000000000000011e-01_dp, &
        5.00000000000000000e-01_dp, &
        -1.00000000000000006e-01_dp, &
        1.19999999999999996e+00_dp ], &
        [2,2])
    real(dp), parameter :: matrix_row_ref(2,2) = reshape([ &
        1.50000000000000000e+00_dp, &
        2.99999999999999989e-01_dp, &
        2.99999999999999989e-01_dp, &
        8.00000000000000044e-01_dp ], &
        [2,2])
    real(dp), parameter :: matrix_col_ref(2,2) = reshape([ &
        6.99999999999999956e-01_dp, &
        -1.00000000000000006e-01_dp, &
        -1.00000000000000006e-01_dp, &
        1.10000000000000009e+00_dp ], &
        [2,2])
    real(dp), parameter :: matrix_x_ref(2,2) = reshape([ &
        1.00000000000000006e-01_dp, &
        1.00000000000000000e+00_dp, &
        4.00000000000000022e-01_dp, &
        8.00000000000000044e-01_dp ], &
        [2,2])
    real(dp), parameter :: matrix_normal_logpdf_ref = -3.95666118105663100e+00_dp
    real(dp), parameter :: matrix_normal_pdf_ref = 1.91268689521356811e-02_dp
    real(dp), parameter :: matrix_normal_entropy_ref = 5.50567730244117293e+00_dp
    real(dp), parameter :: wi_scale_ref(2,2) = reshape([ &
        1.19999999999999996e+00_dp, &
        2.00000000000000011e-01_dp, &
        2.00000000000000011e-01_dp, &
        9.00000000000000022e-01_dp ], &
        [2,2])
    real(dp), parameter :: wi_x_ref(2,2) = reshape([ &
        2.00000000000000000e+00_dp, &
        2.99999999999999989e-01_dp, &
        2.99999999999999989e-01_dp, &
        1.39999999999999991e+00_dp ], &
        [2,2])
    real(dp), parameter :: wi_df_ref = 5.50000000000000000e+00_dp
    real(dp), parameter :: wishart_logpdf_ref = -5.46181660075335973e+00_dp
    real(dp), parameter :: wishart_pdf_ref = 4.24583574644508879e-03_dp
    real(dp), parameter :: wishart_mean_ref(2,2) = reshape([ &
        6.59999999999999964e+00_dp, &
        1.10000000000000009e+00_dp, &
        1.10000000000000009e+00_dp, &
        4.95000000000000018e+00_dp ], &
        [2,2])
    real(dp), parameter :: wishart_mode_ref(2,2) = reshape([ &
        3.00000000000000000e+00_dp, &
        5.00000000000000000e-01_dp, &
        5.00000000000000000e-01_dp, &
        2.25000000000000000e+00_dp ], &
        [2,2])
    real(dp), parameter :: wishart_var_ref(2,2) = reshape([ &
        1.58399999999999999e+01_dp, &
        6.16000000000000014e+00_dp, &
        6.16000000000000014e+00_dp, &
        8.91000000000000014e+00_dp ], &
        [2,2])
    real(dp), parameter :: wishart_entropy_ref = 7.07141457164283249e+00_dp
    real(dp), parameter :: invwishart_logpdf_ref = -9.73386175419154220e+00_dp
    real(dp), parameter :: invwishart_pdf_ref = 5.92430695629875064e-05_dp
    real(dp), parameter :: invwishart_mean_ref(2,2) = reshape([ &
        4.79999999999999982e-01_dp, &
        8.00000000000000017e-02_dp, &
        8.00000000000000017e-02_dp, &
        3.59999999999999987e-01_dp ], &
        [2,2])
    real(dp), parameter :: invwishart_mode_ref(2,2) = reshape([ &
        1.41176470588235292e-01_dp, &
        2.35294117647058820e-02_dp, &
        2.35294117647058820e-02_dp, &
        1.05882352941176469e-01_dp ], &
        [2,2])
    real(dp), parameter :: invwishart_var_ref(2,2) = reshape([ &
        9.21599999999999864e-01_dp, &
        2.63314285714285723e-01_dp, &
        2.63314285714285723e-01_dp, &
        5.18400000000000083e-01_dp ], &
        [2,2])
    real(dp), parameter :: invwishart_entropy_ref = -2.22090215674421998e-01_dp
    real(dp), parameter :: matrix_t_df_ref = 3.50000000000000000e+00_dp
    real(dp), parameter :: matrix_t_logpdf_ref = -2.92634757531167988e+00_dp
    real(dp), parameter :: matrix_t_pdf_ref = 5.35924234033655286e-02_dp
    real(dp), parameter :: matrix_t_doc_mean_ref(3,2) = reshape([ &
        0.00000000000000000e+00_dp, &
        2.00000000000000000e+00_dp, &
        4.00000000000000000e+00_dp, &
        1.00000000000000000e+00_dp, &
        3.00000000000000000e+00_dp, &
        5.00000000000000000e+00_dp ], &
        [3,2])
    real(dp), parameter :: matrix_t_doc_row_ref(3,3) = reshape([ &
        1.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        2.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        3.00000000000000000e+00_dp ], &
        [3,3])
    real(dp), parameter :: matrix_t_doc_col_ref(2,2) = reshape([ &
        2.99999999999999989e-01_dp, &
        0.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        2.99999999999999989e-01_dp ], &
        [2,2])
    real(dp), parameter :: matrix_t_doc_x_ref(3,2) = reshape([ &
        1.00000000000000006e-01_dp, &
        2.10000000000000009e+00_dp, &
        4.09999999999999964e+00_dp, &
        1.10000000000000009e+00_dp, &
        3.10000000000000009e+00_dp, &
        5.09999999999999964e+00_dp ], &
        [3,2])
    real(dp), parameter :: matrix_t_doc_logpdf_ref = -2.71565604466317279e-03_dp
    real(dp), parameter :: matrix_t_doc_pdf_ref = 9.97288028013580408e-01_dp
end module test_matrix_distributions_reference
