! SPDX-License-Identifier: MIT
! Generated by tools/generate_directional_random_matrix_reference.py
! SciPy version: 1.17.0
module test_directional_random_matrix_reference
    use scifort_kinds, only : dp
    implicit none
    real(dp), parameter :: besseli_log_ref = -2.04604317885523868e+00_dp
    real(dp), parameter :: besseli_ratio_ref = 7.38092974491790232e-01_dp
    real(dp), parameter :: besseli_large_log_ref = -5.62305578454131449e+00_dp
    real(dp), parameter :: besseli_large_ratio_ref = 9.50750343507047235e-01_dp
    real(dp), parameter :: vmf_mu2_ref(2) = [ &
        9.21060994002885103e-01_dp, &
        3.89418342308650522e-01_dp ]
    real(dp), parameter :: vmf_x2_ref(2) = [ &
        7.64842187284488495e-01_dp, &
        -6.44217687237691017e-01_dp ]
    real(dp), parameter :: vmf_kappa2_ref = 2.25000000000000000e+00_dp
    real(dp), parameter :: vmf_logpdf2_ref = -1.82051661216114113e+00_dp
    real(dp), parameter :: vmf_pdf2_ref = 1.61942068078181928e-01_dp
    real(dp), parameter :: vmf_entropy2_ref = 1.18771686751548544e+00_dp
    real(dp), parameter :: vmf_mu3_ref(3) = [ &
        2.67261241912424397e-01_dp, &
        5.34522483824848793e-01_dp, &
        8.01783725737273190e-01_dp ]
    real(dp), parameter :: vmf_x3_ref(3) = [ &
        -6.66666666666666630e-01_dp, &
        3.33333333333333315e-01_dp, &
        6.66666666666666630e-01_dp ]
    real(dp), parameter :: vmf_kappa3_ref = 4.25000000000000000e+00_dp
    real(dp), parameter :: vmf_logpdf3_ref = -2.36903403814590297e+00_dp
    real(dp), parameter :: vmf_pdf3_ref = 9.35710687203881591e-02_dp
    real(dp), parameter :: vmf_entropy3_ref = 1.38902476129859975e+00_dp
    real(dp), parameter :: vmf_mu5_ref(5) = [ &
        2.56073759865791950e-01_dp, &
        5.12147519731583900e-01_dp, &
        -2.56073759865791950e-01_dp, &
        1.28036879932895975e-01_dp, &
        7.68221279597375850e-01_dp ]
    real(dp), parameter :: vmf_x5_ref(5) = [ &
        1.99007438041997831e-01_dp, &
        -3.98014876083995661e-01_dp, &
        7.96029752167991322e-01_dp, &
        3.98014876083995661e-01_dp, &
        9.95037190209989153e-02_dp ]
    real(dp), parameter :: vmf_kappa5_ref = 1.30000000000000000e+01_dp
    real(dp), parameter :: vmf_logpdf5_ref = -1.44470068099174327e+01_dp
    real(dp), parameter :: vmf_pdf5_ref = 5.31795505362421295e-07_dp
    real(dp), parameter :: vmf_entropy5_ref = 3.82479377050623626e-01_dp
    real(dp), parameter :: vmf_fit_data_ref(3,5) = reshape([ &
        1.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        0.00000000000000000e+00_dp, &
        8.00000000000000044e-01_dp, &
        5.99999999999999978e-01_dp, &
        0.00000000000000000e+00_dp, &
        8.00000000000000044e-01_dp, &
        0.00000000000000000e+00_dp, &
        5.99999999999999978e-01_dp, &
        5.99999999999999978e-01_dp, &
        8.00000000000000044e-01_dp, &
        0.00000000000000000e+00_dp, &
        5.99999999999999978e-01_dp, &
        0.00000000000000000e+00_dp, &
        8.00000000000000044e-01_dp ], &
        [3,5])
    real(dp), parameter :: vmf_fit_mu_ref(3) = [ &
        8.86844053217739514e-01_dp, &
        3.26732019606535584e-01_dp, &
        3.26732019606535584e-01_dp ]
    real(dp), parameter :: vmf_fit_kappa_ref = 6.99152654666879769e+00_dp
    integer, parameter :: random_table_row_ref(2) = [7, 6]
    integer, parameter :: random_table_col_ref(3) = [3, 8, 2]
    integer, parameter :: random_table_x_ref(2,3) = reshape([1, 2, 5, 3, 1, 1], [2,3])
    real(dp), parameter :: random_table_logpmf_ref = -1.63064012008470272e+00_dp
    real(dp), parameter :: random_table_pmf_ref = 1.95804195804195919e-01_dp
    real(dp), parameter :: random_table_mean_ref(2,3) = reshape([ &
        1.61538461538461542e+00_dp, &
        1.38461538461538458e+00_dp, &
        4.30769230769230749e+00_dp, &
        3.69230769230769251e+00_dp, &
        1.07692307692307687e+00_dp, &
        9.23076923076923128e-01_dp ], &
        [2,3])
end module test_directional_random_matrix_reference
