! SPDX-License-Identifier: MIT
! Copyright (c) 2026 SciFort contributors

! Tests for the incomplete gamma functions, the gamma and chi-square
! distributions, and the elementary helpers they depend on. Reference values
! are generated by tools/generate_gamma_reference.py.

program test_gamma
    use, intrinsic :: ieee_arithmetic, only : ieee_is_nan, &
        ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value
    use scifort_incomplete_gamma, only : log_gammainc, log_gammaincc
    use scifort_math, only : expm1_safe, log1p_safe
    use scifort_special, only : gammainc, gammaincc, gammainccinv, gammaincinv
    use scifort_stats
    use test_checks, only : check_close, check_true
    use test_gamma_reference
    implicit none

    real(dp), parameter :: eps = epsilon(1.0_dp)
    integer :: failures
    real(dp) :: nan_value
    real(dp) :: negative_inf
    real(dp) :: positive_inf

    nan_value = ieee_value(0.0_dp, ieee_quiet_nan)
    negative_inf = ieee_value(0.0_dp, ieee_negative_inf)
    positive_inf = ieee_value(0.0_dp, ieee_positive_inf)

    failures = 0
    call test_elementary(failures)
    call test_incomplete_gamma_reference(failures)
    call test_incomplete_gamma_special_values(failures)
    call test_incomplete_gamma_identities(failures)
    call test_inverse_reference(failures)
    call test_gamma_reference_values(failures)
    call test_chi2_reference_values(failures)
    call test_endpoints(failures)
    call test_invalid_and_ieee(failures)
    call test_monotonicity(failures)
    call test_round_trips(failures)
    call test_distribution_identities(failures)
    call test_elemental(failures)

    if (failures == 0) then
        print '(a)', 'test_gamma: PASS'
    else
        print '(a,1x,i0)', 'test_gamma: FAIL', failures
        error stop 1
    end if

contains

    ! Reference values from mpmath 1.3.0 at 40 digits.
    subroutine test_elementary(failures)
        integer, intent(inout) :: failures

        call check_close('log1p 1e-300', log1p_safe(1.0e-300_dp), 1.0e-300_dp, &
            0.0_dp, 2.0_dp * eps, failures)
        call check_close('log1p 1e-10', log1p_safe(1.0e-10_dp), &
            9.9999999995e-11_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('log1p 1e-4', log1p_safe(1.0e-4_dp), &
            0.000099995000333308335333_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('log1p -0.3', log1p_safe(-0.3_dp), &
            -0.35667494393873237891_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('log1p 0.75', log1p_safe(0.75_dp), &
            0.55961578793542268627_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('log1p -0.999', log1p_safe(-0.999_dp), &
            -6.9077552789821370521_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_true('log1p -1', log1p_safe(-1.0_dp) < -huge(1.0_dp), failures)
        call check_true('log1p below -1', ieee_is_nan(log1p_safe(-2.0_dp)), failures)
        call check_true('log1p NaN', ieee_is_nan(log1p_safe(nan_value)), failures)
        call check_true('log1p infinity', log1p_safe(positive_inf) > huge(1.0_dp), &
            failures)

        call check_close('expm1 1e-300', expm1_safe(1.0e-300_dp), 1.0e-300_dp, &
            0.0_dp, 2.0_dp * eps, failures)
        call check_close('expm1 1e-10', expm1_safe(1.0e-10_dp), &
            1.00000000005e-10_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('expm1 1e-5', expm1_safe(1.0e-5_dp), &
            0.000010000050000166667083_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('expm1 -0.4', expm1_safe(-0.4_dp), &
            -0.32967995396436069926_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('expm1 0.49', expm1_safe(0.49_dp), &
            0.63231621995537897012_dp, 0.0_dp, 2.0_dp * eps, failures)
        call check_close('expm1 3', expm1_safe(3.0_dp), &
            19.085536923187667741_dp, 0.0_dp, 4.0_dp * eps, failures)
        call check_close('expm1 -infinity', expm1_safe(negative_inf), -1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('expm1 NaN', ieee_is_nan(expm1_safe(nan_value)), failures)
    end subroutine test_elementary

    subroutine test_incomplete_gamma_reference(failures)
        integer, intent(inout) :: failures

        integer :: i
        character(len=64) :: label

        do i = 1, size(ig_a)
            write(label, '(a,i0)') 'gammainc reference ', i
            call check_close(trim(label), gammainc(ig_a(i), ig_x(i)), ig_p(i), &
                ig_tol_p(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'gammaincc reference ', i
            call check_close(trim(label), gammaincc(ig_a(i), ig_x(i)), ig_q(i), &
                ig_tol_q(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'log_gammainc reference ', i
            call check_close(trim(label), log_gammainc(ig_a(i), ig_x(i)), &
                ig_logp(i), ig_tol_logp(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'log_gammaincc reference ', i
            call check_close(trim(label), log_gammaincc(ig_a(i), ig_x(i)), &
                ig_logq(i), ig_tol_logq(i), 0.0_dp, failures)
        end do
    end subroutine test_incomplete_gamma_reference

    ! Conventions follow scipy.special.gammainc and gammaincc.
    subroutine test_incomplete_gamma_special_values(failures)
        integer, intent(inout) :: failures

        call check_close('gammainc(0, 1)', gammainc(0.0_dp, 1.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('gammaincc(0, 1)', gammaincc(0.0_dp, 1.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('gammainc(0, 0)', ieee_is_nan(gammainc(0.0_dp, 0.0_dp)), &
            failures)
        call check_close('gammainc(1, 0)', gammainc(1.0_dp, 0.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('gammaincc(1, 0)', gammaincc(1.0_dp, 0.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('gammainc(1, inf)', gammainc(1.0_dp, positive_inf), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('gammaincc(1, inf)', gammaincc(1.0_dp, positive_inf), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('gammainc(inf, 1)', gammainc(positive_inf, 1.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('gammaincc(inf, 1)', gammaincc(positive_inf, 1.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('gammainc(inf, inf)', &
            ieee_is_nan(gammainc(positive_inf, positive_inf)), failures)
        call check_true('gammainc(-1, 1)', ieee_is_nan(gammainc(-1.0_dp, 1.0_dp)), &
            failures)
        call check_true('gammaincc(1, -1)', ieee_is_nan(gammaincc(1.0_dp, -1.0_dp)), &
            failures)
        call check_true('gammainc NaN a', ieee_is_nan(gammainc(nan_value, 1.0_dp)), &
            failures)
        call check_true('gammaincc NaN x', ieee_is_nan(gammaincc(1.0_dp, nan_value)), &
            failures)
        call check_true('log_gammainc(1, 0)', &
            log_gammainc(1.0_dp, 0.0_dp) < -huge(1.0_dp), failures)
        call check_close('log_gammaincc(1, 0)', log_gammaincc(1.0_dp, 0.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)

        call check_close('gammaincinv(1, 0)', gammaincinv(1.0_dp, 0.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('gammaincinv(1, 1)', gammaincinv(1.0_dp, 1.0_dp) > huge(1.0_dp), &
            failures)
        call check_true('gammainccinv(1, 0)', &
            gammainccinv(1.0_dp, 0.0_dp) > huge(1.0_dp), failures)
        call check_close('gammainccinv(1, 1)', gammainccinv(1.0_dp, 1.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('gammaincinv(0, 0.5)', &
            ieee_is_nan(gammaincinv(0.0_dp, 0.5_dp)), failures)
        call check_true('gammaincinv(1, 1.5)', &
            ieee_is_nan(gammaincinv(1.0_dp, 1.5_dp)), failures)
        call check_true('gammainccinv(1, NaN)', &
            ieee_is_nan(gammainccinv(1.0_dp, nan_value)), failures)
        ! The root is about 1e-353000, which rounds to zero.
        call check_close('gammaincinv underflow', gammaincinv(1.0e-3_dp, 0.3_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
    end subroutine test_incomplete_gamma_special_values

    subroutine test_incomplete_gamma_identities(failures)
        integer, intent(inout) :: failures

        integer :: k
        integer :: n
        real(dp) :: poisson_sum
        real(dp) :: term
        real(dp) :: x

        ! Q(n + 1, x) is the Poisson probability of at most n events.
        x = 3.7_dp
        do n = 0, 12
            term = exp(-x)
            poisson_sum = term
            do k = 1, n
                term = term * x / real(k, dp)
                poisson_sum = poisson_sum + term
            end do
            call check_close('Poisson identity', gammaincc(real(n + 1, dp), x), &
                poisson_sum, 0.0_dp, 1.0e-14_dp, failures)
        end do

        ! P(1/2, x) = erf(sqrt(x)) and Q(1/2, x) = erfc(sqrt(x)).
        call check_close('P(1/2, 2) = erf', gammainc(0.5_dp, 2.0_dp), &
            erf(sqrt(2.0_dp)), 0.0_dp, 4.0_dp * eps, failures)
        call check_close('Q(1/2, 50) = erfc', gammaincc(0.5_dp, 50.0_dp), &
            erfc(sqrt(50.0_dp)), 0.0_dp, 1.0e-14_dp, failures)
    end subroutine test_incomplete_gamma_identities

    subroutine test_inverse_reference(failures)
        integer, intent(inout) :: failures

        integer :: i
        character(len=64) :: label

        do i = 1, size(inv_a)
            write(label, '(a,i0)') 'gammaincinv reference ', i
            call check_close(trim(label), gammaincinv(inv_a(i), inv_p(i)), inv_x(i), &
                0.0_dp, inv_tol(i), failures)
            write(label, '(a,i0)') 'gammainccinv reference ', i
            call check_close(trim(label), gammainccinv(inv_a(i), inv_p(i)), &
                cinv_x(i), 0.0_dp, cinv_tol(i), failures)
        end do
    end subroutine test_inverse_reference

    subroutine test_gamma_reference_values(failures)
        integer, intent(inout) :: failures

        integer :: i
        character(len=64) :: label

        do i = 1, size(gd_x)
            write(label, '(a,i0)') 'gamma logpdf reference ', i
            call check_close(trim(label), &
                gamma_logpdf(gd_x(i), gd_a(i), gd_loc(i), gd_scale(i)), &
                gd_logpdf(i), gd_tol_logpdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'gamma pdf reference ', i
            call check_close(trim(label), &
                gamma_pdf(gd_x(i), gd_a(i), gd_loc(i), gd_scale(i)), &
                exp(gd_logpdf(i)), 0.0_dp, gd_tol_logpdf(i) + 2.0_dp * eps, failures)
            write(label, '(a,i0)') 'gamma cdf reference ', i
            call check_close(trim(label), &
                gamma_cdf(gd_x(i), gd_a(i), gd_loc(i), gd_scale(i)), &
                gd_cdf(i), gd_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'gamma sf reference ', i
            call check_close(trim(label), &
                gamma_sf(gd_x(i), gd_a(i), gd_loc(i), gd_scale(i)), &
                gd_sf(i), gd_tol_sf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'gamma logcdf reference ', i
            call check_close(trim(label), &
                gamma_logcdf(gd_x(i), gd_a(i), gd_loc(i), gd_scale(i)), &
                log(gd_cdf(i)), gd_tol_cdf(i) / gd_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'gamma logsf reference ', i
            call check_close(trim(label), &
                gamma_logsf(gd_x(i), gd_a(i), gd_loc(i), gd_scale(i)), &
                log(gd_sf(i)), gd_tol_sf(i) / gd_sf(i), 0.0_dp, failures)
        end do
    end subroutine test_gamma_reference_values

    subroutine test_chi2_reference_values(failures)
        integer, intent(inout) :: failures

        integer :: i
        character(len=64) :: label

        do i = 1, size(c2_x)
            write(label, '(a,i0)') 'chi2 logpdf reference ', i
            call check_close(trim(label), chi2_logpdf(c2_x(i), c2_df(i)), &
                c2_logpdf(i), c2_tol_logpdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'chi2 cdf reference ', i
            call check_close(trim(label), chi2_cdf(c2_x(i), c2_df(i)), &
                c2_cdf(i), c2_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'chi2 sf reference ', i
            call check_close(trim(label), chi2_sf(c2_x(i), c2_df(i)), &
                c2_sf(i), c2_tol_sf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'chi2 logsf reference ', i
            call check_close(trim(label), chi2_logsf(c2_x(i), c2_df(i)), &
                log(c2_sf(i)), c2_tol_sf(i) / c2_sf(i), 0.0_dp, failures)
        end do
    end subroutine test_chi2_reference_values

    subroutine test_endpoints(failures)
        integer, intent(inout) :: failures

        call check_true('gamma pdf 0, a < 1', gamma_pdf(0.0_dp, 0.5_dp) > huge(1.0_dp), &
            failures)
        call check_close('gamma pdf 0, a = 1', gamma_pdf(3.0_dp, 1.0_dp, 3.0_dp, 2.0_dp), &
            0.5_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('gamma pdf 0, a > 1', gamma_pdf(0.0_dp, 2.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('gamma logpdf 0, a > 1', &
            gamma_logpdf(0.0_dp, 2.0_dp) < -huge(1.0_dp), failures)
        call check_close('gamma logpdf 0, a = 1', gamma_logpdf(0.0_dp, 1.0_dp, &
            scale=2.0_dp), -log(2.0_dp), 0.0_dp, eps, failures)
        call check_close('gamma pdf below support', gamma_pdf(-1.0_dp, 2.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('gamma cdf at loc', gamma_cdf(2.0_dp, 3.0_dp, 2.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('gamma sf at loc', gamma_sf(2.0_dp, 3.0_dp, 2.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('gamma logsf at loc', gamma_logsf(2.0_dp, 3.0_dp, 2.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_true('gamma logcdf at loc', &
            gamma_logcdf(2.0_dp, 3.0_dp, 2.0_dp) < -huge(1.0_dp), failures)
        call check_close('gamma cdf +inf', gamma_cdf(positive_inf, 3.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('gamma sf +inf', gamma_sf(positive_inf, 3.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('gamma logsf +inf', &
            gamma_logsf(positive_inf, 3.0_dp) < -huge(1.0_dp), failures)
        call check_close('gamma cdf -inf', gamma_cdf(negative_inf, 3.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('gamma pdf +inf', gamma_pdf(positive_inf, 3.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('gamma ppf 0', gamma_ppf(0.0_dp, 3.0_dp, 3.0_dp), 3.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('gamma ppf 1', gamma_ppf(1.0_dp, 3.0_dp) > huge(1.0_dp), &
            failures)
        call check_true('gamma isf 0', gamma_isf(0.0_dp, 3.0_dp) > huge(1.0_dp), &
            failures)
        call check_close('gamma isf 1', gamma_isf(1.0_dp, 3.0_dp, 3.0_dp), 3.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('chi2 pdf 0, df = 2', chi2_pdf(0.0_dp, 2.0_dp), 0.5_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('chi2 pdf 0, df = 1', chi2_pdf(0.0_dp, 1.0_dp) > huge(1.0_dp), &
            failures)
    end subroutine test_endpoints

    subroutine test_invalid_and_ieee(failures)
        integer, intent(inout) :: failures

        call check_true('gamma zero shape', ieee_is_nan(gamma_pdf(1.0_dp, 0.0_dp)), &
            failures)
        call check_true('gamma negative shape', &
            ieee_is_nan(gamma_cdf(1.0_dp, -1.0_dp)), failures)
        call check_true('gamma infinite shape', &
            ieee_is_nan(gamma_sf(1.0_dp, positive_inf)), failures)
        call check_true('gamma NaN shape', ieee_is_nan(gamma_logpdf(1.0_dp, nan_value)), &
            failures)
        call check_true('gamma zero scale', &
            ieee_is_nan(gamma_cdf(1.0_dp, 2.0_dp, scale=0.0_dp)), failures)
        call check_true('gamma infinite loc', &
            ieee_is_nan(gamma_cdf(1.0_dp, 2.0_dp, loc=positive_inf)), failures)
        call check_true('gamma ppf p > 1', ieee_is_nan(gamma_ppf(1.5_dp, 2.0_dp)), &
            failures)
        call check_true('gamma isf p < 0', ieee_is_nan(gamma_isf(-0.5_dp, 2.0_dp)), &
            failures)
        call check_true('chi2 zero df', ieee_is_nan(chi2_cdf(1.0_dp, 0.0_dp)), failures)
        call check_true('chi2 negative scale', &
            ieee_is_nan(chi2_pdf(1.0_dp, 3.0_dp, scale=-1.0_dp)), failures)

        call check_true('gamma pdf NaN x', ieee_is_nan(gamma_pdf(nan_value, 2.0_dp)), &
            failures)
        call check_true('gamma logpdf NaN x', &
            ieee_is_nan(gamma_logpdf(nan_value, 2.0_dp)), failures)
        call check_true('gamma cdf NaN x', ieee_is_nan(gamma_cdf(nan_value, 2.0_dp)), &
            failures)
        call check_true('gamma sf NaN x', ieee_is_nan(gamma_sf(nan_value, 2.0_dp)), &
            failures)
        call check_true('gamma logcdf NaN x', &
            ieee_is_nan(gamma_logcdf(nan_value, 2.0_dp)), failures)
        call check_true('gamma logsf NaN x', &
            ieee_is_nan(gamma_logsf(nan_value, 2.0_dp)), failures)
        call check_true('gamma ppf NaN p', ieee_is_nan(gamma_ppf(nan_value, 2.0_dp)), &
            failures)
        call check_true('chi2 isf NaN p', ieee_is_nan(chi2_isf(nan_value, 2.0_dp)), &
            failures)
    end subroutine test_invalid_and_ieee

    subroutine test_monotonicity(failures)
        integer, intent(inout) :: failures

        real(dp), parameter :: shapes(6) = [1.0e-3_dp, 0.3_dp, 1.0_dp, 2.5_dp, &
            40.0_dp, 5000.0_dp]
        integer :: i
        integer :: j
        logical :: ok
        real(dp) :: cdf_prev
        real(dp) :: cdf_now
        real(dp) :: pdf_now
        real(dp) :: sf_now
        real(dp) :: sf_prev
        real(dp) :: x

        ok = .true.
        do i = 1, size(shapes)
            cdf_prev = 0.0_dp
            sf_prev = 1.0_dp
            do j = -600, 800
                x = 10.0_dp ** (real(j, dp) / 100.0_dp)
                cdf_now = gamma_cdf(x, shapes(i))
                sf_now = gamma_sf(x, shapes(i))
                pdf_now = gamma_pdf(x, shapes(i))
                ok = ok .and. cdf_now >= cdf_prev .and. sf_now <= sf_prev
                ok = ok .and. cdf_now >= 0.0_dp .and. cdf_now <= 1.0_dp
                ok = ok .and. sf_now >= 0.0_dp .and. sf_now <= 1.0_dp
                ok = ok .and. pdf_now >= 0.0_dp
                cdf_prev = cdf_now
                sf_prev = sf_now
            end do
        end do
        call check_true('gamma monotone and bounded', ok, failures)
    end subroutine test_monotonicity

    ! Round-trip tolerance: a quantile x carries a relative rounding error of
    ! order eps, which moves a tail probability V by eps * x f(x) / V; the
    ! forward function adds eps * (1 + |log V|).
    subroutine test_round_trips(failures)
        integer, intent(inout) :: failures

        real(dp), parameter :: shapes(7) = [1.0e-3_dp, 0.3_dp, 1.0_dp, 2.5_dp, &
            30.0_dp, 1000.0_dp, 1.0e5_dp]
        real(dp), parameter :: probabilities(7) = [1.0e-300_dp, 1.0e-12_dp, &
            0.01_dp, 0.3_dp, 0.5_dp, 0.9_dp, 1.0_dp - 1.0e-10_dp]
        integer :: i
        integer :: j
        real(dp) :: a
        real(dp) :: p
        real(dp) :: rtol
        real(dp) :: x

        do i = 1, size(shapes)
            a = shapes(i)
            do j = 1, size(probabilities)
                p = probabilities(j)

                x = gamma_ppf(p, a)
                if (x == 0.0_dp) then
                    call check_true('gamma ppf underflow is justified', &
                        gamma_cdf(tiny(1.0_dp), a) >= p, failures)
                else
                    rtol = 20.0_dp * eps * (1.0_dp + abs(log(p)) + &
                        x * gamma_pdf(x, a) / p)
                    call check_close('gamma cdf(ppf(p))', gamma_cdf(x, a), p, &
                        0.0_dp, rtol, failures)
                end if

                x = gamma_isf(p, a)
                if (x == 0.0_dp) then
                    call check_true('gamma isf underflow is justified', &
                        gamma_sf(tiny(1.0_dp), a) <= p, failures)
                else
                    rtol = 20.0_dp * eps * (1.0_dp + abs(log(p)) + &
                        x * gamma_pdf(x, a) / p)
                    call check_close('gamma sf(isf(p))', gamma_sf(x, a), p, &
                        0.0_dp, rtol, failures)
                end if
            end do
        end do

        ! Reference from mpmath 1.3.0 at 40 digits.
        x = chi2_ppf(0.95_dp, 1.0_dp)
        call check_close('chi2 ppf 0.95 df 1', x, 3.8414588206941259584_dp, 0.0_dp, &
            1.0e-14_dp, failures)
    end subroutine test_round_trips

    subroutine test_distribution_identities(failures)
        integer, intent(inout) :: failures

        integer :: i
        real(dp) :: x(6)

        x = [1.0e-8_dp, 0.3_dp, 1.0_dp, 4.0_dp, 30.0_dp, 600.0_dp]
        do i = 1, size(x)
            call check_close('gamma(1) cdf = exponential', &
                gamma_cdf(x(i), 1.0_dp, 0.5_dp, 2.0_dp), &
                exponential_cdf(x(i), 0.5_dp, 2.0_dp), 0.0_dp, 4.0_dp * eps, failures)
            call check_close('gamma(1) sf = exponential', &
                gamma_sf(x(i), 1.0_dp), exponential_sf(x(i)), 0.0_dp, &
                1.0e-14_dp, failures)
            call check_close('gamma(1) logsf = exponential', &
                gamma_logsf(x(i), 1.0_dp), exponential_logsf(x(i)), 0.0_dp, &
                4.0_dp * eps, failures)
            call check_close('gamma(1) logpdf = exponential', &
                gamma_logpdf(x(i), 1.0_dp), exponential_logpdf(x(i)), 0.0_dp, &
                4.0_dp * eps, failures)
            call check_close('chi2(2) cdf = exponential(scale 2)', &
                chi2_cdf(x(i), 2.0_dp), exponential_cdf(x(i), scale=2.0_dp), &
                0.0_dp, 4.0_dp * eps, failures)
            call check_close('chi2 = gamma(df/2, scale 2)', &
                chi2_sf(x(i), 7.0_dp, 1.0_dp, 3.0_dp), &
                gamma_sf(x(i), 3.5_dp, 1.0_dp, 6.0_dp), 0.0_dp, 0.0_dp, failures)
            call check_close('gamma cdf + sf', gamma_cdf(x(i), 3.3_dp) + &
                gamma_sf(x(i), 3.3_dp), 1.0_dp, 2.0_dp * eps, 0.0_dp, failures)
            call check_close('chi2(1) cdf = erf', chi2_cdf(x(i), 1.0_dp), &
                erf(sqrt(0.5_dp * x(i))), 0.0_dp, 8.0_dp * eps, failures)
        end do
    end subroutine test_distribution_identities

    subroutine test_elemental(failures)
        integer, intent(inout) :: failures

        integer :: i
        real(dp) :: actual(4)
        real(dp) :: p(4)
        real(dp) :: x(4)

        x = [0.1_dp, 1.0_dp, 5.0_dp, 20.0_dp]
        actual = gamma_cdf(x, 2.5_dp, scale=1.5_dp)
        do i = 1, size(x)
            call check_close('gamma cdf elemental', actual(i), &
                gamma_cdf(x(i), 2.5_dp, scale=1.5_dp), 0.0_dp, 0.0_dp, failures)
        end do

        p = [0.01_dp, 0.25_dp, 0.5_dp, 0.99_dp]
        actual = chi2_ppf(p, [1.0_dp, 2.0_dp, 5.0_dp, 50.0_dp])
        call check_close('chi2 ppf elemental 1', actual(1), chi2_ppf(p(1), 1.0_dp), &
            0.0_dp, 0.0_dp, failures)
        call check_close('chi2 ppf elemental 4', actual(4), chi2_ppf(p(4), 50.0_dp), &
            0.0_dp, 0.0_dp, failures)

        actual = gammainc([0.5_dp, 1.0_dp, 2.0_dp, 4.0_dp], 2.0_dp)
        call check_close('gammainc elemental', actual(3), gammainc(2.0_dp, 2.0_dp), &
            0.0_dp, 0.0_dp, failures)
    end subroutine test_elemental

end program test_gamma
