! SPDX-License-Identifier: MIT
! Copyright (c) 2026 SciFort contributors

! Tests for the Poisson and binomial distributions. Reference values are
! generated by tools/generate_discrete_reference.py.

program test_discrete
    use, intrinsic :: ieee_arithmetic, only : ieee_is_finite, ieee_is_nan, &
        ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value
    use scifort_special, only : betainc, gammainc, gammaincc
    use scifort_stats
    use test_checks, only : check_close, check_true
    use test_discrete_reference
    implicit none

    real(dp), parameter :: eps = epsilon(1.0_dp)
    integer :: failures
    real(dp) :: nan_value
    real(dp) :: negative_inf
    real(dp) :: positive_inf

    nan_value = ieee_value(0.0_dp, ieee_quiet_nan)
    negative_inf = ieee_value(0.0_dp, ieee_negative_inf)
    positive_inf = ieee_value(0.0_dp, ieee_positive_inf)

    failures = 0
    call test_poisson_reference(failures)
    call test_binomial_reference(failures)
    call test_quantile_reference(failures)
    call test_quantile_properties(failures)
    call test_mass_sums(failures)
    call test_identities(failures)
    call test_endpoints(failures)
    call test_invalid_and_ieee(failures)
    call test_integer_interface(failures)
    call test_monotonicity(failures)
    call test_elemental(failures)

    if (failures == 0) then
        print '(a)', 'test_discrete: PASS'
    else
        print '(a,1x,i0)', 'test_discrete: FAIL', failures
        error stop 1
    end if

contains

    subroutine test_poisson_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(po_k)
            write(label, '(a,i0)') 'poisson pmf reference ', i
            call check_close(trim(label), poisson_pmf(po_k(i), po_mu(i)), po_pmf(i), &
                po_tol_pmf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'poisson cdf reference ', i
            call check_close(trim(label), poisson_cdf(po_k(i), po_mu(i)), po_cdf(i), &
                po_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'poisson sf reference ', i
            call check_close(trim(label), poisson_sf(po_k(i), po_mu(i)), po_sf(i), &
                po_tol_sf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'poisson logpmf reference ', i
            call check_close(trim(label), poisson_logpmf(po_k(i), po_mu(i)), &
                log(po_pmf(i)), po_tol_pmf(i) / po_pmf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'poisson logcdf reference ', i
            call check_close(trim(label), poisson_logcdf(po_k(i), po_mu(i)), &
                log(po_cdf(i)), po_tol_cdf(i) / po_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'poisson logsf reference ', i
            call check_close(trim(label), poisson_logsf(po_k(i), po_mu(i)), &
                log(po_sf(i)), po_tol_sf(i) / po_sf(i), 0.0_dp, failures)
        end do
    end subroutine test_poisson_reference

    subroutine test_binomial_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(bi_k)
            write(label, '(a,i0)') 'binomial pmf reference ', i
            call check_close(trim(label), binomial_pmf(bi_k(i), bi_n(i), bi_p(i)), &
                bi_pmf(i), bi_tol_pmf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'binomial cdf reference ', i
            call check_close(trim(label), binomial_cdf(bi_k(i), bi_n(i), bi_p(i)), &
                bi_cdf(i), bi_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'binomial sf reference ', i
            call check_close(trim(label), binomial_sf(bi_k(i), bi_n(i), bi_p(i)), &
                bi_sf(i), bi_tol_sf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'binomial logpmf reference ', i
            call check_close(trim(label), binomial_logpmf(bi_k(i), bi_n(i), bi_p(i)), &
                log(bi_pmf(i)), bi_tol_pmf(i) / bi_pmf(i), 0.0_dp, failures)
            if (bi_sf(i) > 0.0_dp) then
                write(label, '(a,i0)') 'binomial logsf reference ', i
                call check_close(trim(label), binomial_logsf(bi_k(i), bi_n(i), bi_p(i)), &
                    log(bi_sf(i)), bi_tol_sf(i) / bi_sf(i), 0.0_dp, failures)
            end if
        end do
    end subroutine test_binomial_reference

    subroutine test_quantile_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=64) :: label

        do i = 1, size(poq_p)
            write(label, '(a,i0)') 'poisson ppf reference ', i
            call check_close(trim(label), poisson_ppf(poq_p(i), poq_mu(i)), poq_ppf(i), &
                0.0_dp, 0.0_dp, failures)
            write(label, '(a,i0)') 'poisson isf reference ', i
            call check_close(trim(label), poisson_isf(poq_p(i), poq_mu(i)), poq_isf(i), &
                0.0_dp, 0.0_dp, failures)
        end do

        do i = 1, size(biq_p)
            write(label, '(a,i0)') 'binomial ppf reference ', i
            call check_close(trim(label), binomial_ppf(biq_p(i), biq_n(i), biq_prob(i)), &
                biq_ppf(i), 0.0_dp, 0.0_dp, failures)
            write(label, '(a,i0)') 'binomial isf reference ', i
            call check_close(trim(label), binomial_isf(biq_p(i), biq_n(i), biq_prob(i)), &
                biq_isf(i), 0.0_dp, 0.0_dp, failures)
        end do
    end subroutine test_quantile_reference

    ! The quantile is the smallest count whose tail reaches the probability,
    ! so the count below it must not reach it.
    subroutine test_quantile_properties(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        real(dp), parameter :: means(4) = [0.5_dp, 5.0_dp, 100.0_dp, 1.0e5_dp]
        real(dp), parameter :: probabilities(7) = [1.0e-12_dp, 0.001_dp, 0.1_dp, 0.5_dp, &
            0.9_dp, 0.999_dp, 1.0_dp - 1.0e-12_dp]
        real(dp), parameter :: trials(3) = [1.0_dp, 25.0_dp, 10000.0_dp]
        integer :: i
        integer :: j
        logical :: ok
        real(dp) :: k

        ok = .true.
        do i = 1, size(means)
            do j = 1, size(probabilities)
                k = poisson_ppf(probabilities(j), means(i))
                ok = ok .and. poisson_cdf(k, means(i)) >= probabilities(j)
                ok = ok .and. (k == 0.0_dp .or. &
                    poisson_cdf(k - 1.0_dp, means(i)) < probabilities(j))
                k = poisson_isf(probabilities(j), means(i))
                ok = ok .and. poisson_sf(k, means(i)) <= probabilities(j)
                ok = ok .and. (k == -1.0_dp .or. &
                    poisson_sf(k - 1.0_dp, means(i)) > probabilities(j))
            end do
        end do
        call check_true('poisson quantile is the smallest count', ok, failures)

        ok = .true.
        do i = 1, size(trials)
            do j = 1, size(probabilities)
                k = binomial_ppf(probabilities(j), trials(i), 0.3_dp)
                ok = ok .and. binomial_cdf(k, trials(i), 0.3_dp) >= probabilities(j)
                ok = ok .and. (k == 0.0_dp .or. &
                    binomial_cdf(k - 1.0_dp, trials(i), 0.3_dp) < probabilities(j))
                k = binomial_isf(probabilities(j), trials(i), 0.3_dp)
                ok = ok .and. binomial_sf(k, trials(i), 0.3_dp) <= probabilities(j)
                ok = ok .and. (k == -1.0_dp .or. &
                    binomial_sf(k - 1.0_dp, trials(i), 0.3_dp) > probabilities(j))
            end do
        end do
        call check_true('binomial quantile is the smallest count', ok, failures)
    end subroutine test_quantile_properties

    ! The mass function must sum to the cumulative function and to one.
    subroutine test_mass_sums(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: k
        real(dp) :: total

        total = 0.0_dp
        do k = 0, 300
            total = total + poisson_pmf(k, 10.0_dp)
        end do
        call check_close('poisson mass sums to one', total, 1.0_dp, 0.0_dp, 1.0e-14_dp, &
            failures)

        total = 0.0_dp
        do k = 0, 12
            total = total + poisson_pmf(k, 4.0_dp)
        end do
        call check_close('poisson cdf equals the partial sum', total, &
            poisson_cdf(12, 4.0_dp), 0.0_dp, 1.0e-14_dp, failures)

        total = 0.0_dp
        do k = 0, 40
            total = total + binomial_pmf(real(k, dp), 40.0_dp, 0.3_dp)
        end do
        call check_close('binomial mass sums to one', total, 1.0_dp, 0.0_dp, 1.0e-14_dp, &
            failures)

        total = 0.0_dp
        do k = 0, 7
            total = total + binomial_pmf(real(k, dp), 40.0_dp, 0.3_dp)
        end do
        call check_close('binomial cdf equals the partial sum', total, &
            binomial_cdf(7.0_dp, 40.0_dp, 0.3_dp), 0.0_dp, 1.0e-14_dp, failures)
    end subroutine test_mass_sums

    subroutine test_identities(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        real(dp) :: k(5)

        k = [0.0_dp, 1.0_dp, 4.0_dp, 9.0_dp, 30.0_dp]
        do i = 1, size(k)
            ! P(X <= k) = Q(k + 1, mu) and P(X > k) = P(k + 1, mu), DLMF 8.4.8.
            call check_close('poisson cdf is the upper gamma', poisson_cdf(k(i), 7.0_dp), &
                gammaincc(k(i) + 1.0_dp, 7.0_dp), 0.0_dp, 0.0_dp, failures)
            call check_close('poisson sf is the lower gamma', poisson_sf(k(i), 7.0_dp), &
                gammainc(k(i) + 1.0_dp, 7.0_dp), 0.0_dp, 0.0_dp, failures)
            call check_close('poisson cdf plus sf', poisson_cdf(k(i), 7.0_dp) + &
                poisson_sf(k(i), 7.0_dp), 1.0_dp, 2.0_dp * eps, 0.0_dp, failures)
            ! P(X > k) = I_p(k + 1, n - k), DLMF 8.17.5.
            call check_close('binomial sf is the incomplete beta', &
                binomial_sf(k(i), 40.0_dp, 0.3_dp), &
                betainc(k(i) + 1.0_dp, 40.0_dp - k(i), 0.3_dp), 0.0_dp, 0.0_dp, failures)
            call check_close('binomial cdf plus sf', binomial_cdf(k(i), 40.0_dp, 0.3_dp) + &
                binomial_sf(k(i), 40.0_dp, 0.3_dp), 1.0_dp, 2.0_dp * eps, 0.0_dp, failures)
            ! Reflection: P(X <= k | p) = P(Y > n - k - 1 | 1 - p). The value
            ! 0.25 is used because it and its complement are both exact in
            ! binary64, so both sides see the same parameter.
            call check_close('binomial reflection', binomial_cdf(k(i), 40.0_dp, 0.25_dp), &
                binomial_sf(39.0_dp - k(i), 40.0_dp, 0.75_dp), 0.0_dp, 4.0_dp * eps, &
                failures)
        end do

        ! One trial is the Bernoulli distribution.
        call check_close('bernoulli pmf at zero', binomial_pmf(0.0_dp, 1.0_dp, 0.3_dp), &
            0.7_dp, 2.0_dp * eps, 0.0_dp, failures)
        call check_close('bernoulli pmf at one', binomial_pmf(1.0_dp, 1.0_dp, 0.3_dp), &
            0.3_dp, 2.0_dp * eps, 0.0_dp, failures)

        ! Shifting the support shifts the argument.
        call check_close('poisson loc shift', poisson_pmf(5.0_dp, 2.5_dp, 2.0_dp), &
            poisson_pmf(3.0_dp, 2.5_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('binomial loc shift', binomial_cdf(7.0_dp, 10.0_dp, 0.4_dp, 3.0_dp), &
            binomial_cdf(4.0_dp, 10.0_dp, 0.4_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('poisson ppf loc shift', poisson_ppf(0.7_dp, 2.5_dp, 4.0_dp), &
            poisson_ppf(0.7_dp, 2.5_dp) + 4.0_dp, 0.0_dp, 0.0_dp, failures)
    end subroutine test_identities

    subroutine test_endpoints(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        ! A non-integer or negative count has probability zero.
        call check_close('poisson pmf non-integer', poisson_pmf(2.5_dp, 3.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('poisson pmf negative', poisson_pmf(-1.0_dp, 3.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('poisson logpmf non-integer', &
            poisson_logpmf(2.5_dp, 3.0_dp) < -huge(1.0_dp), failures)
        call check_close('binomial pmf above n', binomial_pmf(11.0_dp, 10.0_dp, 0.3_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        ! The cumulative function uses the floor of the argument.
        call check_close('poisson cdf floors', poisson_cdf(2.5_dp, 3.0_dp), &
            poisson_cdf(2.0_dp, 3.0_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('binomial cdf floors', binomial_cdf(2.9_dp, 10.0_dp, 0.3_dp), &
            binomial_cdf(2.0_dp, 10.0_dp, 0.3_dp), 0.0_dp, 0.0_dp, failures)

        ! Degenerate parameters.
        call check_close('poisson mean zero at zero', poisson_pmf(0.0_dp, 0.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('poisson mean zero above', poisson_pmf(1.0_dp, 0.0_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('poisson mean zero cdf', poisson_cdf(0.0_dp, 0.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('binomial p zero', binomial_pmf(0.0_dp, 5.0_dp, 0.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('binomial p zero above', binomial_pmf(2.0_dp, 5.0_dp, 0.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('binomial p one', binomial_pmf(5.0_dp, 5.0_dp, 1.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('binomial zero trials', binomial_pmf(0.0_dp, 0.0_dp, 0.3_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)

        ! Infinite arguments and an infinite mean.
        call check_close('poisson cdf at infinity', poisson_cdf(positive_inf, 3.0_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('poisson pmf at infinity', poisson_pmf(positive_inf, 3.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('poisson cdf at minus infinity', poisson_cdf(negative_inf, 3.0_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('poisson infinite mean', poisson_cdf(5.0_dp, positive_inf), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)

        ! Probability endpoints, following scipy.stats.
        call check_close('poisson ppf 0', poisson_ppf(0.0_dp, 3.0_dp), -1.0_dp, 0.0_dp, &
            0.0_dp, failures)
        call check_true('poisson ppf 1', poisson_ppf(1.0_dp, 3.0_dp) > huge(1.0_dp), &
            failures)
        call check_close('poisson isf 1', poisson_isf(1.0_dp, 3.0_dp), -1.0_dp, 0.0_dp, &
            0.0_dp, failures)
        call check_true('poisson isf 0', poisson_isf(0.0_dp, 3.0_dp) > huge(1.0_dp), &
            failures)
        call check_close('poisson ppf 0 with loc', poisson_ppf(0.0_dp, 3.0_dp, 5.0_dp), &
            4.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('binomial ppf 0', binomial_ppf(0.0_dp, 10.0_dp, 0.3_dp), -1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('binomial ppf 1', binomial_ppf(1.0_dp, 10.0_dp, 0.3_dp), 10.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('binomial isf 0', binomial_isf(0.0_dp, 10.0_dp, 0.3_dp), 10.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('binomial isf 1', binomial_isf(1.0_dp, 10.0_dp, 0.3_dp), -1.0_dp, &
            0.0_dp, 0.0_dp, failures)
    end subroutine test_endpoints

    subroutine test_invalid_and_ieee(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_true('poisson negative mean', ieee_is_nan(poisson_pmf(1.0_dp, -1.0_dp)), &
            failures)
        call check_true('poisson NaN mean', ieee_is_nan(poisson_cdf(1.0_dp, nan_value)), &
            failures)
        call check_true('poisson NaN count', ieee_is_nan(poisson_sf(nan_value, 3.0_dp)), &
            failures)
        call check_true('poisson ppf p > 1', ieee_is_nan(poisson_ppf(1.5_dp, 3.0_dp)), &
            failures)
        call check_true('poisson logcdf NaN count', &
            ieee_is_nan(poisson_logcdf(nan_value, 3.0_dp)), failures)
        call check_true('binomial non-integer trials', &
            ieee_is_nan(binomial_pmf(1.0_dp, 5.5_dp, 0.3_dp)), failures)
        call check_true('binomial negative trials', &
            ieee_is_nan(binomial_pmf(1.0_dp, -5.0_dp, 0.3_dp)), failures)
        call check_true('binomial infinite trials', &
            ieee_is_nan(binomial_cdf(1.0_dp, positive_inf, 0.3_dp)), failures)
        call check_true('binomial p above one', &
            ieee_is_nan(binomial_pmf(1.0_dp, 5.0_dp, 1.5_dp)), failures)
        call check_true('binomial NaN p', ieee_is_nan(binomial_sf(1.0_dp, 5.0_dp, nan_value)), &
            failures)
        call check_true('binomial NaN count', &
            ieee_is_nan(binomial_cdf(nan_value, 5.0_dp, 0.3_dp)), failures)
        call check_true('binomial isf p < 0', &
            ieee_is_nan(binomial_isf(-0.5_dp, 5.0_dp, 0.3_dp)), failures)
    end subroutine test_invalid_and_ieee

    ! The integer and real interfaces must agree.
    subroutine test_integer_interface(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_close('poisson pmf integer argument', poisson_pmf(3, 2.5_dp), &
            poisson_pmf(3.0_dp, 2.5_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('poisson cdf integer argument', poisson_cdf(3, 2.5_dp), &
            poisson_cdf(3.0_dp, 2.5_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('poisson logsf integer argument', poisson_logsf(3, 2.5_dp), &
            poisson_logsf(3.0_dp, 2.5_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('binomial pmf integer argument', binomial_pmf(3, 10, 0.25_dp), &
            binomial_pmf(3.0_dp, 10.0_dp, 0.25_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('binomial sf integer argument', binomial_sf(3, 10, 0.25_dp), &
            binomial_sf(3.0_dp, 10.0_dp, 0.25_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('binomial logcdf integer argument', binomial_logcdf(3, 10, 0.25_dp), &
            binomial_logcdf(3.0_dp, 10.0_dp, 0.25_dp), 0.0_dp, 0.0_dp, failures)
    end subroutine test_integer_interface

    subroutine test_monotonicity(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: k
        logical :: ok
        real(dp) :: previous
        real(dp) :: value

        ok = .true.
        previous = 0.0_dp
        do k = 0, 500
            value = poisson_cdf(k, 50.0_dp)
            ok = ok .and. value >= previous .and. value <= 1.0_dp
            ok = ok .and. poisson_pmf(k, 50.0_dp) >= 0.0_dp
            previous = value
        end do
        call check_true('poisson cdf monotone', ok, failures)

        ok = .true.
        previous = 0.0_dp
        do k = 0, 200
            value = binomial_cdf(real(k, dp), 200.0_dp, 0.25_dp)
            ok = ok .and. value >= previous .and. value <= 1.0_dp
            ok = ok .and. binomial_pmf(real(k, dp), 200.0_dp, 0.25_dp) >= 0.0_dp
            previous = value
        end do
        call check_true('binomial cdf monotone', ok, failures)
    end subroutine test_monotonicity

    subroutine test_elemental(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        real(dp) :: actual(4)
        real(dp) :: k(4)

        k = [0.0_dp, 2.0_dp, 5.0_dp, 11.0_dp]
        actual = poisson_pmf(k, 4.0_dp)
        do i = 1, size(k)
            call check_close('poisson pmf elemental', actual(i), poisson_pmf(k(i), 4.0_dp), &
                0.0_dp, 0.0_dp, failures)
        end do

        actual = binomial_cdf(k, 12.0_dp, [0.1_dp, 0.3_dp, 0.5_dp, 0.9_dp])
        call check_close('binomial cdf elemental', actual(3), &
            binomial_cdf(k(3), 12.0_dp, 0.5_dp), 0.0_dp, 0.0_dp, failures)

        actual = poisson_ppf([0.1_dp, 0.5_dp, 0.9_dp, 0.99_dp], 6.0_dp)
        call check_close('poisson ppf elemental', actual(2), poisson_ppf(0.5_dp, 6.0_dp), &
            0.0_dp, 0.0_dp, failures)
    end subroutine test_elemental

end program test_discrete
