! SPDX-License-Identifier: MIT
! Copyright (c) 2026 SciFort contributors

! Tests for Bernoulli, geometric, and negative-binomial distributions.
! High-precision references are generated by
! tools/generate_discrete_extended_reference.py.

program test_discrete_extended
    use, intrinsic :: ieee_arithmetic, only : ieee_is_nan, ieee_negative_inf, &
        ieee_positive_inf, ieee_quiet_nan, ieee_value
    use scifort_stats
    use test_checks, only : check_close, check_true
    use test_discrete_extended_reference
    implicit none

    real(dp), parameter :: eps = epsilon(1.0_dp)
    integer :: failures
    real(dp) :: nan_value
    real(dp) :: negative_inf
    real(dp) :: positive_inf

    nan_value = ieee_value(0.0_dp, ieee_quiet_nan)
    negative_inf = ieee_value(0.0_dp, ieee_negative_inf)
    positive_inf = ieee_value(0.0_dp, ieee_positive_inf)

    failures = 0
    call test_geometric_reference(failures)
    call test_negative_binomial_reference(failures)
    call test_quantile_reference(failures)
    call test_identities(failures)
    call test_quantile_properties(failures)
    call test_mass_sums(failures)
    call test_endpoints(failures)
    call test_invalid_and_ieee(failures)
    call test_integer_interface(failures)
    call test_elemental(failures)

    if (failures == 0) then
        print '(a)', 'test_discrete_extended: PASS'
    else
        print '(a,1x,i0)', 'test_discrete_extended: FAIL', failures
        error stop 1
    end if

contains

    subroutine test_geometric_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=80) :: label

        do i = 1, size(ge_k)
            write(label, '(a,i0)') 'geometric pmf reference ', i
            call check_close(trim(label), geometric_pmf(ge_k(i), ge_p(i)), ge_pmf(i), &
                ge_tol_pmf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'geometric cdf reference ', i
            call check_close(trim(label), geometric_cdf(ge_k(i), ge_p(i)), ge_cdf(i), &
                ge_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'geometric sf reference ', i
            call check_close(trim(label), geometric_sf(ge_k(i), ge_p(i)), ge_sf(i), &
                ge_tol_sf(i), 0.0_dp, failures)
            if (ge_pmf(i) > 0.0_dp) then
                write(label, '(a,i0)') 'geometric logpmf reference ', i
                call check_close(trim(label), geometric_logpmf(ge_k(i), ge_p(i)), &
                    log(ge_pmf(i)), ge_tol_pmf(i) / ge_pmf(i), 0.0_dp, failures)
            end if
            if (ge_cdf(i) > 0.0_dp) then
                write(label, '(a,i0)') 'geometric logcdf reference ', i
                call check_close(trim(label), geometric_logcdf(ge_k(i), ge_p(i)), &
                    log(ge_cdf(i)), ge_tol_cdf(i) / ge_cdf(i), 0.0_dp, failures)
            end if
            if (ge_sf(i) > 0.0_dp) then
                write(label, '(a,i0)') 'geometric logsf reference ', i
                call check_close(trim(label), geometric_logsf(ge_k(i), ge_p(i)), &
                    log(ge_sf(i)), ge_tol_sf(i) / ge_sf(i), 0.0_dp, failures)
            end if
        end do
    end subroutine test_geometric_reference

    subroutine test_negative_binomial_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=80) :: label

        do i = 1, size(nb_k)
            write(label, '(a,i0)') 'negative binomial pmf reference ', i
            call check_close(trim(label), negative_binomial_pmf(nb_k(i), nb_n(i), nb_p(i)), &
                nb_pmf(i), nb_tol_pmf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'negative binomial cdf reference ', i
            call check_close(trim(label), negative_binomial_cdf(nb_k(i), nb_n(i), nb_p(i)), &
                nb_cdf(i), nb_tol_cdf(i), 0.0_dp, failures)
            write(label, '(a,i0)') 'negative binomial sf reference ', i
            call check_close(trim(label), negative_binomial_sf(nb_k(i), nb_n(i), nb_p(i)), &
                nb_sf(i), nb_tol_sf(i), 0.0_dp, failures)
            if (nb_pmf(i) > 0.0_dp) then
                write(label, '(a,i0)') 'negative binomial logpmf reference ', i
                call check_close(trim(label), &
                    negative_binomial_logpmf(nb_k(i), nb_n(i), nb_p(i)), log(nb_pmf(i)), &
                    nb_tol_pmf(i) / nb_pmf(i), 0.0_dp, failures)
            end if
            if (nb_cdf(i) > 0.0_dp) then
                write(label, '(a,i0)') 'negative binomial logcdf reference ', i
                call check_close(trim(label), &
                    negative_binomial_logcdf(nb_k(i), nb_n(i), nb_p(i)), log(nb_cdf(i)), &
                    nb_tol_cdf(i) / nb_cdf(i), 0.0_dp, failures)
            end if
            if (nb_sf(i) > 0.0_dp) then
                write(label, '(a,i0)') 'negative binomial logsf reference ', i
                call check_close(trim(label), &
                    negative_binomial_logsf(nb_k(i), nb_n(i), nb_p(i)), log(nb_sf(i)), &
                    nb_tol_sf(i) / nb_sf(i), 0.0_dp, failures)
            end if
        end do
    end subroutine test_negative_binomial_reference

    subroutine test_quantile_reference(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: i
        character(len=80) :: label

        do i = 1, size(geq_prob)
            write(label, '(a,i0)') 'geometric ppf reference ', i
            call check_close(trim(label), geometric_ppf(geq_prob(i), geq_p(i)), &
                geq_ppf(i), 0.0_dp, 0.0_dp, failures)
            write(label, '(a,i0)') 'geometric isf reference ', i
            call check_close(trim(label), geometric_isf(geq_prob(i), geq_p(i)), &
                geq_isf(i), 0.0_dp, 0.0_dp, failures)
        end do

        do i = 1, size(nbq_prob)
            write(label, '(a,i0)') 'negative binomial ppf reference ', i
            call check_close(trim(label), negative_binomial_ppf(nbq_prob(i), nbq_n(i), &
                nbq_p(i)), nbq_ppf(i), 0.0_dp, 0.0_dp, failures)
            write(label, '(a,i0)') 'negative binomial isf reference ', i
            call check_close(trim(label), negative_binomial_isf(nbq_prob(i), nbq_n(i), &
                nbq_p(i)), nbq_isf(i), 0.0_dp, 0.0_dp, failures)
        end do
    end subroutine test_quantile_reference

    subroutine test_identities(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: k

        do k = 0, 1
            call check_close('bernoulli pmf equals binomial n=1', &
                bernoulli_pmf(k, 0.3_dp), binomial_pmf(k, 1, 0.3_dp), &
                0.0_dp, 0.0_dp, failures)
            call check_close('bernoulli cdf equals binomial n=1', &
                bernoulli_cdf(k, 0.3_dp), binomial_cdf(k, 1, 0.3_dp), &
                0.0_dp, 0.0_dp, failures)
        end do
        call check_close('bernoulli ppf equals binomial n=1', bernoulli_ppf(0.7_dp, 0.3_dp), &
            binomial_ppf(0.7_dp, 1.0_dp, 0.3_dp), 0.0_dp, 0.0_dp, failures)

        do k = 1, 20
            call check_close('geometric pmf equals nbinom n=1', geometric_pmf(k, 0.2_dp), &
                negative_binomial_pmf(k - 1, 1.0_dp, 0.2_dp), 8.0_dp * eps, 0.0_dp, &
                failures)
            call check_close('geometric cdf equals nbinom n=1', geometric_cdf(k, 0.2_dp), &
                negative_binomial_cdf(k - 1, 1.0_dp, 0.2_dp), 8.0_dp * eps, 0.0_dp, &
                failures)
        end do

        call check_close('geometric loc shift', geometric_cdf(7.5_dp, 0.2_dp, 0.5_dp), &
            geometric_cdf(7.0_dp, 0.2_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('negative binomial loc shift', &
            negative_binomial_pmf(5.5_dp, 2.5_dp, 0.3_dp, 0.5_dp), &
            negative_binomial_pmf(5.0_dp, 2.5_dp, 0.3_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('bernoulli loc shift', bernoulli_pmf(1.5_dp, 0.3_dp, 0.5_dp), &
            bernoulli_pmf(1.0_dp, 0.3_dp), 0.0_dp, 0.0_dp, failures)
    end subroutine test_identities

    subroutine test_quantile_properties(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        real(dp), parameter :: probabilities(7) = [1.0e-10_dp, 0.001_dp, 0.1_dp, 0.5_dp, &
            0.9_dp, 0.999_dp, 1.0_dp - 1.0e-10_dp]
        integer :: i
        logical :: ok
        real(dp) :: k

        ok = .true.
        do i = 1, size(probabilities)
            k = geometric_ppf(probabilities(i), 0.03_dp)
            ok = ok .and. geometric_cdf(k, 0.03_dp) >= probabilities(i)
            ok = ok .and. (k <= 1.0_dp .or. &
                geometric_cdf(k - 1.0_dp, 0.03_dp) < probabilities(i))
            k = geometric_isf(probabilities(i), 0.03_dp)
            ok = ok .and. geometric_sf(k, 0.03_dp) <= probabilities(i)
            ok = ok .and. (k <= 1.0_dp .or. &
                geometric_sf(k - 1.0_dp, 0.03_dp) > probabilities(i))
        end do
        call check_true('geometric quantile is the smallest count', ok, failures)

        ok = .true.
        do i = 1, size(probabilities)
            k = negative_binomial_ppf(probabilities(i), 2.5_dp, 0.3_dp)
            ok = ok .and. negative_binomial_cdf(k, 2.5_dp, 0.3_dp) >= probabilities(i)
            ok = ok .and. (k == 0.0_dp .or. &
                negative_binomial_cdf(k - 1.0_dp, 2.5_dp, 0.3_dp) < probabilities(i))
            k = negative_binomial_isf(probabilities(i), 2.5_dp, 0.3_dp)
            ok = ok .and. negative_binomial_sf(k, 2.5_dp, 0.3_dp) <= probabilities(i)
            ok = ok .and. (k == -1.0_dp .or. &
                negative_binomial_sf(k - 1.0_dp, 2.5_dp, 0.3_dp) > probabilities(i))
        end do
        call check_true('negative binomial quantile is the smallest count', ok, failures)
    end subroutine test_quantile_properties

    subroutine test_mass_sums(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        integer :: k
        real(dp) :: total

        total = 0.0_dp
        do k = 1, 500
            total = total + geometric_pmf(k, 0.1_dp)
        end do
        call check_close('geometric mass sums to one', total, 1.0_dp, 0.0_dp, 2.0e-14_dp, &
            failures)

        total = 0.0_dp
        do k = 0, 500
            total = total + negative_binomial_pmf(k, 2.5_dp, 0.3_dp)
        end do
        call check_close('negative binomial mass sums to one', total, 1.0_dp, 0.0_dp, &
            3.0e-14_dp, failures)

        total = 0.0_dp
        do k = 0, 7
            total = total + negative_binomial_pmf(k, 2.5_dp, 0.3_dp)
        end do
        call check_close('negative binomial cdf equals partial sum', total, &
            negative_binomial_cdf(7, 2.5_dp, 0.3_dp), 0.0_dp, 2.0e-14_dp, failures)
    end subroutine test_mass_sums

    subroutine test_endpoints(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_close('geometric below support', geometric_pmf(0.0_dp, 0.2_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('geometric non-integer', geometric_pmf(1.5_dp, 0.2_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('geometric cdf floors', geometric_cdf(3.9_dp, 0.2_dp), &
            geometric_cdf(3.0_dp, 0.2_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('geometric p one mass', geometric_pmf(1.0_dp, 1.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('geometric p one ppf', geometric_ppf(0.5_dp, 1.0_dp), 1.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_close('geometric cdf infinity', geometric_cdf(positive_inf, 0.2_dp), &
            1.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('geometric cdf minus infinity', geometric_cdf(negative_inf, 0.2_dp), &
            0.0_dp, 0.0_dp, 0.0_dp, failures)
        call check_close('geometric ppf zero', geometric_ppf(0.0_dp, 0.2_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('geometric ppf one', geometric_ppf(1.0_dp, 0.2_dp) > huge(1.0_dp), &
            failures)
        call check_close('geometric isf one', geometric_isf(1.0_dp, 0.2_dp), 0.0_dp, &
            0.0_dp, 0.0_dp, failures)
        call check_true('geometric isf zero', geometric_isf(0.0_dp, 0.2_dp) > huge(1.0_dp), &
            failures)

        call check_close('negative binomial non-integer count', &
            negative_binomial_pmf(2.5_dp, 2.5_dp, 0.3_dp), 0.0_dp, 0.0_dp, 0.0_dp, &
            failures)
        call check_close('negative binomial p one mass', &
            negative_binomial_pmf(0.0_dp, 2.5_dp, 1.0_dp), 1.0_dp, 0.0_dp, 0.0_dp, &
            failures)
        call check_close('negative binomial p one above', &
            negative_binomial_pmf(1.0_dp, 2.5_dp, 1.0_dp), 0.0_dp, 0.0_dp, 0.0_dp, &
            failures)
        call check_close('negative binomial cdf infinity', &
            negative_binomial_cdf(positive_inf, 2.5_dp, 0.3_dp), 1.0_dp, 0.0_dp, 0.0_dp, &
            failures)
        call check_close('negative binomial ppf zero', &
            negative_binomial_ppf(0.0_dp, 2.5_dp, 0.3_dp), -1.0_dp, 0.0_dp, 0.0_dp, &
            failures)
        call check_true('negative binomial ppf one', &
            negative_binomial_ppf(1.0_dp, 2.5_dp, 0.3_dp) > huge(1.0_dp), failures)
        call check_close('negative binomial isf one', &
            negative_binomial_isf(1.0_dp, 2.5_dp, 0.3_dp), -1.0_dp, 0.0_dp, 0.0_dp, &
            failures)
        call check_true('negative binomial isf zero', &
            negative_binomial_isf(0.0_dp, 2.5_dp, 0.3_dp) > huge(1.0_dp), failures)
    end subroutine test_endpoints

    subroutine test_invalid_and_ieee(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_true('geometric p zero invalid', ieee_is_nan(geometric_pmf(1, 0.0_dp)), &
            failures)
        call check_true('geometric p above one invalid', &
            ieee_is_nan(geometric_cdf(1, 1.1_dp)), failures)
        call check_true('geometric NaN count', ieee_is_nan(geometric_sf(nan_value, 0.2_dp)), &
            failures)
        call check_true('geometric NaN probability', &
            ieee_is_nan(geometric_ppf(nan_value, 0.2_dp)), failures)
        call check_true('negative binomial n zero invalid', &
            ieee_is_nan(negative_binomial_pmf(0, 0.0_dp, 0.3_dp)), failures)
        call check_true('negative binomial n infinite invalid', &
            ieee_is_nan(negative_binomial_cdf(0, positive_inf, 0.3_dp)), failures)
        call check_true('negative binomial p zero invalid', &
            ieee_is_nan(negative_binomial_sf(0, 2.5_dp, 0.0_dp)), failures)
        call check_true('negative binomial NaN count', &
            ieee_is_nan(negative_binomial_cdf(nan_value, 2.5_dp, 0.3_dp)), failures)
        call check_true('bernoulli p invalid', ieee_is_nan(bernoulli_pmf(0, 1.1_dp)), failures)
    end subroutine test_invalid_and_ieee

    subroutine test_integer_interface(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        call check_close('geometric pmf integer argument', geometric_pmf(4, 0.2_dp), &
            geometric_pmf(4.0_dp, 0.2_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('geometric logsf integer argument', geometric_logsf(4, 0.2_dp), &
            geometric_logsf(4.0_dp, 0.2_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('negative binomial pmf integer argument', &
            negative_binomial_pmf(4, 2.5_dp, 0.3_dp), &
            negative_binomial_pmf(4.0_dp, 2.5_dp, 0.3_dp), 0.0_dp, 0.0_dp, failures)
        call check_close('negative binomial cdf integer argument', &
            negative_binomial_cdf(4, 2.5_dp, 0.3_dp), &
            negative_binomial_cdf(4.0_dp, 2.5_dp, 0.3_dp), 0.0_dp, 0.0_dp, failures)
    end subroutine test_integer_interface

    subroutine test_elemental(failures)
        integer, intent(inout) :: failures !! running count of failed checks

        real(dp) :: actual(4)
        real(dp) :: k(4)

        k = [1.0_dp, 2.0_dp, 5.0_dp, 20.0_dp]
        actual = geometric_pmf(k, 0.2_dp)
        call check_close('geometric elemental', actual(3), geometric_pmf(k(3), 0.2_dp), &
            0.0_dp, 0.0_dp, failures)

        actual = negative_binomial_cdf(k, 2.5_dp, [0.2_dp, 0.3_dp, 0.5_dp, 0.8_dp])
        call check_close('negative binomial elemental', actual(2), &
            negative_binomial_cdf(k(2), 2.5_dp, 0.3_dp), 0.0_dp, 0.0_dp, failures)

        actual = bernoulli_pmf([0.0_dp, 1.0_dp, 0.0_dp, 1.0_dp], &
            [0.1_dp, 0.2_dp, 0.3_dp, 0.4_dp])
        call check_close('bernoulli elemental', actual(4), 0.4_dp, 2.0_dp * eps, 0.0_dp, &
            failures)
    end subroutine test_elemental

end program test_discrete_extended
