! SPDX-License-Identifier: MIT
! Copyright (c) 2026 SciFort contributors
!
! Uniform random directions on S^(d-1), generated by normalizing an
! isotropic Gaussian vector.

module scifort_uniform_direction
    use scifort_kinds, only : dp
    use scifort_normal, only : normal_ppf
    use scifort_random, only : rng_state, rng_uniform
    implicit none
    private

    integer, parameter, public :: uniform_direction_status_success = 0
    integer, parameter, public :: uniform_direction_status_invalid_shape = 1
    integer, parameter, public :: uniform_direction_status_numerical_failure = 2

    public :: uniform_direction_rvs
    public :: uniform_direction_rvs_array

contains

    subroutine uniform_direction_rvs(state, sample, status)
        type(rng_state), intent(inout) :: state !! explicit RNG state advanced by the Gaussian draws
        real(dp), intent(out) :: sample(:) !! one unit vector; its length is the spatial dimension
        integer, intent(out), optional :: status !! zero on success; nonzero for invalid/numerical failure

        integer, parameter :: max_attempts = 8
        integer :: attempt
        integer :: i
        real(dp) :: norm2

        if (size(sample) < 1) then
            if (present(status)) status = uniform_direction_status_invalid_shape
            return
        end if

        do attempt = 1, max_attempts
            do i = 1, size(sample)
                sample(i) = normal_ppf(rng_uniform(state))
            end do
            norm2 = dot_product(sample, sample)
            if (norm2 > tiny(1.0_dp)) then
                sample = sample / sqrt(norm2)
                if (present(status)) status = uniform_direction_status_success
                return
            end if
        end do

        sample = 0.0_dp
        if (present(status)) status = uniform_direction_status_numerical_failure
    end subroutine uniform_direction_rvs

    subroutine uniform_direction_rvs_array(state, samples, status)
        type(rng_state), intent(inout) :: state !! explicit RNG state advanced by all draws
        real(dp), intent(out) :: samples(:, :) !! samples by column, shape (dimension, count)
        integer, intent(out), optional :: status !! zero on success; nonzero for invalid/numerical failure

        integer :: j
        integer :: local_status

        if (size(samples,1) < 1) then
            if (present(status)) status = uniform_direction_status_invalid_shape
            return
        end if
        do j = 1, size(samples,2)
            call uniform_direction_rvs(state, samples(:,j), local_status)
            if (local_status /= uniform_direction_status_success) then
                if (present(status)) status = local_status
                return
            end if
        end do
        if (present(status)) status = uniform_direction_status_success
    end subroutine uniform_direction_rvs_array

end module scifort_uniform_direction
