#!/usr/bin/env python3
"""Generate SciPy 1.17 reference values for the Landau distribution."""
from pathlib import Path

import numpy as np
import scipy
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "landau_reference.f90"
X = np.array([-5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 5.0, 20.0, 100.0], dtype=float)
PROBS = np.array([1e-5, 1e-2, 0.2, 0.5, 0.8, 0.99, 1.0 - 1e-5], dtype=float)


def fmt(value):
    value = float(value)
    if np.isnan(value):
        return "ieee_value(0.0_dp, ieee_quiet_nan)"
    if np.isposinf(value):
        return "ieee_value(0.0_dp, ieee_positive_inf)"
    if np.isneginf(value):
        return "ieee_value(0.0_dp, ieee_negative_inf)"
    return f"{value:.17e}_dp"


def arr(name, values):
    vals = [fmt(value) for value in values]
    out = [f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for index, value in enumerate(vals):
        suffix = ", &" if index < len(vals) - 1 else " ]"
        out.append(f"        {value}{suffix}\n")
    return "".join(out)


parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_landau_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_landau_reference\n",
    "    use, intrinsic :: ieee_arithmetic, only : ieee_negative_inf, ieee_positive_inf, &\n",
    "        ieee_quiet_nan, ieee_value\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    arr("landau_x_ref", X),
    arr("landau_prob_ref", PROBS),
]
for method in ["pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"]:
    parts.append(arr("landau_" + method + "_ref", getattr(stats.landau, method)(X)))
parts.append(arr("landau_ppf_ref", stats.landau.ppf(PROBS)))
parts.append(arr("landau_isf_ref", stats.landau.isf(PROBS)))
parts.append("end module test_landau_reference\n")
OUT.write_text("".join(parts), encoding="ascii")
print(OUT)
