#!/usr/bin/env python3
"""Generate deterministic SciPy 1.17 references for resampling inference tests."""

from pathlib import Path

import numpy as np
from scipy import __version__ as scipy_version
from scipy import stats


def literal(value: float) -> str:
    return f"{float(value):.17e}"


def mean_difference(x, y):
    return np.mean(x) - np.mean(y)


def dot_product(x, y):
    return np.dot(x, y)


def fixed_null(size):
    return np.zeros(size, dtype=float)


def fixed_power(size):
    return np.ones(size, dtype=float)


def fixed_power_zero(size):
    return np.zeros(size, dtype=float)


def one_sample_pvalue(sample, axis=-1):
    return np.where(np.mean(sample, axis=axis) > 0.5, 0.01, 0.50)


def two_sample_pvalue(sample_x, sample_y, axis=-1):
    return np.where(np.mean(sample_x, axis=axis) > np.mean(sample_y, axis=axis), 0.01, 0.50)


def main() -> None:
    if scipy_version != "1.17.0":
        raise RuntimeError(f"expected SciPy 1.17.0, found {scipy_version}")

    x = np.array([1.0, 2.0])
    y = np.array([3.0, 4.0])
    independent = stats.permutation_test(
        (x, y), mean_difference, permutation_type="independent",
        n_resamples=100, vectorized=False,
    )
    samples = stats.permutation_test(
        (x, y), mean_difference, permutation_type="samples",
        n_resamples=100, vectorized=False,
    )
    pairings = stats.permutation_test(
        (x, y), dot_product, permutation_type="pairings",
        n_resamples=100, vectorized=False,
    )

    observed = np.array([1.0, 2.0, 3.0])
    monte = stats.monte_carlo_test(
        observed, fixed_null, np.mean, n_resamples=9,
        alternative="greater", vectorized=False,
    )

    power_one = stats.power(
        one_sample_pvalue, fixed_power, 8,
        significance=0.05, vectorized=True, n_resamples=25,
    )
    power_two = stats.power(
        two_sample_pvalue, (fixed_power, fixed_power_zero), (8, 9),
        significance=0.05, vectorized=True, n_resamples=25,
    )

    target = Path(__file__).resolve().parents[1] / "test" / "resampling_inference_reference.f90"
    target.write_text(
        "! Generated by tools/generate_resampling_inference_reference.py with SciPy 1.17.0.\n"
        "module resampling_inference_reference\n"
        "    use scifort_stats, only : dp\n"
        "    implicit none\n"
        "    private\n"
        "    public :: ref_independent_pvalue, ref_samples_pvalue, ref_pairings_pvalue\n"
        "    public :: ref_monte_greater, ref_power_one, ref_power_two\n\n"
        f"    real(dp), parameter :: ref_independent_pvalue = {literal(independent.pvalue)}_dp\n"
        f"    real(dp), parameter :: ref_samples_pvalue = {literal(samples.pvalue)}_dp\n"
        f"    real(dp), parameter :: ref_pairings_pvalue = {literal(pairings.pvalue)}_dp\n"
        f"    real(dp), parameter :: ref_monte_greater = {literal(monte.pvalue)}_dp\n"
        f"    real(dp), parameter :: ref_power_one = {literal(power_one.power)}_dp\n"
        f"    real(dp), parameter :: ref_power_two = {literal(power_two.power)}_dp\n"
        "end module resampling_inference_reference\n",
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
