#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for genextreme, kappa3, kappa4, and truncweibull_min."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import genextreme, kappa3, kappa4, truncweibull_min

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

PROBS = np.array([1e-6, 0.1, 0.5, 0.9, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("ge", genextreme, np.array([-3.0, -1.0, 0.0, 1.0, 2.5]), (0.35,)),
    ("k3", kappa3, np.array([0.05, 0.3, 1.0, 3.0, 20.0]), (2.4,)),
    ("k4", kappa4, np.array([-0.5, 0.0, 0.8, 2.0, 3.1]), (0.5, 0.3)),
    ("tw", truncweibull_min, np.array([0.21, 0.5, 1.0, 1.8, 2.39]), (1.7, 0.2, 2.4)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_genextreme_kappa_truncweibull_reference.py with SciPy 1.17.0.",
    "module test_genextreme_kappa_truncweibull_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines.append("end module test_genextreme_kappa_truncweibull_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "genextreme_kappa_truncweibull_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
