#!/usr/bin/env python3
"""Generate SciPy 1.17 reference values for directional/random-matrix stats."""

from pathlib import Path
import numpy as np
import scipy
from scipy import stats
from scipy.special import ive


def fmt(v):
    v = float(v)
    if np.isnan(v):
        raise ValueError("NaN is not emitted as a parameter constant")
    if np.isposinf(v):
        return "huge(1.0_dp)"
    if np.isneginf(v):
        return "-huge(1.0_dp)"
    return f"{v:.17e}_dp"


def rscalar(name, value):
    return f"    real(dp), parameter :: {name} = {fmt(value)}\n"


def rvec(name, values):
    a = np.asarray(values, dtype=float).reshape(-1)
    lines = [f"    real(dp), parameter :: {name}({a.size}) = [ &\n"]
    for i, v in enumerate(a):
        suffix = ", &" if i < a.size - 1 else " ]"
        lines.append(f"        {fmt(v)}{suffix}\n")
    return "".join(lines)


def ivec(name, values):
    a = np.asarray(values, dtype=int).reshape(-1)
    vals = ", ".join(str(int(v)) for v in a)
    return f"    integer, parameter :: {name}({a.size}) = [{vals}]\n"


def imat(name, values):
    a = np.asarray(values, dtype=int)
    flat = a.flatten(order="F")
    vals = ", ".join(str(int(v)) for v in flat)
    return (f"    integer, parameter :: {name}({a.shape[0]},{a.shape[1]}) = "
            f"reshape([{vals}], [{a.shape[0]},{a.shape[1]}])\n")


def rmat(name, values):
    a = np.asarray(values, dtype=float)
    flat = a.flatten(order="F")
    lines = [f"    real(dp), parameter :: {name}({a.shape[0]},{a.shape[1]}) = reshape([ &\n"]
    for i, v in enumerate(flat):
        suffix = ", &" if i < flat.size - 1 else " ], &"
        lines.append(f"        {fmt(v)}{suffix}\n")
    lines.append(f"        [{a.shape[0]},{a.shape[1]}])\n")
    return "".join(lines)


mu2 = np.array([np.cos(0.4), np.sin(0.4)])
x2 = np.array([np.cos(-0.7), np.sin(-0.7)])
kappa2 = 2.25

mu3 = np.array([1.0, 2.0, 3.0])
mu3 /= np.linalg.norm(mu3)
x3 = np.array([-2.0, 1.0, 2.0])
x3 /= np.linalg.norm(x3)
kappa3 = 4.25

mu5 = np.array([1.0, 2.0, -1.0, 0.5, 3.0])
mu5 /= np.linalg.norm(mu5)
x5 = np.array([0.5, -1.0, 2.0, 1.0, 0.25])
x5 /= np.linalg.norm(x5)
kappa5 = 13.0

fit_data = np.array([
    [1.0, 0.0, 0.0],
    [0.8, 0.6, 0.0],
    [0.8, 0.0, 0.6],
    [0.6, 0.8, 0.0],
    [0.6, 0.0, 0.8],
])
fit_mu, fit_kappa = stats.vonmises_fisher.fit(fit_data)

row = np.array([7, 6])
col = np.array([3, 8, 2])
table = np.array([[1, 5, 1], [2, 3, 1]])

parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_directional_random_matrix_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_directional_random_matrix_reference\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    rscalar("besseli_log_ref", np.log(ive(1.5, 7.0))),
    rscalar("besseli_ratio_ref", ive(2.5, 7.0) / ive(1.5, 7.0)),
    rscalar("besseli_large_log_ref", np.log(ive(50.0, 1000.0))),
    rscalar("besseli_large_ratio_ref", ive(51.0, 1000.0) / ive(50.0, 1000.0)),
    rvec("vmf_mu2_ref", mu2), rvec("vmf_x2_ref", x2), rscalar("vmf_kappa2_ref", kappa2),
    rscalar("vmf_logpdf2_ref", stats.vonmises_fisher.logpdf(x2, mu2, kappa2)),
    rscalar("vmf_pdf2_ref", stats.vonmises_fisher.pdf(x2, mu2, kappa2)),
    rscalar("vmf_entropy2_ref", stats.vonmises_fisher.entropy(mu2, kappa2)),
    rvec("vmf_mu3_ref", mu3), rvec("vmf_x3_ref", x3), rscalar("vmf_kappa3_ref", kappa3),
    rscalar("vmf_logpdf3_ref", stats.vonmises_fisher.logpdf(x3, mu3, kappa3)),
    rscalar("vmf_pdf3_ref", stats.vonmises_fisher.pdf(x3, mu3, kappa3)),
    rscalar("vmf_entropy3_ref", stats.vonmises_fisher.entropy(mu3, kappa3)),
    rvec("vmf_mu5_ref", mu5), rvec("vmf_x5_ref", x5), rscalar("vmf_kappa5_ref", kappa5),
    rscalar("vmf_logpdf5_ref", stats.vonmises_fisher.logpdf(x5, mu5, kappa5)),
    rscalar("vmf_pdf5_ref", stats.vonmises_fisher.pdf(x5, mu5, kappa5)),
    rscalar("vmf_entropy5_ref", stats.vonmises_fisher.entropy(mu5, kappa5)),
    rmat("vmf_fit_data_ref", fit_data.T), rvec("vmf_fit_mu_ref", fit_mu),
    rscalar("vmf_fit_kappa_ref", fit_kappa),
    ivec("random_table_row_ref", row), ivec("random_table_col_ref", col),
    imat("random_table_x_ref", table),
    rscalar("random_table_logpmf_ref", stats.random_table.logpmf(table, row, col)),
    rscalar("random_table_pmf_ref", stats.random_table.pmf(table, row, col)),
    rmat("random_table_mean_ref", stats.random_table.mean(row, col)),
    "end module test_directional_random_matrix_reference\n",
]

out = Path(__file__).resolve().parents[1] / "test" / "test_directional_random_matrix_reference.f90"
out.write_text("".join(parts), encoding="ascii")
print(out)
