#!/usr/bin/env python3
"""Generate SciPy 1.17 references for generalized hyperbolic and Fisher NCHG."""
from pathlib import Path
import numpy as np
import scipy
from scipy import stats, special

OUT = Path(__file__).resolve().parents[1] / "test" / "genhyperbolic_fisher_reference.f90"
probs = np.array([1e-5, 1e-2, 0.2, 0.5, 0.8, 0.99, 1.0-1e-5], dtype=float)
gh_x = np.array([-4.0, -2.0, -0.5, 0.0, 1.0, 3.0, 7.0])
fh_x = np.arange(0.0, 7.0)
gh = stats.genhyperbolic
fh = stats.nchypergeom_fisher


def fmt(x):
    x = float(x)
    if np.isnan(x):
        return "ieee_value(0.0_dp, ieee_quiet_nan)"
    if np.isposinf(x):
        return "ieee_value(0.0_dp, ieee_positive_inf)"
    if np.isneginf(x):
        return "ieee_value(0.0_dp, ieee_negative_inf)"
    return f"{x:.17e}_dp"


def arr(name, xs):
    vals = [fmt(x) for x in xs]
    out = [f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for i, value in enumerate(vals):
        suffix = ", &" if i < len(vals)-1 else " ]"
        out.append(f"        {value}{suffix}\n")
    return "".join(out)


parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_genhyperbolic_fisher_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_genhyperbolic_fisher_reference\n",
    "    use, intrinsic :: ieee_arithmetic, only : ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    arr("reference_probs", probs),
    arr("gh_x", gh_x),
]
for meth in ["pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"]:
    parts.append(arr("gh_" + meth, getattr(gh, meth)(gh_x, 1.2, 2.5, 0.7)))
parts.append(arr("gh_ppf", gh.ppf(probs, 1.2, 2.5, 0.7)))
parts.append(arr("gh_isf", gh.isf(probs, 1.2, 2.5, 0.7)))
parts.append(arr("fh_x", fh_x))
for meth in ["pmf", "logpmf", "cdf", "sf", "logcdf", "logsf"]:
    parts.append(arr("fh_" + meth, getattr(fh, meth)(fh_x, 30, 12, 7, 2.3)))
parts.append(arr("fh_ppf", fh.ppf(probs, 30, 12, 7, 2.3)))
parts.append(arr("fh_isf", fh.isf(probs, 30, 12, 7, 2.3)))
parts.append(arr("bk_scaled_nu", np.array([0.0, 0.5, 2.5, 10.0, 100.0])))
parts.append(arr("bk_scaled_x", np.array([0.1, 0.7, 5.0, 30.0, 1000.0])))
parts.append(arr("bk_scaled_log", np.log(special.kve(
    np.array([0.0, 0.5, 2.5, 10.0, 100.0]),
    np.array([0.1, 0.7, 5.0, 30.0, 1000.0])))))
parts.append("end module test_genhyperbolic_fisher_reference\n")
OUT.write_text("".join(parts), encoding="ascii")
print(OUT)
