#!/usr/bin/env python3
"""Generate SciPy 1.17 reference values for matrix/multivariate families."""

from pathlib import Path
import numpy as np
import scipy
from scipy import stats


def fmt(v):
    v = float(v)
    if np.isnan(v):
        raise ValueError("NaN is not emitted as a parameter constant")
    if np.isposinf(v):
        return "huge(1.0_dp)"
    if np.isneginf(v):
        return "-huge(1.0_dp)"
    return f"{v:.17e}_dp"


def rscalar(name, value):
    return f"    real(dp), parameter :: {name} = {fmt(value)}\n"


def rvec(name, values):
    a = np.asarray(values, dtype=float).reshape(-1)
    lines = [f"    real(dp), parameter :: {name}({a.size}) = [ &\n"]
    for i, v in enumerate(a):
        suffix = ", &" if i < a.size - 1 else " ]"
        lines.append(f"        {fmt(v)}{suffix}\n")
    return "".join(lines)


def ivec(name, values):
    a = np.asarray(values, dtype=int).reshape(-1)
    vals = ", ".join(str(int(v)) for v in a)
    return f"    integer, parameter :: {name}({a.size}) = [{vals}]\n"


def rmat(name, values):
    a = np.asarray(values, dtype=float)
    flat = a.flatten(order="F")
    lines = [f"    real(dp), parameter :: {name}({a.shape[0]},{a.shape[1]}) = reshape([ &\n"]
    for i, v in enumerate(flat):
        suffix = ", &" if i < flat.size - 1 else " ], &"
        lines.append(f"        {fmt(v)}{suffix}\n")
    lines.append(f"        [{a.shape[0]},{a.shape[1]}])\n")
    return "".join(lines)


# Multivariate hypergeometric.
mhg_m = np.array([5, 7, 8])
mhg_x = np.array([1, 2, 3])
mhg_n = 6
mhg = stats.multivariate_hypergeom(mhg_m, mhg_n)

# Normal-inverse-gamma.
nig_mu, nig_lmbda, nig_a, nig_b = 0.4, 2.5, 3.5, 1.7
nig_x, nig_s2 = 0.2, 1.3
nig = stats.normal_inverse_gamma(nig_mu, nig_lmbda, nig_a, nig_b)

# Matrix normal.
mat_mean = np.array([[0.2, -0.1], [0.5, 1.2]])
mat_row = np.array([[1.5, 0.3], [0.3, 0.8]])
mat_col = np.array([[0.7, -0.1], [-0.1, 1.1]])
mat_x = np.array([[0.1, 0.4], [1.0, 0.8]])
matn = stats.matrix_normal(mat_mean, mat_row, mat_col)

# Wishart and inverse Wishart.
wi_scale = np.array([[1.2, 0.2], [0.2, 0.9]])
wi_x = np.array([[2.0, 0.3], [0.3, 1.4]])
wi_df = 5.5
w = stats.wishart(wi_df, wi_scale)
iw = stats.invwishart(wi_df, wi_scale)

# Matrix t.
mt_df = 3.5
mt = stats.matrix_t(mat_mean, mat_row, mat_col, mt_df)
mt_doc_mean = np.arange(6.0).reshape(3, 2)
mt_doc_row = np.diag([1.0, 2.0, 3.0])
mt_doc_col = 0.3 * np.eye(2)
mt_doc_x = mt_doc_mean + 0.1

parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_matrix_distributions_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_matrix_distributions_reference\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    ivec("mhg_m_ref", mhg_m), ivec("mhg_x_ref", mhg_x),
    f"    integer, parameter :: mhg_n_ref = {mhg_n}\n",
    rscalar("mhg_logpmf_ref", mhg.logpmf(mhg_x)),
    rscalar("mhg_pmf_ref", mhg.pmf(mhg_x)),
    rvec("mhg_mean_ref", mhg.mean()), rvec("mhg_var_ref", mhg.var()),
    rmat("mhg_cov_ref", mhg.cov()),
    rscalar("nig_mu_ref", nig_mu), rscalar("nig_lmbda_ref", nig_lmbda),
    rscalar("nig_a_ref", nig_a), rscalar("nig_b_ref", nig_b),
    rscalar("nig_x_ref", nig_x), rscalar("nig_s2_ref", nig_s2),
    rscalar("nig_logpdf_ref", nig.logpdf(nig_x, nig_s2)),
    rscalar("nig_pdf_ref", nig.pdf(nig_x, nig_s2)),
    rvec("nig_mean_ref", nig.mean()), rvec("nig_var_ref", nig.var()),
    rmat("matrix_mean_ref", mat_mean), rmat("matrix_row_ref", mat_row),
    rmat("matrix_col_ref", mat_col), rmat("matrix_x_ref", mat_x),
    rscalar("matrix_normal_logpdf_ref", matn.logpdf(mat_x)),
    rscalar("matrix_normal_pdf_ref", matn.pdf(mat_x)),
    rscalar("matrix_normal_entropy_ref", matn.entropy()),
    rmat("wi_scale_ref", wi_scale), rmat("wi_x_ref", wi_x), rscalar("wi_df_ref", wi_df),
    rscalar("wishart_logpdf_ref", w.logpdf(wi_x)), rscalar("wishart_pdf_ref", w.pdf(wi_x)),
    rmat("wishart_mean_ref", w.mean()), rmat("wishart_mode_ref", w.mode()),
    rmat("wishart_var_ref", w.var()), rscalar("wishart_entropy_ref", w.entropy()),
    rscalar("invwishart_logpdf_ref", iw.logpdf(wi_x)), rscalar("invwishart_pdf_ref", iw.pdf(wi_x)),
    rmat("invwishart_mean_ref", iw.mean()), rmat("invwishart_mode_ref", iw.mode()),
    rmat("invwishart_var_ref", iw.var()), rscalar("invwishart_entropy_ref", iw.entropy()),
    rscalar("matrix_t_df_ref", mt_df), rscalar("matrix_t_logpdf_ref", mt.logpdf(mat_x)),
    rscalar("matrix_t_pdf_ref", mt.pdf(mat_x)),
    rmat("matrix_t_doc_mean_ref", mt_doc_mean), rmat("matrix_t_doc_row_ref", mt_doc_row),
    rmat("matrix_t_doc_col_ref", mt_doc_col), rmat("matrix_t_doc_x_ref", mt_doc_x),
    rscalar("matrix_t_doc_logpdf_ref", stats.matrix_t.logpdf(
        mt_doc_x, mt_doc_mean, mt_doc_row, mt_doc_col, 3.0)),
    rscalar("matrix_t_doc_pdf_ref", stats.matrix_t.pdf(
        mt_doc_x, mt_doc_mean, mt_doc_row, mt_doc_col, 3.0)),
    "end module test_matrix_distributions_reference\n",
]

out = Path(__file__).resolve().parents[1] / "test" / "test_matrix_distributions_reference.f90"
out.write_text("".join(parts), encoding="ascii")
print(out)
