#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for Burr, Mielke, Gibrat, and wrapped Cauchy."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import burr, gibrat, mielke, wrapcauchy

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

PROBS = np.array([1e-6, 0.1, 0.5, 0.9, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("bu", burr, np.array([0.05, 0.3, 1.0, 3.0, 20.0]), (2.3, 1.7)),
    ("mi", mielke, np.array([0.05, 0.3, 1.0, 3.0, 20.0]), (2.4, 1.6)),
    ("gi", gibrat, np.array([0.05, 0.3, 1.0, 3.0, 20.0]), ()),
    ("wc", wrapcauchy, np.array([0.05, 0.8, np.pi, 5.2, 6.2]), (0.4,)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_burr_mielke_gibrat_wrapcauchy_reference.py with SciPy 1.17.0.",
    "module test_burr_mielke_gibrat_wrapcauchy_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines.append("end module test_burr_mielke_gibrat_wrapcauchy_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "burr_mielke_gibrat_wrapcauchy_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
