#!/usr/bin/env python3
"""Generate SciPy 1.17 reference values for the four shape-family checkpoint."""
from pathlib import Path
import numpy as np
import scipy
from scipy import stats

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected scipy 1.17.0, found {scipy.__version__}")

shape = 1.7
probs = np.array([1e-6, 0.1, 0.5, 0.9, 1.0 - 1e-6], dtype=float)
families = [
    ("al", stats.alpha(shape), np.array([0.15, 0.5, 1.0, 2.0, 5.0])),
    ("fl", stats.fatiguelife(shape), np.array([0.15, 0.5, 1.0, 2.0, 5.0])),
    ("gl", stats.genlogistic(shape), np.array([-3.0, -1.0, 0.0, 1.0, 3.0])),
    ("gn", stats.gennorm(shape), np.array([-3.0, -1.0, 0.0, 1.0, 3.0])),
]

def arr(values):
    return ", &\n        ".join(f"{x:.17e}_dp" for x in np.asarray(values, dtype=float))

lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_shape_family_reference.py with SciPy 1.17.0.",
    "module test_shape_family_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    real(dp), parameter :: reference_shape = 1.7_dp",
    "    real(dp), parameter :: reference_probs(5) = [ &",
    f"        {arr(probs)}]",
]
for prefix, dist, x in families:
    values = {
        "x": x,
        "pdf": dist.pdf(x),
        "cdf": dist.cdf(x),
        "sf": dist.sf(x),
        "logcdf": dist.logcdf(x),
        "logsf": dist.logsf(x),
        "ppf": dist.ppf(probs),
        "isf": dist.isf(probs),
    }
    for name, v in values.items():
        lines += [
            f"    real(dp), parameter :: {prefix}_{name}(5) = [ &",
            f"        {arr(v)}]",
        ]
lines.append("end module test_shape_family_reference")
Path("test/shape_family_reference.f90").write_text("\n".join(lines) + "\n", encoding="ascii")
