#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for Gompertz, inverse Weibull, beta-prime, and Burr XII."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import betaprime, burr12, gompertz, invweibull

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

C = 1.7
D = 2.3
PROBS = np.array([1e-6, 0.1, 0.5, 0.9, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("go", gompertz, np.array([0.0, 0.1, 0.5, 1.5, 4.0]), (C,)),
    ("iw", invweibull, np.array([0.1, 0.3, 0.8, 2.0, 8.0]), (C,)),
    ("bp", betaprime, np.array([0.05, 0.2, 0.8, 2.5, 20.0]), (C, D)),
    ("bu", burr12, np.array([0.05, 0.2, 0.8, 2.5, 20.0]), (C, D)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_positive_shape_reference.py with SciPy 1.17.0.",
    "module test_positive_shape_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
    f"    real(dp), parameter, public :: reference_c = {C}_dp",
    f"    real(dp), parameter, public :: reference_d = {D}_dp",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines.append("end module test_positive_shape_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "positive_shape_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
