#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for Nakagami, power-normal, log-gamma, and Wald."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import loggamma, nakagami, powernorm, wald

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

SHAPE = 1.7
PROBS = np.array([1e-6, 0.1, 0.5, 0.9, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("nk", nakagami, np.array([0.15, 0.5, 1.0, 1.6, 3.0]), (SHAPE,)),
    ("pn", powernorm, np.array([-3.0, -1.0, 0.0, 1.0, 3.0]), (SHAPE,)),
    ("lg", loggamma, np.array([-4.0, -1.0, 0.0, 1.0, 3.0]), (SHAPE,)),
    ("wd", wald, np.array([0.15, 0.5, 1.0, 2.0, 5.0]), ()),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_transform_family_reference.py with SciPy 1.17.0.",
    "module test_transform_family_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
    f"    real(dp), parameter, public :: reference_shape = {SHAPE}_dp",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines.append("end module test_transform_family_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "transform_family_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
