#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for four additional continuous laws."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import genexpon, rice, skewnorm, tukeylambda

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

PROBS = np.array([1e-6, 0.1, 0.5, 0.9, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("gx", genexpon, np.array([0.05, 0.3, 0.8, 1.8, 4.0]), (1.3, 0.8, 1.7)),
    ("sn", skewnorm, np.array([-2.0, -0.5, 0.0, 1.0, 2.5]), (3.5,)),
    ("tl", tukeylambda, np.array([-2.0, -0.5, 0.0, 0.75, 2.0]), (0.14,)),
    ("ri", rice, np.array([0.1, 0.5, 1.5, 3.0, 5.0]), (2.0,)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_genexpon_skewnorm_tukeylambda_rice_reference.py with SciPy 1.17.0.",
    "module test_genexpon_skewnorm_tukeylambda_rice_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines.append("end module test_genexpon_skewnorm_tukeylambda_rice_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "genexpon_skewnorm_tukeylambda_rice_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
