#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for multiple-comparison/mean tests."""
from pathlib import Path
import numpy as np
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "multiple_comparisons_reference.f90"


def fmt(x):
    x = float(x)
    if np.isnan(x):
        return "0.0_dp"
    if np.isposinf(x):
        return "huge(0.0_dp)"
    if np.isneginf(x):
        return "-huge(0.0_dp)"
    return f"{x:.17e}_dp"


def arr(name, vals, per_line=2):
    vals = np.asarray(vals, dtype=float).ravel(order="F")
    chunks = []
    for i in range(0, len(vals), per_line):
        chunks.append(", ".join(fmt(v) for v in vals[i:i+per_line]))
    body = ", &\n        ".join(chunks)
    return f"    real(dp), parameter, public :: {name}({len(vals)}) = [{body}]\n"


atlanta = [13.75, 13.75, 13.5, 13.5, 13.0, 13.0, 13.0, 12.75, 12.5]
chicago = [14.25, 13.0, 12.75, 12.5, 12.5, 12.4, 12.3, 11.9, 11.9]
houston = [14.0, 14.0, 13.51, 13.5, 13.5, 13.25, 13.0, 12.5, 12.5]
memphis = [15.0, 14.0, 13.75, 13.59, 13.25, 12.97, 12.5, 12.25, 11.89]
r = stats.alexandergovern(atlanta, chicago, houston, memphis)
alexander_ref = [r.statistic, r.pvalue]

groups = [
    np.array([24.5, 23.5, 26.4, 27.1, 29.9]),
    np.array([28.4, 34.2, 29.5, 32.2, 30.1]),
    np.array([26.1, 28.3, 24.3, 26.2, 27.8]),
]

def tukey_refs(groups, equal_var, level=.95):
    r = stats.tukey_hsd(*groups, equal_var=equal_var)
    ci = r.confidence_interval(level)
    return np.concatenate([
        r.statistic.ravel(order="F"), r.pvalue.ravel(order="F"),
        ci.low.ravel(order="F"), ci.high.ravel(order="F")])


tukey_equal_ref = tukey_refs(groups, True)
tukey_games_ref = tukey_refs(groups, False)
unequal_groups = [
    np.array([1.2, 2.1, 1.7, 2.4]),
    np.array([3.2, 2.8, 3.6, 3.1, 2.9, 3.7]),
    np.array([2.0, 1.8, 2.6, 2.5, 2.3]),
]
tukey_unequal_ref = tukey_refs(unequal_groups, True, .90)

samples = [np.array([3.8, 2.7, 4.0, 2.4]), np.array([2.8, 3.4, 3.7, 2.2, 2.0])]
control = np.array([2.9, 3.0, 2.5, 2.6, 3.2])
dunnett_ref = []
for seed, alt in enumerate(("two-sided", "greater", "less"), start=12345):
    r = stats.dunnett(*samples, control=control, alternative=alt,
                      rng=np.random.default_rng(seed))
    ci = r.confidence_interval(.95)
    dunnett_ref.extend(r.statistic)
    dunnett_ref.extend(r.pvalue)
    dunnett_ref.extend(ci.low)
    dunnett_ref.extend(ci.high)

poisson_ref = []
for case in ((0, 100., 3, 100., 0.),
             (5, 30., 1, 25., 0.),
             (5, 30., 1, 25., .1),
             (12, 40., 8, 25., .05)):
    for alt in ("two-sided", "less", "greater"):
        r = stats.poisson_means_test(case[0], case[1], case[2], case[3],
                                     diff=case[4], alternative=alt)
        poisson_ref.extend([r.statistic, r.pvalue])

lines = [
    "! Generated by tools/generate_multiple_comparisons_reference.py with SciPy 1.17.0.\n",
    "module multiple_comparisons_reference\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    "    private\n",
    arr("alexander_ref", alexander_ref),
    arr("tukey_equal_ref", tukey_equal_ref),
    arr("tukey_games_ref", tukey_games_ref),
    arr("tukey_unequal_ref", tukey_unequal_ref),
    arr("dunnett_ref", dunnett_ref),
    arr("poisson_means_ref", poisson_ref),
    "end module multiple_comparisons_reference\n",
]
OUT.write_text("".join(lines), encoding="ascii")
