#!/usr/bin/env python3
"""Generate SciPy 1.17 references for levy_stable and studentized_range."""
from pathlib import Path

import numpy as np
import scipy
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "levy_stable_studentized_range_reference.f90"

LEVY_CASES = [
    (-3.0, 0.30, 0.00),
    (-1.0, 0.50, 1.00),
    (-0.4, 0.70, -0.50),
    (0.0, 1.00, 0.50),
    (0.7, 1.20, -0.80),
    (1.0, 1.50, 0.00),
    (2.5, 1.80, 0.70),
    (3.0, 2.00, -1.00),
]
LEVY_QCASES = [(1.40, 0.35, p) for p in (1e-4, 1e-2, 0.2, 0.5, 0.8, 0.99, 0.9999)]

SR_CASES = [
    (0.10, 2.0, 1.0),
    (1.00, 3.0, 5.0),
    (2.50, 5.0, 10.0),
    (4.00, 10.0, 100.0),
    (6.00, 5.0, 100.0),
    (1.50, 2.5, 1.0e5),
    (3.00, 8.0, 1.0e5),
    (3.50, 3.0, 100.0),
]
SR_QCASES = [(5.0, 10.0, p) for p in (1e-4, 1e-2, 0.2, 0.5, 0.8, 0.99, 0.9999)]


def fmt(value):
    value = float(value)
    if np.isnan(value):
        return "transfer(9221120237041090560_int64, 0.0_dp)"
    if np.isposinf(value):
        return "transfer(9218868437227405312_int64, 0.0_dp)"
    if np.isneginf(value):
        return "transfer(-4503599627370496_int64, 0.0_dp)"
    return f"{value:.17e}_dp"


def rarr(name, values):
    vals = [fmt(v) for v in values]
    out = [f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for i, value in enumerate(vals):
        suffix = ", &" if i < len(vals) - 1 else " ]"
        out.append(f"        {value}{suffix}\n")
    return "".join(out)


parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_levy_stable_studentized_range_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_levy_stable_studentized_range_reference\n",
    "    use, intrinsic :: iso_fortran_env, only : int64\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    rarr("ls_x_ref", [c[0] for c in LEVY_CASES]),
    rarr("ls_alpha_ref", [c[1] for c in LEVY_CASES]),
    rarr("ls_beta_ref", [c[2] for c in LEVY_CASES]),
    rarr("ls_qalpha_ref", [c[0] for c in LEVY_QCASES]),
    rarr("ls_qbeta_ref", [c[1] for c in LEVY_QCASES]),
    rarr("ls_prob_ref", [c[2] for c in LEVY_QCASES]),
]
for method in ("pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"):
    vals = [getattr(stats.levy_stable, method)(x, a, b) for x, a, b in LEVY_CASES]
    parts.append(rarr(f"ls_{method}_ref", vals))
parts.append(rarr("ls_ppf_ref", [stats.levy_stable.ppf(p, a, b) for a, b, p in LEVY_QCASES]))
parts.append(rarr("ls_isf_ref", [stats.levy_stable.isf(p, a, b) for a, b, p in LEVY_QCASES]))

parts.extend([
    rarr("sr_x_ref", [c[0] for c in SR_CASES]),
    rarr("sr_k_ref", [c[1] for c in SR_CASES]),
    rarr("sr_df_ref", [c[2] for c in SR_CASES]),
    rarr("sr_qk_ref", [c[0] for c in SR_QCASES]),
    rarr("sr_qdf_ref", [c[1] for c in SR_QCASES]),
    rarr("sr_prob_ref", [c[2] for c in SR_QCASES]),
])
for method in ("pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"):
    vals = [getattr(stats.studentized_range, method)(x, k, df) for x, k, df in SR_CASES]
    parts.append(rarr(f"sr_{method}_ref", vals))
parts.append(rarr("sr_ppf_ref", [stats.studentized_range.ppf(p, k, df) for k, df, p in SR_QCASES]))
parts.append(rarr("sr_isf_ref", [stats.studentized_range.isf(p, k, df) for k, df, p in SR_QCASES]))
parts.append("end module test_levy_stable_studentized_range_reference\n")

OUT.write_text("".join(parts), encoding="ascii")
print(OUT)
