#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for four additional continuous laws."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import irwinhall, ksone, ncx2, ncf

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

PROBS = np.array([1e-6, 0.05, 0.5, 0.95, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("ih", irwinhall, np.array([0.2, 1.2, 2.3, 3.4, 4.8]), (5,)),
    ("ko", ksone, np.array([0.03, 0.09, 0.17, 0.26, 0.41]), (20,)),
    ("nx", ncx2, np.array([0.2, 2.0, 8.0, 15.0, 30.0]), (5.0, 3.0)),
    ("nf", ncf, np.array([0.05, 0.3, 1.7, 4.0, 12.0]), (5.0, 12.0, 3.0)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_irwinhall_ksone_ncx2_ncf_reference.py with SciPy 1.17.0.",
    "module test_irwinhall_ksone_ncx2_ncf_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines += emit_array("ko_tiny_ppf", ksone.ppf(np.array([1e-10]), 250))
lines += emit_array("nx_tiny_ppf", ncx2.ppf(np.array([1e-9]), 0.5, 0.0))
lines += emit_array("nx_far_pdf", ncx2.pdf(np.array([900.0]), 80.0, 100.0))
lines += emit_array("nf_far_sf", ncf.sf(np.array([378227639.49492204]), 5.0, 2.5, 100.0))
lines.append("end module test_irwinhall_ksone_ncx2_ncf_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "irwinhall_ksone_ncx2_ncf_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
