#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for contingency/meta-analysis procedures."""
from pathlib import Path
import numpy as np
from scipy import stats
from scipy.stats import contingency

OUT = Path(__file__).resolve().parents[1] / "test" / "contingency_meta_reference.f90"


def fmt(x):
    x = float(x)
    if np.isnan(x):
        return "0.0_dp"  # NaN edge cases are checked structurally in the test.
    if np.isposinf(x):
        return "huge(0.0_dp)"  # Infinite endpoints are checked structurally.
    if np.isneginf(x):
        return "-huge(0.0_dp)"
    return f"{x:.17e}_dp"


def arr(name, vals, per_line=2):
    vals = np.asarray(vals).ravel()
    chunks = []
    for i in range(0, len(vals), per_line):
        chunks.append(", ".join(fmt(v) for v in vals[i:i+per_line]))
    if len(chunks) == 1:
        return f"    real(dp), parameter, public :: {name}({len(vals)}) = [{chunks[0]}]\n"
    body = ", &\n        ".join(chunks)
    return f"    real(dp), parameter, public :: {name}({len(vals)}) = [{body}]\n"


# Binomial test and all three proportion-CI methods.
binom_ref = []
for alt in ("two-sided", "less", "greater"):
    r = stats.binomtest(7, 50, 0.1, alternative=alt)
    binom_ref.extend([r.statistic, r.pvalue])
    for method in ("exact", "wilson", "wilsoncc"):
        ci = r.proportion_ci(method=method)
        binom_ref.extend([ci.low, ci.high])

# Barnard standard vaccine example and a second small table, pooled/unpooled.
barnard_ref = []
for table in (np.array([[7, 12], [8, 3]]), np.array([[1, 2], [3, 4]])):
    for pooled in (True, False):
        for alt in ("two-sided", "less", "greater"):
            r = stats.barnard_exact(table, alternative=alt, pooled=pooled, n=32)
            barnard_ref.extend([r.statistic, r.pvalue])

# Boschloo standard example plus a small table.
boschloo_ref = []
for table in (np.array([[74, 31], [43, 32]]), np.array([[1, 2], [3, 4]])):
    for alt in ("two-sided", "less", "greater"):
        r = stats.boschloo_exact(table, alternative=alt, n=32)
        boschloo_ref.extend([r.statistic, r.pvalue])

# Conditional/sample odds ratio and confidence intervals.
or_table = np.array([[7, 15], [58, 472]])
odds_ref = []
for kind in ("conditional", "sample"):
    r = contingency.odds_ratio(or_table, kind=kind)
    odds_ref.append(r.statistic)
    for alt in ("two-sided", "less", "greater"):
        ci = r.confidence_interval(alternative=alt)
        odds_ref.extend([ci.low, ci.high])

rr = contingency.relative_risk(27, 122, 44, 487)
rr_ci = rr.confidence_interval()
relative_risk_ref = [rr.relative_risk, rr_ci.low, rr_ci.high]

assoc_table = np.array([[100, 150], [203, 322], [420, 700], [320, 210]])
association_ref = [contingency.association(assoc_table, method=m)
                   for m in ("pearson", "cramer", "tschuprow")]

ps = np.array([0.01, 0.2, 0.03, 0.5, 0.001])
weights = np.array([1., 2., 1., 1., 3.])
combine_ref = []
for method in ("fisher", "pearson", "mudholkar_george", "tippett", "stouffer"):
    kwargs = {"weights": weights} if method == "stouffer" else {}
    r = stats.combine_pvalues(ps, method=method, **kwargs)
    combine_ref.extend([r.statistic, r.pvalue])
fdr_bh_ref = stats.false_discovery_control(ps, method="bh")
fdr_by_ref = stats.false_discovery_control(ps, method="by")
fdr_tie_ref = stats.false_discovery_control([0.5, 0.1, 0.1, 0.01], method="bh")

lines = [
    "! Generated by tools/generate_contingency_meta_reference.py with SciPy 1.17.0.\n",
    "module contingency_meta_reference\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    "    private\n",
    arr("binom_ref", binom_ref),
    arr("barnard_ref", barnard_ref),
    arr("boschloo_ref", boschloo_ref),
    arr("odds_ref", odds_ref),
    arr("relative_risk_ref", relative_risk_ref),
    arr("association_ref", association_ref),
    arr("combine_ref", combine_ref),
    arr("fdr_bh_ref", fdr_bh_ref),
    arr("fdr_by_ref", fdr_by_ref),
    arr("fdr_tie_ref", fdr_tie_ref),
    "end module contingency_meta_reference\n",
]
OUT.write_text("".join(lines), encoding="ascii")
