#!/usr/bin/env python3
"""Generate SciPy 1.17 references for GIG, NIG, and Skellam."""
from pathlib import Path
import numpy as np
import scipy
from scipy import stats, special

OUT = Path(__file__).resolve().parents[1] / "test" / "gig_nig_skellam_reference.f90"
probs = np.array([1e-5, 1e-2, 0.2, 0.5, 0.8, 0.99, 1.0-1e-5], dtype=float)
continuous = {
    "gig": (stats.geninvgauss, np.array([0.08,0.2,0.5,1.0,2.0,5.0,15.0]), (1.2,2.3)),
    "nig": (stats.norminvgauss, np.array([-4.,-2.,-0.5,0.,1.,3.,7.]), (2.5,0.7)),
}
sk_x = np.array([-10.,-5.,-2.,0.,2.,5.,10.])

def fmt(x):
    x=float(x)
    if np.isnan(x): return "ieee_value(0.0_dp, ieee_quiet_nan)"
    if np.isposinf(x): return "ieee_value(0.0_dp, ieee_positive_inf)"
    if np.isneginf(x): return "ieee_value(0.0_dp, ieee_negative_inf)"
    return f"{x:.17e}_dp"

def arr(name, xs):
    vals=[fmt(x) for x in xs]
    out=[f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for i,v in enumerate(vals):
        out.append(f"        {v}{', &' if i < len(vals)-1 else ' ]'}\n")
    return "".join(out)

parts=[
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_gig_nig_skellam_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_gig_nig_skellam_reference\n",
    "    use, intrinsic :: ieee_arithmetic, only : ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    arr("reference_probs",probs),
]
for prefix,(dist,x,args) in continuous.items():
    parts.append(arr(prefix+"_x",x))
    for meth in ["pdf","logpdf","cdf","sf","logcdf","logsf"]:
        parts.append(arr(prefix+"_"+meth,getattr(dist,meth)(x,*args)))
    parts.append(arr(prefix+"_ppf",dist.ppf(probs,*args)))
    parts.append(arr(prefix+"_isf",dist.isf(probs,*args)))
parts.append(arr("sk_x",sk_x))
for meth in ["pmf","logpmf","cdf","sf","logcdf","logsf"]:
    parts.append(arr("sk_"+meth,getattr(stats.skellam,meth)(sk_x,3.2,1.7)))
parts.append(arr("sk_ppf",stats.skellam.ppf(probs,3.2,1.7)))
parts.append(arr("sk_isf",stats.skellam.isf(probs,3.2,1.7)))
parts.append(arr("bk_nu",np.array([0.,0.5,1.,2.5,-3.2])))
parts.append(arr("bk_x",np.array([0.1,0.7,2.,5.,20.])))
parts.append(arr("bk_log",np.log(special.kv(np.array([0.,0.5,1.,2.5,-3.2]),np.array([0.1,0.7,2.,5.,20.])))))
parts.append("end module test_gig_nig_skellam_reference\n")
OUT.write_text("".join(parts),encoding="ascii")
print(OUT)
