#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for dgamma, asymmetric Laplace, truncnorm, and loguniform."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import dgamma, laplace_asymmetric, loguniform, truncnorm

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

PROBS = np.array([1e-6, 0.1, 0.5, 0.9, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("dg", dgamma, np.array([-4.0, -1.0, -0.2, 0.5, 3.0]), (2.3,)),
    ("la", laplace_asymmetric, np.array([-3.0, -0.5, 0.0, 0.7, 3.0]), (1.7,)),
    ("tn", truncnorm, np.array([-1.0, -0.5, 0.0, 0.8, 1.8]), (-1.2, 2.0)),
    ("lu", loguniform, np.array([0.25, 0.4, 1.0, 2.0, 4.5]), (0.2, 5.0)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_scipy_transform_reference.py with SciPy 1.17.0.",
    "module test_scipy_transform_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines.append("end module test_scipy_transform_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "scipy_transform_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
