#!/usr/bin/env python3
"""Generate SciPy 1.17 gaussian_kde reference values for Fortran tests."""
from pathlib import Path
import numpy as np
import scipy
from scipy import stats

if scipy.__version__ != "1.17.0":
    raise RuntimeError(f"expected scipy 1.17.0, got {scipy.__version__}")

x1 = np.array([-2.0, -0.5, 0.25, 1.5, 3.0])
p1 = np.array([-1.0, 0.0, 2.0])
k1 = stats.gaussian_kde(x1)
k1_s = stats.gaussian_kde(x1, bw_method="silverman")
k1b = stats.gaussian_kde(np.array([-1.2, 0.1, 0.8, 2.2]))

x2 = np.array([[-1.0, 0.0, 0.5, 2.0, 1.0, 2.5],
               [0.5, -0.2, 1.5, 1.2, 2.4, 0.7]])
w2 = np.array([0.10, 0.20, 0.25, 0.15, 0.20, 0.10])
p2 = np.array([[0.0, 1.2, 2.0], [0.2, 1.7, 1.0]])
k2 = stats.gaussian_kde(x2, weights=w2)
mean2 = np.array([0.3, 0.8])
cov2 = np.array([[0.8, 0.1], [0.1, 0.5]])
low2 = np.array([-0.5, 0.0])
high2 = np.array([1.5, 2.0])
box2 = k2.integrate_box(low2, high2, maxpts=400000,
                        rng=np.random.default_rng(20260922))
k2_c = stats.gaussian_kde(x2, weights=w2, bw_method=0.42)
km = k2.marginal([1])


def scalar(v):
    return f"{float(v):.17e}_dp"


def emit_array(lines, decl, values, reshape_shape=None):
    vals = [scalar(v) for v in np.asarray(values).ravel(order="F")]
    if reshape_shape is None:
        lines.append(f"    {decl} = [ &")
    else:
        lines.append(f"    {decl} = reshape([ &")
    for i, value in enumerate(vals):
        last = i == len(vals) - 1
        if reshape_shape is None:
            suffix = "]" if last else ", &"
        else:
            suffix = "], &" if last else ", &"
        lines.append(f"        {value}{suffix}")
    if reshape_shape is not None:
        dims = ",".join(str(x) for x in reshape_shape)
        lines.append(f"        [{dims}])")


lines = [
    "! Generated by tools/generate_gaussian_kde_reference.py with SciPy 1.17.0.",
    "module gaussian_kde_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    f"    real(dp), parameter :: ref_1d_factor = {scalar(k1.factor)}",
    f"    real(dp), parameter :: ref_1d_cov = {scalar(k1.covariance[0,0])}",
    f"    real(dp), parameter :: ref_1d_silverman_factor = {scalar(k1_s.factor)}",
    f"    real(dp), parameter :: ref_1d_silverman_cov = {scalar(k1_s.covariance[0,0])}",
]
emit_array(lines, "real(dp), parameter :: ref_1d_pdf(3)", k1.pdf(p1))
emit_array(lines, "real(dp), parameter :: ref_1d_logpdf(3)", k1.logpdf(p1))
lines += [
    f"    real(dp), parameter :: ref_1d_box = {scalar(k1.integrate_box_1d(-0.75, 1.25))}",
    f"    real(dp), parameter :: ref_1d_gaussian = {scalar(k1.integrate_gaussian(np.array([0.4]), np.array([[0.7]])))}",
    f"    real(dp), parameter :: ref_1d_kde = {scalar(k1.integrate_kde(k1b))}",
    f"    real(dp), parameter :: ref_2d_neff = {scalar(k2.neff)}",
    f"    real(dp), parameter :: ref_2d_factor = {scalar(k2.factor)}",
]
emit_array(lines, "real(dp), parameter :: ref_2d_cov(2,2)", k2.covariance, (2, 2))
emit_array(lines, "real(dp), parameter :: ref_2d_inv_cov(2,2)", k2.inv_cov, (2, 2))
emit_array(lines, "real(dp), parameter :: ref_2d_pdf(3)", k2.pdf(p2))
emit_array(lines, "real(dp), parameter :: ref_2d_logpdf(3)", k2.logpdf(p2))
lines += [
    f"    real(dp), parameter :: ref_2d_gaussian = {scalar(k2.integrate_gaussian(mean2, cov2))}",
    f"    real(dp), parameter :: ref_2d_box = {scalar(box2)}",
    f"    real(dp), parameter :: ref_constant_factor = {scalar(k2_c.factor)}",
]
emit_array(lines, "real(dp), parameter :: ref_constant_cov(2,2)", k2_c.covariance, (2, 2))
lines.append(f"    real(dp), parameter :: ref_marginal_factor = {scalar(km.factor)}")
emit_array(lines, "real(dp), parameter :: ref_marginal_pdf(3)", km.pdf(np.array([0.0, 1.0, 2.0])))
lines.append("end module gaussian_kde_reference")
Path("test/gaussian_kde_reference.f90").write_text("\n".join(lines) + "\n", newline="\n")
