#!/usr/bin/env python3
"""Generate SciPy 1.17 reference values for finite-sample two-sided KS."""
from pathlib import Path

import numpy as np
import scipy
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "kstwo_reference.f90"
CASES = [
    (1, 0.75),
    (2, 0.40),
    (5, 0.21),
    (5, 0.341),
    (5, 0.49),
    (20, 0.083),
    (20, 0.127),
    (20, 0.303),
    (20, 0.61),
    (100, 0.0613),
    (100, 0.103),
    (100, 0.197),
    (200, 0.042),
    (200, 0.081),
    (200, 0.157),
    (1000, 0.021),
    (1000, 0.041),
]
QNS = [1, 2, 5, 20, 100, 1000]
QPROBS = [1e-3, 0.1, 0.5, 0.9, 0.99]
QCASES = [(n, p) for n in QNS for p in QPROBS]


def fmt(value):
    value = float(value)
    if np.isnan(value):
        return "ieee_value(0.0_dp, ieee_quiet_nan)"
    if np.isposinf(value):
        return "ieee_value(0.0_dp, ieee_positive_inf)"
    if np.isneginf(value):
        return "ieee_value(0.0_dp, ieee_negative_inf)"
    return f"{value:.17e}_dp"


def rarr(name, values):
    vals = [fmt(value) for value in values]
    out = [f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for i, value in enumerate(vals):
        suffix = ", &" if i < len(vals) - 1 else " ]"
        out.append(f"        {value}{suffix}\n")
    return "".join(out)


def iarr(name, values):
    vals = [str(int(value)) for value in values]
    out = [f"    integer, parameter :: {name}({len(vals)}) = [ &\n"]
    for i, value in enumerate(vals):
        suffix = ", &" if i < len(vals) - 1 else " ]"
        out.append(f"        {value}{suffix}\n")
    return "".join(out)


n = np.array([case[0] for case in CASES], dtype=int)
x = np.array([case[1] for case in CASES], dtype=float)
qn = np.array([case[0] for case in QCASES], dtype=int)
prob = np.array([case[1] for case in QCASES], dtype=float)

parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_kstwo_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_kstwo_reference\n",
    "    use, intrinsic :: ieee_arithmetic, only : ieee_negative_inf, ieee_positive_inf, &\n",
    "        ieee_quiet_nan, ieee_value\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    iarr("kstwo_n_ref", n),
    rarr("kstwo_x_ref", x),
    iarr("kstwo_qn_ref", qn),
    rarr("kstwo_prob_ref", prob),
]
for method in ["pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"]:
    vals = [getattr(stats.kstwo, method)(xx, nn) for nn, xx in CASES]
    parts.append(rarr(f"kstwo_{method}_ref", vals))
parts.append(rarr("kstwo_ppf_ref", [stats.kstwo.ppf(p, n) for n, p in QCASES]))
parts.append(rarr("kstwo_isf_ref", [stats.kstwo.isf(p, n) for n, p in QCASES]))
parts.append("end module test_kstwo_reference\n")
OUT.write_text("".join(parts), encoding="ascii")
print(OUT)
