#!/usr/bin/env python3
"""Generate SciPy 1.17 references for nct and gausshyper distributions."""
from pathlib import Path

import numpy as np
import scipy
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "nct_gausshyper_reference.f90"
PROBS = np.array([1e-5, 1e-2, 0.2, 0.5, 0.8, 0.99, 1.0 - 1e-5], dtype=float)
NCT_X = np.array([-2.0, -0.5, 0.0, 1.0, 3.0, 7.0, 15.0], dtype=float)
GH_X = np.array([0.01, 0.05, 0.2, 0.4, 0.6, 0.8, 0.95], dtype=float)


def fmt(value):
    value = float(value)
    if np.isnan(value):
        return "ieee_value(0.0_dp, ieee_quiet_nan)"
    if np.isposinf(value):
        return "ieee_value(0.0_dp, ieee_positive_inf)"
    if np.isneginf(value):
        return "ieee_value(0.0_dp, ieee_negative_inf)"
    return f"{value:.17e}_dp"


def arr(name, values):
    vals = [fmt(value) for value in values]
    out = [f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for index, value in enumerate(vals):
        suffix = ", &" if index < len(vals) - 1 else " ]"
        out.append(f"        {value}{suffix}\n")
    return "".join(out)


parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_nct_gausshyper_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_nct_gausshyper_reference\n",
    "    use, intrinsic :: ieee_arithmetic, only : ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    arr("reference_probs", PROBS),
    arr("nct_x", NCT_X),
]
for method in ["pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"]:
    parts.append(arr("nct_ref_" + method, getattr(stats.nct, method)(NCT_X, 5.0, 2.0)))
parts.append(arr("nct_ref_ppf", stats.nct.ppf(PROBS, 5.0, 2.0)))
parts.append(arr("nct_ref_isf", stats.nct.isf(PROBS, 5.0, 2.0)))
parts.append(arr("gh_x", GH_X))
for method in ["pdf", "logpdf", "cdf", "sf", "logcdf", "logsf"]:
    parts.append(arr("gh_" + method, getattr(stats.gausshyper, method)(GH_X, 2.0, 3.0, 1.5, 2.0)))
parts.append(arr("gh_ppf", stats.gausshyper.ppf(PROBS, 2.0, 3.0, 1.5, 2.0)))
parts.append(arr("gh_isf", stats.gausshyper.isf(PROBS, 2.0, 3.0, 1.5, 2.0)))
parts.append("end module test_nct_gausshyper_reference\n")
OUT.write_text("".join(parts), encoding="ascii")
print(OUT)
