#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for four additional discrete laws."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import randint, planck, dlaplace, logser

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

PROBS = np.array([1e-6, 0.05, 0.5, 0.95, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("ri", randint, np.array([2., 3., 4., 6., 7.]), (2, 9)),
    ("pl", planck, np.array([0., 1., 2., 4., 15.]), (0.7,)),
    ("dl", dlaplace, np.array([-7., -2., 0., 3., 8.]), (0.8,)),
    ("ls", logser, np.array([1., 2., 3., 6., 25.]), (0.8,)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_randint_planck_dlaplace_logser_reference.py with SciPy 1.17.0.",
    "module test_randint_planck_dlaplace_logser_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pmf", "logpmf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
# Stress references for long upper tails / extreme quantiles.
lines += emit_array("pl_far_isf", planck.isf(np.array([1e-12]), 0.05))
lines += emit_array("dl_far_isf", dlaplace.isf(np.array([1e-12]), 0.05))
lines += emit_array("ls_far_isf", logser.isf(np.array([1e-10]), 0.99))
lines += emit_array("ls_far_sf", logser.sf(np.array([1000.0]), 0.99))
lines.append("end module test_randint_planck_dlaplace_logser_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "randint_planck_dlaplace_logser_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
