#!/usr/bin/env python3
"""Generate deterministic SciPy 1.17 reference values for GOF/normality tests."""
from pathlib import Path
import numpy as np
import scipy
from scipy import stats

assert scipy.__version__ == "1.17.0", scipy.__version__

a = np.arange(1.0, 9.0)
b = np.array([1.1, 2.0, 2.5, 3.7, 4.2, 5.9, 7.1, 8.4, 9.0, 10.3, 11.5, 13.0])
x = np.array([-1.2, -0.4, 0.1, 0.7, 1.1])
x2 = np.array([0.1, 0.4, 0.8, 1.2])
y2 = np.array([0.2, 0.3, 0.9, 1.5, 2.0])
cvm_x = np.array([-1.0, -0.2, 0.0, 0.3, 0.7, 1.5, 2.2])
cvm_y = np.array([-0.8, 0.1, 0.4, 0.9, 1.8, 2.5])
shap_x = np.array([0.1, 0.2, 0.3, 0.8, 1.2, 1.5, 2.1, 2.2, 3.0, 3.5])
and_x = np.array([0.2, 0.4, 0.6, 0.9, 1.1, 1.3, 1.8, 2.0, 2.5, 3.1])

skew = stats.skewtest(a)
kurt = stats.kurtosistest(b)
normal = stats.normaltest(b)
jb = stats.jarque_bera(b)
ks1 = stats.ks_1samp(x, stats.norm.cdf, method="exact")
ks1_asymp = stats.ks_1samp(x, stats.norm.cdf, method="asymp")
ks1_approx = stats.ks_1samp(x, stats.norm.cdf, method="approx")
ks2 = stats.ks_2samp(x2, y2, method="exact")
ks2_less = stats.ks_2samp(x2, y2, alternative="less", method="exact")
ks2_greater = stats.ks_2samp(x2, y2, alternative="greater", method="exact")
cvm1 = stats.cramervonmises(x, stats.norm.cdf)
cvm2_exact = stats.cramervonmises_2samp(cvm_x, cvm_y, method="exact")
cvm2_asymp = stats.cramervonmises_2samp(cvm_x, cvm_y, method="asymptotic")
shap = stats.shapiro(shap_x)

ands = {}
for name, vals in [
    ("norm", and_x),
    ("expon", and_x + 0.1),
    ("logistic", and_x),
    ("gumbel_r", and_x),
    ("gumbel_l", and_x),
]:
    r = stats.anderson(vals, dist=name)
    ands[name] = r


def fr(x):
    text = f"{float(x):.17g}"
    if "e" not in text.lower() and "." not in text:
        text += ".0"
    return text + "_dp"


def vec(name, values):
    vals = [fr(v) for v in values]
    lines = [f"    real(dp), parameter :: {name}({len(vals)}) = [ &"]
    for i in range(0, len(vals), 3):
        chunk = ", ".join(vals[i:i + 3])
        suffix = ", &" if i + 3 < len(vals) else " &"
        lines.append(f"        {chunk}{suffix}")
    lines.append("    ]")
    return "\n".join(lines) + "\n"

out = [
    "! Generated by tools/generate_goodness_of_fit_reference.py with SciPy 1.17.0.\n",
    "module goodness_of_fit_reference\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    "    public\n\n",
]
for name, r in [("skew", skew), ("kurt", kurt), ("normal", normal), ("jb", jb)]:
    out.append(vec(name + "_ref", [r.statistic, r.pvalue]))
out.append(vec("ks1_ref", [ks1.statistic, ks1.pvalue, ks1.statistic_location, ks1.statistic_sign]))
out.append(vec("ks1_methods_ref", [ks1_asymp.pvalue, ks1_approx.pvalue]))
out.append(vec("ks2_ref", [ks2.statistic, ks2.pvalue, ks2.statistic_location, ks2.statistic_sign]))
out.append(vec("ks2_one_sided_ref", [ks2_less.statistic, ks2_less.pvalue, ks2_greater.statistic, ks2_greater.pvalue]))
out.append(vec("cvm_ref", [cvm1.statistic, cvm1.pvalue, cvm2_exact.statistic, cvm2_exact.pvalue, cvm2_asymp.pvalue]))
out.append(vec("shapiro_ref", [shap.statistic, shap.pvalue]))
for name, r in ands.items():
    out.append(f"    real(dp), parameter :: and_{name}_stat = {fr(r.statistic)}\n")
    out.append(vec(f"and_{name}_critical", r.critical_values))
    out.append(vec(f"and_{name}_sig", r.significance_level))
    params = list(r.fit_result.params)
    out.append(vec(f"and_{name}_fit", params))
out.append("end module goodness_of_fit_reference\n")
Path("test/goodness_of_fit_reference.f90").write_text("".join(out), encoding="ascii")
