#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for four folded/reciprocal families."""
from pathlib import Path
import numpy as np
import scipy
from scipy.stats import foldcauchy, foldnorm, recipinvgauss, truncpareto

if scipy.__version__ != "1.17.0":
    raise SystemExit(f"expected SciPy 1.17.0, found {scipy.__version__}")

PROBS = np.array([1e-6, 0.1, 0.5, 0.9, 1 - 1e-6], dtype=float)
FAMILIES = [
    ("fn", foldnorm, np.array([0.0, 0.2, 1.0, 2.0, 4.0]), (1.3,)),
    ("fc", foldcauchy, np.array([0.0, 0.2, 1.0, 2.0, 8.0]), (0.8,)),
    ("ri", recipinvgauss, np.array([0.05, 0.2, 0.7, 2.0, 6.0]), (0.7,)),
    ("tp", truncpareto, np.array([1.05, 1.2, 2.0, 3.5, 4.9]), (1.7, 5.0)),
]


def fval(x: float) -> str:
    if np.isneginf(x):
        return "-huge(1.0_dp)"
    if np.isposinf(x):
        return "huge(1.0_dp)"
    return f"{float(x):.17e}_dp"


def emit_array(name: str, values: np.ndarray) -> list[str]:
    values = np.asarray(values)
    lines = [f"    real(dp), parameter, public :: {name}({values.size}) = [ &"]
    for i, value in enumerate(values):
        suffix = ", &" if i + 1 < values.size else "]"
        lines.append(f"        {fval(value)}{suffix}")
    return lines


lines = [
    "! SPDX-License-Identifier: MIT",
    "! Generated by tools/generate_folded_reciprocal_reference.py with SciPy 1.17.0.",
    "module test_folded_reciprocal_reference",
    "    use scifort_kinds, only : dp",
    "    implicit none",
    "    private",
]
lines += emit_array("reference_probs", PROBS)
for prefix, dist, x, args in FAMILIES:
    lines += emit_array(f"{prefix}_x", x)
    for method in ("pdf", "cdf", "sf", "logcdf", "logsf"):
        lines += emit_array(f"{prefix}_{method}", getattr(dist, method)(x, *args))
    lines += emit_array(f"{prefix}_ppf", dist.ppf(PROBS, *args))
    lines += emit_array(f"{prefix}_isf", dist.isf(PROBS, *args))
lines.append("end module test_folded_reciprocal_reference")
lines.append("")

out = Path(__file__).resolve().parents[1] / "test" / "folded_reciprocal_reference.f90"
out.write_text("\n".join(lines), encoding="ascii")
