#!/usr/bin/env python3
"""Generate SciPy 1.17 references for four power-law discrete families."""
from pathlib import Path
import numpy as np
import scipy
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "betanbinom_yulesimon_zipf_zipfian_reference.f90"
probs = np.array([1e-8, 1e-4, 0.05, 0.5, 0.9, 0.999, 1.0-1e-8], dtype=float)
cases = {
    "bn": (stats.betanbinom, np.array([0.,1.,3.,10.,30.,100.,500.]), (4,2.7,1.4)),
    "ys": (stats.yulesimon, np.array([1.,2.,3.,5.,10.,30.,100.]), (2.5,)),
    "zp": (stats.zipf, np.array([1.,2.,3.,5.,10.,30.,100.]), (2.3,)),
    "zi": (stats.zipfian, np.array([1.,2.,3.,5.,10.,30.,49.]), (1.2,50)),
}

def fmt(x):
    x=float(x)
    if np.isnan(x): return "ieee_value(0.0_dp, ieee_quiet_nan)"
    if np.isposinf(x): return "ieee_value(0.0_dp, ieee_positive_inf)"
    if np.isneginf(x): return "ieee_value(0.0_dp, ieee_negative_inf)"
    return f"{x:.17e}_dp"

def arr(name, xs):
    vals=[fmt(x) for x in xs]
    lines=[f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for i,v in enumerate(vals):
        suffix = ", &" if i < len(vals)-1 else " ]"
        lines.append(f"        {v}{suffix}\n")
    return "".join(lines)


parts=[
"! SPDX-License-Identifier: MIT\n",
"! Generated by tools/generate_betanbinom_yulesimon_zipf_zipfian_reference.py\n",
f"! SciPy version: {scipy.__version__}\n",
"module test_betanbinom_yulesimon_zipf_zipfian_reference\n",
"    use scifort_kinds, only : dp\n",
"    implicit none\n",
arr("reference_probs",probs),
]
for prefix,(dist,x,args) in cases.items():
    parts.append(arr(prefix+"_x",x))
    for meth in ["pmf","logpmf","cdf","sf","logcdf","logsf"]:
        parts.append(arr(prefix+"_"+meth,getattr(dist,meth)(x,*args)))
    parts.append(arr(prefix+"_ppf",dist.ppf(probs,*args)))
    parts.append(arr(prefix+"_isf",dist.isf(probs,*args)))
parts.append("end module test_betanbinom_yulesimon_zipf_zipfian_reference\n")
OUT.write_text("".join(parts), encoding="ascii")
print(OUT)
