#!/usr/bin/env python3
"""Generate SciPy 1.17.0 references for additional nonparametric tests."""
from pathlib import Path
import warnings
import numpy as np
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "nonparametric_extended_reference.f90"

def fmt(x):
    return f"{float(x):.17e}".replace("e", "e") + "_dp"

def arr(name, vals):
    vals = np.asarray(vals).ravel()
    chunks = []
    for i in range(0, len(vals), 2):
        chunks.append(", ".join(fmt(v) for v in vals[i:i+2]))
    if len(chunks) == 1:
        return f"    real(dp), parameter, public :: {name}({len(vals)}) = [{chunks[0]}]\n"
    body = ", &\n        ".join(chunks)
    return f"    real(dp), parameter, public :: {name}({len(vals)}) = [{body}]\n"

x = np.array([1., 2., 5., 7., 9.])
y = np.array([0., 3., 4., 6., 8., 10.])
xt = np.array([1., 2., 2., 5., 7.])
yt = np.array([0., 2., 4., 6., 8., 8.])
ans = []
for alt in ("two-sided", "less", "greater"):
    r = stats.ansari(x, y, alternative=alt)
    ans.extend([r.statistic, r.pvalue])
for alt in ("two-sided", "less", "greater"):
    r = stats.ansari(xt, yt, alternative=alt)
    ans.extend([r.statistic, r.pvalue])

mood_vals = []
for xx, yy in ((x, y), (xt, yt)):
    for alt in ("two-sided", "less", "greater"):
        r = stats.mood(xx, yy, alternative=alt)
        mood_vals.extend([r.statistic, r.pvalue])

xe = np.array([1., 2., 2.5, 3.5, 5., 8., 13., 21.])
ye = np.array([0.5, 1.5, 2.2, 4., 4.5, 7., 11., 18., 29.])
e1 = stats.epps_singleton_2samp(xe, ye)
e2 = stats.epps_singleton_2samp(xe, ye, t=[0.3, 0.7, 1.1])
epps = [e1.statistic, e1.pvalue, e2.statistic, e2.pvalue]

ax = np.array([-2., -1.2, -0.8, -0.2, 0.1, 0.4, 0.9, 1.4, 2., 2.5])
ay = np.array([-0.3, 0.4, 1., 1.5, 1.8, 2.2, 2.6, 3.1, 3.7, 4.3])
and_vals = []
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for variant in ("midrank", "right", "continuous"):
        r = stats.anderson_ksamp([ax, ay], variant=variant)
        and_vals.extend([r.statistic, r.pvalue])
    legacy = stats.anderson_ksamp([ax, ay])
critical = legacy.critical_values

s1 = np.array([1., 2., 2., 4., 6.])
s2 = np.array([0., 2., 3., 5.])
s3 = np.array([1., 3., 3., 7., 8., 9.])
and_tie = []
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for variant in ("midrank", "right"):
        r = stats.anderson_ksamp([s1, s2, s3], variant=variant)
        and_tie.extend([r.statistic, r.pvalue])

g1 = np.array([10,14,14,18,20,22,24,25,31,31,32,39,43,43,48,49.])
g2 = np.array([28,30,31,33,34,35,36,40,44,55,57,61,91,92,99.])
g3 = np.array([0,3,9,22,23,25,25,33,34,34,40,45,46,48,62,67,84.])
med = []
tables = []
for ties in ("below", "above", "ignore"):
    r = stats.median_test(g1, g2, g3, ties=ties)
    med.extend([r.statistic, r.pvalue, r.median])
    tables.append(np.asarray(r.table, dtype=int))
r = stats.median_test(g1, g2, g3, lambda_="log-likelihood")
med.extend([r.statistic, r.pvalue])

lines = [
    "! Generated by tools/generate_nonparametric_extended_reference.py with SciPy 1.17.0.\n",
    "module nonparametric_extended_reference\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    "    private\n",
    arr("ansari_ref", ans),
    arr("mood_ref", mood_vals),
    arr("epps_ref", epps),
    arr("anderson_ref", and_vals),
    arr("anderson_tie_ref", and_tie),
    arr("anderson_critical_ref", critical),
    arr("median_ref", med),
]
for i, table in enumerate(tables, 1):
    flat = table.ravel(order="F")
    vals = ", ".join(str(int(v)) for v in flat)
    lines.append(f"    integer, parameter, public :: median_table_{i}(2, 3) = reshape([{vals}], [2, 3])\n")
lines.append("end module nonparametric_extended_reference\n")
OUT.write_text("".join(lines), encoding="ascii")
