#!/usr/bin/env python3
"""Generate SciPy 1.17 references for Wallenius NCHG and Poisson-binomial."""
from pathlib import Path
import numpy as np
import scipy
from scipy import stats

OUT = Path(__file__).resolve().parents[1] / "test" / "wallenius_poisson_binom_reference.f90"
probs = np.array([1e-6, 1e-3, 0.05, 0.25, 0.5, 0.75, 0.95, 1-1e-3, 1-1e-6], dtype=float)
wall_x = np.arange(0.0, 7.0)
pb_p = np.array([0.05, 0.2, 0.35, 0.6, 0.9], dtype=float)
pb_x = np.arange(0.0, 5.0)
wall = stats.nchypergeom_wallenius
pb = stats.poisson_binom


def fmt(x):
    x = float(x)
    if np.isnan(x):
        return "ieee_value(0.0_dp, ieee_quiet_nan)"
    if np.isposinf(x):
        return "ieee_value(0.0_dp, ieee_positive_inf)"
    if np.isneginf(x):
        return "ieee_value(0.0_dp, ieee_negative_inf)"
    return f"{x:.17e}_dp"


def arr(name, xs):
    vals = [fmt(x) for x in xs]
    out = [f"    real(dp), parameter :: {name}({len(vals)}) = [ &\n"]
    for i, value in enumerate(vals):
        suffix = ", &" if i < len(vals)-1 else " ]"
        out.append(f"        {value}{suffix}\n")
    return "".join(out)

parts = [
    "! SPDX-License-Identifier: MIT\n",
    "! Generated by tools/generate_wallenius_poisson_binom_reference.py\n",
    f"! SciPy version: {scipy.__version__}\n",
    "module test_wallenius_poisson_binom_reference\n",
    "    use, intrinsic :: ieee_arithmetic, only : ieee_negative_inf, ieee_positive_inf, ieee_quiet_nan, ieee_value\n",
    "    use scifort_kinds, only : dp\n",
    "    implicit none\n",
    arr("reference_probs", probs),
    arr("wall_x", wall_x),
]
for meth in ["pmf", "logpmf", "cdf", "sf", "logcdf", "logsf"]:
    parts.append(arr("wall_" + meth, getattr(wall, meth)(wall_x, 30, 12, 7, 2.3)))
parts.append(arr("wall_ppf", wall.ppf(probs, 30, 12, 7, 2.3)))
parts.append(arr("wall_isf", wall.isf(probs, 30, 12, 7, 2.3)))
parts.append(arr("pb_p", pb_p))
parts.append(arr("pb_x", pb_x))
for meth in ["pmf", "logpmf", "cdf", "sf", "logcdf", "logsf"]:
    parts.append(arr("pb_" + meth, getattr(pb, meth)(pb_x, pb_p)))
parts.append(arr("pb_ppf", pb.ppf(probs, pb_p)))
parts.append(arr("pb_isf", pb.isf(probs, pb_p)))
parts.append("end module test_wallenius_poisson_binom_reference\n")
OUT.write_text("".join(parts), encoding="ascii")
print(OUT)
